### ISSUE TITLE
firstDayOfWeek and lastDayofWeek incorrect results

### ISSUE THREAD

**Issue by oyalhi** [malcommac/SwiftDate#1]
I am +2 GMT zone. For today, the first day of week shows as 10 (sunday) which is incorrect. the last day shows as 17 (sunday). If firstdayofweek is 10 then the lastdayofweek should be 16.  The firstdayofweek for my computer is 11 and the last day is 17 (monday is the first day of week).

![screen shot 2015-05-13 at 12 33 53](https://cloud.githubusercontent.com/assets/11165954/7607722/60e5ed84-f96c-11e4-9cd9-5b9b88c5a078.png)

**Comment by malcommac** [comment]
Hi,
I've fixed the bug and now it should works fine.
SwiftDate 1.0.3 reference commit is here: cc2432dd0dfa6ddfdf69fa68f61ce922fe7e5ed0

**Comment by oyalhi** [comment]
Works like a charm, thank you.
