### ISSUE TITLE
Upgrade "Other" time zone types to the main division

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#108]
Instead of `.Other.UTC` or `.Other.Default` please consider moving these items one level up in the hierarchy. This would result in plain `.UTC` and `.Default` respectively.

The items are too important to be stuffed away under "Other"

**Comment by malcommac** [comment]
TimeZoneConvertible is now the main protocol and expose GMT/Default/System/Local at root level.
For example you can type ```TimeZones.GMT```.

Fixed in commit https://github.com/malcommac/SwiftDate/commit/15395a429e2901f325a7b0884a91cf1e6af18cac
