### ISSUE TITLE
Compile error with optimization level 'Fast [-O]'

### ISSUE THREAD

**Issue by twiedow** [malcommac/SwiftDate#112]
I get a compile error for this line of code

```
    let tomorrow = today.add([.Day: 1])
```

where today is an NSDate object, but only when the optimization level is set to fast (which is the default for release builds).

SWIFT_OPTIMIZATION_LEVEL = -O

![screen shot 2015-12-15 at 09 29 30](https://cloud.githubusercontent.com/assets/656549/11805714/5e84d6bc-a30e-11e5-8566-dce2de3029e0.png)

**Comment by twiedow** [comment]
By the way, this is working:

```
    let tomorrow = today.add(days: 1)
```

**Comment by Hout** [comment]
Weird! Needs investigation. Thx for the issue.

**Comment by malcommac** [comment]
It's okay with SwiftDate4.
The new function which accomplish your request is:

```swift
let tomorrow = try! Date().add(components: [.day : 1])
```
