### ISSUE TITLE
1.days - 1.hours results in (-1.days, -1.hours) components

### ISSUE THREAD

**Issue by TadeasKriz** [malcommac/SwiftDate#119]
We are using SwiftDate to do offset certain dates. Recently I got a strange problem that this code:

`(1.days - 1.hours).fromNow()` does not equal to `23.hours.fromNow()`. I looked into it more and the problem is that `(1.days - 1.hours)` returns NSDateComponents with `Day: -1` and `Hour: -1`, instead of `Day: 1` and `Hour: -1`. So I dug into the SwiftDate code a probably found the root cause.

In file [DateInRegion on line 872](https://github.com/malcommac/SwiftDate/blob/master/SwiftDate/DateInRegion.swift#L872), there is this code:
`let finalValue =  ((leftValue + rightValue) * (sum == true ? 1 : -1))`
Instead it should be this:
`let finalValue =  leftValue + (rightValue * (sum == true ? 1 : -1))`

**Comment by Hout** [comment]
Good find! I will include this in the current develop branch.
Thx!

**Comment by Hout** [comment]
Although... In the development branch there is no sum function... :-)=)
I will include this particular circumstance in the unit tests and investigate.

**Comment by TadeasKriz** [comment]
Damn, I didn't check the development branch, sorry :/

**Comment by TadeasKriz** [comment]
But it is still there. Just in a different file: https://github.com/malcommac/SwiftDate/blob/develop/SwiftDate/NSDateComponents%2BSwiftDate.swift#L143

**Comment by Hout** [comment]
I looked in the wrong place. Working on it!

**Comment by TadeasKriz** [comment]
Awesome, thanks!

**Comment by Hout** [comment]
Fixed this one and included test code (see commit above). Can you confirm that this works @TadeasKriz?

**Comment by TadeasKriz** [comment]
Yes I will test it and let you know.

**Comment by TadeasKriz** [comment]
Seems to work properly now, thanks!
