### ISSUE TITLE
DateInRegion.localDate returns incorrect day for some regions

### ISSUE THREAD

**Issue by RustamG** [malcommac/SwiftDate#124]
Hi.

```swift
let date = DateInRegion(
                        year: 2012, month: 1, day: 31, 
                        hour: 0, minute: 0, second: 0, 
                        region: Region(tzType: TimeZoneNames.Europe.Kaliningrad))

let day = date.localDate!.day // why does it return 30???
```

The description for `date` seems to be ok: 
"UTC: 2012-01-30 21:00:00 +0000 (LOCAL: Optional("2012-01-**31**T00:00:00+0300") | Europe/Kaliningrad | gregorian | (en_US))"

**Comment by Hout** [comment]
It should represent the day number in the region mentioned. You have set it to midnight on the 31st in Kaliningrad. If your device local time zone deviates from that, e.g. in London, it could be the 30th.
Which version of the library do you use?

**Comment by RustamG** [comment]
I use pod version 2.0.2. I've set Kaliningrad timezone on my pc and restarted the simulator to have the same timezone in it. I guess the problem is because localDate doesn't consider DST.

To reproduce the issue please set your device's timezone to Kaliningrad. Download the attached archive and look at the tests `test_dateinregion_localdate_date_considering_dst()` and `test_dateinregion_localdate_date()`

[SwiftDate-master.zip](https://github.com/malcommac/SwiftDate/files/71482/SwiftDate-master.zip)

**Comment by RustamG** [comment]
It would be great if you release the version with the PR https://github.com/malcommac/SwiftDate/pull/125 before the localDate disappear.

**Comment by Hout** [comment]
Hmmm it does not make sense at all to change an absolute time object like NSDate in order to represent it in a different time zone whatsoever.

In the new develop branch localDate and UTCDate are canned. They create confusion as NSDate does not have a time zone reference. As such it is not wise to suggest that a date is "local" or "UTC" and to change it by changing the absolute time. In fact NSDate applies to all time zones, it is just represented differently depending on date region.

I included these tests that evaluate to `true`:
```
let utc = DateRegion(tzName: TimeZones.GMT)

it("should have been initialised with the Kaliningrad time zone and calendar in winter") {
    let date = NSDate(year: 2015, month: 12, day: 25, hour: 2, calType: .Gregorian, tzName: TimeZones.Europe.Kaliningrad)!
    expect(date.toString(DateFormat.ISO8601, inRegion: utc)) == "2015-12-25T00:00:00+0000"
}                
 
it("should have been initialised with the Kaliningrad time zone and calendar in summer") {
    let date = NSDate(year: 2015, month: 6, day: 25, hour: 2, calType: .Gregorian, tzName: TimeZones.Europe.Kaliningrad)!
    expect(date.toString(DateFormat.ISO8601, inRegion: utc)) == "2015-06-25T00:00:00+0000"
}            
```

@malcommac can you evaluate #125? Is it worthwhile to implement a hotfix?

**Comment by RustamG** [comment]
Yeah. I understand that NSDate applies to all time zones. I use localDate because it is easy to get components in a specific time zone and to perform calculations on the dates in specific time zone.

**Comment by Hout** [comment]
`localDate` is canned in v3.0.0.
