### ISSUE TITLE
Naming DateRegion

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#127]
Branch from the discussion in #123.

The rationale for renaming it to `DateRegion` was that `Region` is too general; it could be used in a different context which is not at all imaginary when working in a international context. 
`Region` is backward compatible.

It is obvious that the naming causes confusion with `DateInRegion` and it would be easily resolved by renaming it back to `Region`.  Maybe it is a good idea, but also maybe we can find another -more specific- name?

**Comment by Hout** [comment]
Area?

**Comment by malcommac** [comment]
Frankly I've not any better idea right now... sic!
(But if you we stay with `DateInRegion` and `Region` encapsulate params for `DateInRegion` seems natural `Region` is the name for this struct)

**Comment by Hout** [comment]
Agreed, let's move back to `Region`

**Comment by Hout** [comment]
Done in 68e121438f6934b1a15bf98410c2f85308cecea5
