### ISSUE TITLE
Follow SWIFT style guide

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#131]
https://github.com/raywenderlich/swift-style-guide
Rationale:
- generally accepted style makes code accessible to as many programmers as possible.
- It is more effective to adopt ideas that have been evaluated by many than to invent an idea of a few.

**Comment by shams-ahmed** [comment]
great idea, also look at [SwiftLint](https://github.com/realm/SwiftLint) to help enforce consistency

**Comment by malcommac** [comment]
I've tried using SwiftLint into the code but 99% of the warnings are related to line length or white lines.
I'm not sure this could be a bold move.
However I'm okay with the Swift Style Guideline at the top of the issue. I'll check the code for it.

**Comment by Hout** [comment]
I do not think that SwiftLint should be prio no 1.
Let us move towards releasing and move this one forward in time.

**Comment by shams-ahmed** [comment]
@malcommac use a custom configuration for SwiftLint, most things be can enabled/disabled

**Comment by Hout** [comment]
SwiftLint will not be usable with the full configuration indeed. Part of the code follows the style guide already.

To do:
- check swiftlint for usability
- adjust code
- include style guide in design guidelines

**Comment by Hout** [comment]
Swiftlint is adhered to except for some complexity issues that need further investigation.
Code is adjusted
Style guide in design guidelines.
Part of 3.0.4 ahead of the scheduled 3.1.0 milestone!
