### ISSUE TITLE
Consider using struct as opposed to class

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#136]
For `DateInRegion` and `Region` classes, consider using `structs`.

From [Swift don't do that](http://ericasadun.com/2015/05/05/swift-dont-do-that/):
*Use classes if you want reference types. Use structs if you want value types. You can add functionality to both (and to enumerations) in Swift. When in doubt, err on the side of value types. If your construct doesn’t have a life cycle, or two constructs with similar values should be considered as the same thing, use a struct.*

**Comment by malcommac** [comment]
Okay we can merge this feature into develop

**Comment by Hout** [comment]
Not quite: develop branch fails to compile with struct in DateInRegionFormatterPort:
```
		let bundle = NSBundle(forClass: DateInRegion.self)
```

**Comment by malcommac** [comment]
We can pass another class part of the library if our intent is to get the path inside SwiftDste package itself. Right?

**Comment by Hout** [comment]
Yep, but this is probably trivial if we adopt NSDateComponentsFormatter?

**Comment by malcommac** [comment]
Could we consider it closed?

**Comment by Hout** [comment]
I think issues should be closed when the solution branch is merged into the master ;-)

**Comment by Hout** [comment]
My proposal is to round everything up, do a mutual review of code, test code and docs and start the release process as I described in TEAM.md. Good thinking?

**Comment by malcommac** [comment]
Okay I've missed the point with master branch and gitflow. You are absolutely right.
Today I'll check the code for Swift Guidelines as described in [\#131](https://github.com/malcommac/SwiftDate/issues/131).

Would you check toNaturalString() of DateInRegion and toString() of NSTimeInterval so we can add both to the doc and tests? I've just added it recently but all of these commits were made directly on develop (my fault).

**Comment by Hout** [comment]
Feature branches are handy when multiple people are working on the same code. No big deal (yet) ;-)

I will spend some time this afternoon.

**Comment by Hout** [comment]
Fixed in v3.0.0
