### ISSUE TITLE
Feature request: duration formatting

### ISSUE THREAD

**Issue by irace** [malcommac/SwiftDate#137]
E.g. something like

```swift
let interval: NSTimeInterval = 60 * 60
print(interval.toFormatString()) // “1 hour”
```

**Comment by malcommac** [comment]
Should it work only with NSTimeInterval? So you can pass an arbitrary number of seconds and you get it using specified unit of times.

**Comment by irace** [comment]
I think so!

**Comment by Hout** [comment]
Can be done with NSDateComponentFormatter too.

**Comment by irace** [comment]
> Can be done with `NSDateComponentFormatter` too.

Can you provide an example? I was trying to figure out how to do this but could not.

**Comment by Hout** [comment]
```
let interval: NSTimeInterval = 63
let formatter = NSDateComponentsFormatter()

formatter.unitsStyle = .Full
formatter.allowedUnits = [.Hour, .Minute, .Second]

formatter.stringFromTimeInterval(interval)  // "1 minute, 3 seconds"
```

**Comment by malcommac** [comment]
However seems it does not work fine with negative intervals

**Comment by malcommac** [comment]
`NSTimeInterval` now has a `toString(style:)` function you can use to convert a duration into a readable string.
Example:

```swift
let duration = NSTimeInterval( (60*60*24) ).toString() // print "1d"
```

You can also specify the style of the formatted output by passing a FormatterStyle struct:

```swift
let duration = NSTimeInterval( (60*60*24) ).toString(FormatterStyle(style: .Full)) // print "1 day"
```


-----
`FormatterStyle` is a struct where you can set:

```swift
public var style :NSDateComponentsFormatterUnitsStyle = .Abbreviated
```
>Configure the strings to use for unit names such as days, hours, minutes and seconds. Use this property to specify the style of abbreviations used to identify each time component. By default the value of this property is .Abbreviated; so for example, one hour and ten minutes is displayed as “1h 10m”.

```swift
public var units :NSCalendarUnit
```
>The bitmask of calendrical units such as day and month to include in the output string. By default all available values are used; this means each unit of time is part of the output string if the relative value is not zero. You can use:
* `Year`
* `Month`
* `WeekOfMonth`
* `Day`
* `Hour`
* `Minute`
* `Second`
Any other value of the `NSCalendarUnit` enum will result in an exception.

```swift
public var maxUnits :Int = 0
```
>This property can be used to limit the number of units displayed in the resulting string. For example if set to 2, instead of “1h 10m, 30s” the output string will be “1h 10m”. You can use it to provide a round up version of the output when you are constrained.

```swift
public var approximate :Bool = false
```
> Setting the value of this property to `true` adds phrasing to output strings to reflect that the given time value is approximate and not exact. Using this property yields more correct phrasing than simply prepending the string “About” to an output string. By default is set to `false`

```swift
public var approximatePast :Bool = false
```
>Setting this property to `true` results in output strings like “30 minutes remaining”. The default value of this property is `false`.

```swift
public var collapsesLargestUnit :Bool = false
```
>An example of when this property might apply is when expressing 63 seconds worth of time. When this property is set to `true`, the formatted value would be “63s”. When the value of this property is `false`, the formatted value would be “1m 3s”. By default is set to `false`

```swift
public var zeroBehavior :NSDateComponentsFormatterZeroFormattingBehavior = .Default
```
>This specify the behavior of the formatter when it encounter a zero value for a particular unit of time.

**Comment by Hout** [comment]
Should not `weekOfMonth` be `weekOfYear`?
Otherwise we get into trouble when the time interval crosses into another month.

**Comment by malcommac** [comment]
NSDateComponentsFormatter supports only `NSCalendarUnitWeekOfMonth` in  `allowedUnits ` property. In fact  `FormatterStyle` it's just a wrapper around it.
