### ISSUE TITLE
Can you update the docs?

### ISSUE THREAD

**Issue by gloryluu** [malcommac/SwiftDate#138]
Some instruction in doc provided is not right anymore.

**Comment by Hout** [comment]
Correct! We are working on this in the develop branch

Op vr 15 jan. 2016 om 17:41 schreef gloryluu <notifications@github.com>

**Comment by malcommac** [comment]
I'll finish to update the doc today and try to generate an additional doc using jazzy tool.
Moreover I would to compact and merge some files which contains a similar context methods.

**Comment by Hout** [comment]
Fixed in v3.0.0
