### ISSUE TITLE
cached items

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#139]
I noticed the use of cachedFormatter in DateInRegion.

I wondered what the benefits are of the cached formatter as opposed to creating a new formatter and whether this might be over-engineering thus introducing complexity of code?

**Comment by malcommac** [comment]
Initialising an `NSDateFormatter` is a very expensive move. If you have to parse a lot of dates, expect your app to slow down.
This is a known performance issue especially when using in a list of dates; Apple's documentation [here](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW10) say:

>"Creating a date formatter is not a cheap operation. If you are likely to use a formatter frequently, it is typically more efficient to cache a single instance than to create and dispose of multiple instances. One approach is to use a static variable."

There are some other articles you can found by searching on google; [all of them](https://www.google.com/search?client=safari&rls=en&q=NSDateFormatter+expensive+to+create) end with a cached version of the formatter.

However I'm not sure the same the same issue should be applied to `NSDateComponentsFormatter` but right now I've followed the same approach.

**Comment by Hout** [comment]
Clear! Thx.
