### ISSUE TITLE
Format date in local region

### ISSUE THREAD

**Issue by irace** [malcommac/SwiftDate#142]
It seems like local should be the default, is this really the best way to simply format a date for the user’s current region/time zone?

`date.inRegion(Region.LocalRegion()).toMediumString()`

**Comment by Hout** [comment]
The following should produce the same outcome:
```swift
let str = date.toString()
let str = date.inRegion().toString()
let str = date.inRegion(localRegion).toString()
```
Pls try the develop branch. We are working to publish it soon.

**Comment by irace** [comment]
Maybe so but this isn’t the case in the latest tagged CocoaPods build. I don't mean to be snarky but it should be expected that bug reports get filed from release versions, right?

On the release version, I believe `date.inRegion()` uses a default region that is _not_ necessarily the local region, and also the most string formatting methods are on `DateInRegion` but not `NSDate`.

Thanks!

**Comment by Hout** [comment]
Apologies for my ignorance. You are absolutely correct and your remark is appreciated.

It is just that Daniele and myself are putting the final bits together for the v3 release and not with our heads in the current v2 release. That is why I asked you to check the develop branch.

Please hang on. v3 will be out soon.
