### ISSUE TITLE
Jazzy/Dash documentation. Something bad happens

### ISSUE THREAD

**Issue by malcommac** [malcommac/SwiftDate#144]
3.0.0 is now on cocoapods but Dash auto-generated documentation fails.
CocoaPods docs uses jazzy (at least for swift).
Results logs are here:
```
http://api.cocoadocs.org:4567/error/SwiftDate/3.0.0
```
Just tried to generate a doc using Jazzy:
```
/usr/local/bin/jazzy --swift-version 2.1.1 -x '-target,SwiftDate' -o '/Users/danielemm/Desktop/SwiftDate/SwiftDated/JZ' -c --skip-undocumented --author 'Daniele Margutti'
```
but it fails for the same reason.
So I've tried to create a new project, copy SwiftDate core files and..dah dah..it works (we need to make some correction to it, but that's another story).
Never liked the magic behind CocoaPods but it seems to be something related to it.
So my idea is to create a new framework project without using cocoapods to download unit tests (and use it to add carthage targets) and move cocoapods test project in a separate folder.
What do you think @Hout ?

**Comment by Hout** [comment]
We could use Carthage to download Quick and Nimble. That should also work with Travis...
https://github.com/Quick/Quick/blob/master/Documentation/InstallingQuick.md#carthage

**Comment by malcommac** [comment]
Great @Hout. Just made these changes and pushed 3.0.1.
I'll add jazzy documentation sooon. Meanwhile it now works fine with Carthage (I love it!)

**Comment by Hout** [comment]
So Carthage is resolved, how do we progress with Jazzy?

**Comment by malcommac** [comment]
Jazzy is now supported. Configuration was added to project's root directory. First docs [was generated](http://malcommac.github.io/SwiftDate/docs-latest/).
We should make it better but it's a start and it now works.
