### ISSUE TITLE
Carthage fails when building SwiftDate

### ISSUE THREAD

**Issue by iONsky** [malcommac/SwiftDate#145]
I just ran `carthage update` on my project and suddenly carthage fails when building SwiftDate.

Cartfile:
> github "malcommac/SwiftDate"

Output:
> *** Building scheme "SwiftDate" in SwiftDate.xcworkspace
** BUILD FAILED **

> The following build commands failed:
	PhaseScriptExecution Check\ Pods\ Manifest.lock /Users//Library/Developer/Xcode/DerivedData/SwiftDate-fayfyyiikmifsvbdwxifbadfkijw/Build/Intermediates/SwiftDate.build/Release-iphonesimulator/SwiftDate.build/Script-871361268F8CC3B8EB331AF3.sh
(1 failure)
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
A shell task failed with exit code 65:
** BUILD FAILED **

> The following build commands failed:
	PhaseScriptExecution Check\ Pods\ Manifest.lock /Users//Library/Developer/Xcode/DerivedData/SwiftDate-fayfyyiikmifsvbdwxifbadfkijw/Build/Intermediates/SwiftDate.build/Release-iphonesimulator/SwiftDate.build/Script-871361268F8CC3B8EB331AF3.sh
(1 failure)

**Comment by morphinewan** [comment]
me too.

**Comment by SiNBizkit** [comment]
Same problem

**Comment by malcommac** [comment]
Just solved in 3.0.1. Thank you for your report.
If you have problems make sure to remove Carthage folder in your project in order to do a clean fetch/clone/build.
