### ISSUE TITLE
weekdayName isn't public

### ISSUE THREAD

**Issue by mamalat** [malcommac/SwiftDate#147]
weekdayName isn't public.. should it be that way?

**Comment by Hout** [comment]
It should be indeed! And it should be tested also.

**Comment by malcommac** [comment]
Meanwhile I've set as public. We should also write tests for it indeed. (https://github.com/malcommac/SwiftDate/commit/671ec6cb549d3078eb67950c1209de4e32b1f381)

**Comment by AndrewBarba** [comment]
Can you release 3.0.9 to Cocoapods so we can get this change?

**Comment by AndrewBarba** [comment]
Ah, `weekdayName` is missing from `NSDate+SwiftDate.swift`. I think we just need to add:

```
public var weekdayName: Int {
    return self.inRegion().weekdayName
}
```
