### ISSUE TITLE
UTC time

### ISSUE THREAD

**Issue by berlin2** [malcommac/SwiftDate#148]
How do I get current date in UTC timezone and ISO8601 format? Such as: 
print(NSDate().formattedISO8601) // 2016-01-30T22:46:47.914Z

**Comment by Hout** [comment]
That should be:
```swift
let utcRegion = Region(timeZone: Gmt)
let utcString = NSDate().inRegion(utcRegion)..toString(DateFormat.ISO8601)
```
Or with the DateInRegion class:
```swift
let utcRegion = Region(timeZone: Gmt)
let utcDate = DateInRegion(region: utcRegion)
let utcString = utcDate.toString(DateFormat.ISO8601)
```
Does this answer your question?

**Comment by berlin2** [comment]
To make this work I changed your response:
let utcRegion = Region(calendarName: nil, timeZoneName: TimeZoneName.Gmt, localeName: nil)
let utcString = NSDate().inRegion(utcRegion).toString(DateFormat.ISO8601)

This returns a 2016-01-31T12:01:01+0000. I am looking for 2016-01-31T12:01:01.199Z

**Comment by Hout** [comment]
@malcommac can you step in here and do your string magic pls?
This is tested in `RegionStringTests` and confirms @berlin2 's findings:
```swift
               it("should return proper ISO 8601 string") {
                    expect(utcDate.toString(DateFormat.ISO8601)) == "2015-04-13T22:10:00+0000"
                }
```

**Comment by malcommac** [comment]
We could have more different styles for ISO8601 strings; however I think ISO8601 format string is wrong (while the results is in some cases correct).
Currently it is ISO8601 format string is:

```swift
yyyy-MM-dd'T'HH:mm:ssZ // 2015-01-05T22:10:44+0100
```

While according to Apple docs, ISO8601 timezone support should be handled with ZZZ:

```swift
yyyy-MM-dd'T'HH:mm:ssZZZ // 2015-01-05T22:10:44+0100 (here it's the same)
```
If we want to add fractional periods we should add:

```swift
yyyy-MM-dd'T'HH:mm:ss.SSSZ // 2015-01-05T22:10:44.000+0100
```

As with ```ISO8601Formatter``` class we use internally, we should provide different sub-versions.
This is my proposal, currently on a separate feature branch https://github.com/malcommac/SwiftDate/commit/e0e749a6596f4b34b3e871739e2867bfe9bc28f8

I've added new style in DateFormat enum, called ```ISO8601Format``` which takes one parameter of type ```ISO8601Style```:

```swift
public enum ISO8601Style: String {
	case Year							= "yyyy"
	case YearAndMonth					= "yyyy-MM"
	case CompleteDate					= "yyyy-MM-dd"
	case CompleteDateTime				= "yyyy-MM-dd'T'HH:mmZ"
	case CompleteDateTimeSeconds		= "yyyy-MM-dd'T'HH:mm:ssZ"
	case CompleteDateTimeFractional		= "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
}
```

I would tend to avoid removal of ```ISO8601``` and ```ISO8601Date``` DateFormat styles; both of them are the common way in which ISO8601 date is printed.
This is an example about how to format ISO8601 strings:

```swift
let formattedString = date?.toString(.ISO8601Format(.CompleteDateTimeFractional))
```

What do you think @Hout . Any way to make it more readable or compact? Is it okay for you?

**Comment by malcommac** [comment]
Commit https://github.com/malcommac/SwiftDate/commit/74775273174977d3873b8f52e660771b8697ccc5.
DateFormat's IS08601 enum now allows to specify optional ISO8601 variant:

```swift
public enum ISO8601Type: String {
	case Year // yyyy
	case YearMonth // yyyy-MM
	case Date // yyyy-MM-dd
	case DateTime // yyyy-MM-dd'T'HH:mmZ
	case Full	// yyyy-MM-dd'T'HH:mm:ssZ
	case Extended // yyyy-MM-dd'T'HH:mm:ss.SSSZ
}
```
When omitted ```.Full``` is used.

Usage example:
```swift
let iso8601_str = date.toString(.ISO8601())
let iso8601_str = date.toString(.ISO8601(.Extended))
```
