### ISSUE TITLE
Missing "toISO8601String" methods in NSDate

### ISSUE THREAD

**Issue by TadeasKriz** [malcommac/SwiftDate#149]
[Documentation](https://github.com/malcommac/SwiftDate/blob/master/Documentation/UserGuide.md#from-dateinregionnsdate-to-strings) says that the method should be available in both DateInRegion and NSDate, but I could not find it. Is it a bug in documentation or a missing method? Thanks.

**Comment by Hout** [comment]
Thanks for the issue. 

`.toISO8601String` is replaced by `.toString(DateFormat.ISO8601)`

Unfortunately the string functions have not been fully documented yet and should be added to the upgrade guide. Apologies for the time wasted, but Daniele and I decided to publish the v3 library before fully completing the docs as v2 urgently needed an upgrade.

This should work for both:
```swift
let dateStr1 = DateInRegion().toString(format: DateFormat.ISO8601)
let dateStr2 = NSDate().toString(format: DateFormat.ISO8601) 
```

Please let us know whether or not this works for you.

**Comment by TadeasKriz** [comment]
That works well, thanks!
