### ISSUE TITLE
toRelativeString error on Phone

### ISSUE THREAD

**Issue by iantheparker** [malcommac/SwiftDate#15]
Hello there,

This code seems to work fine on the simulator, but on my phone I get an error
`
cell.ageLabel.text = object.published_at.toRelativeString(fromDate: NSDate(), abbreviated: true, maxUnits: 1)
`
`
println("object published \(object.published_at) age label \(cell.ageLabel.text) and date \(NSDate())")
`

outputs on phone
`
object published 2015-06-11 15:34:56 +0000 age label Optional("9.223372e+18w") and date 2015-06-13 22:29:15 +0000
`

outputs on simulator
`
object published 2015-06-11 15:34:56 +0000 age label Optional("2 days ago") and date 2015-06-13 22:41:17 +0000
`

Any tips?

**Comment by codegiant** [comment]
Having the same issue. The "toRelativeString" method works fine on the simulator but fails on my actual device. (iPhone 6, iOS 8)

Instead of the nicely formatted "1h" or "37s", I get back what looks like scientific notation. "9.223372+18w"

**Comment by malcommac** [comment]
Thank you for your report. Seems to be an issue related to deprecated 'week' property of the NSDateComponent class. I've just made a commit here and tested with iOS 8.3 63bffa881c6c1520522d89209156a100603ea0ec. Can you make another check with your device?

**Comment by codegiant** [comment]
You bet. Tested the latest commit on my device and it's working perfectly. 

Nailed it!

**Comment by malcommac** [comment]
Great :) Again, thank you for your bug report

**Comment by iantheparker** [comment]
Great! Thank you!
