### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by FrancoisMartin** [malcommac/SwiftDate#150]
Hello,

How can we translate relative strings ? (eg : "2 minutes ago")

From the documentation (https://github.com/malcommac/SwiftDate/blob/master/Documentation/UserGuide.md#from-dateinregionnsdate-to-relative-strings), i can see that we need to add `SwiftDate.localizable`, someone has more informations about this ?

I see no pull request concerning localisation.

Thank you.

**Comment by Hout** [comment]
Francois, merci a votre issue.
The documentation is outdated; relative strings are already localized.
Search for the `toNaturalString` function.

Does that help?

**Comment by FrancoisMartin** [comment]
Thank you ! That helps me a lot.

Can you give me more information or an example to use the "inRegion" and "style" parameters ?
`item.date.toNaturalString(NSDate(), inRegion: ?, style: ?)`

**Comment by Hout** [comment]
The only reason for using `inRegion` is if you want to get the string from the date in a different time zone, calendar or locale. For your default region you should not use `inRegion`.
As for the `style` parameter I would suggest to just try it out with various options and see what satisfies your requirements. 
For possible values check this [link](https://developer.apple.com/library/prerelease/mac/documentation/Foundation/Reference/NSDateComponentsFormatter_class/#//apple_ref/c/tdef/NSDateComponentsFormatterUnitsStyle)

**Comment by gloryluu** [comment]
Could you update the library? I get some of confusion of this natural after updating to 3.0.2

**Comment by Hout** [comment]
@malcommac Shall I promote develop into master v3.1.0?

**Comment by malcommac** [comment]
Mmmm what's about 3.0.4? I'll reserve 3.10 when relative date formatting will be done, do you agree?

**Comment by Hout** [comment]
3.0.4 it will be. I finished most of the swiftlint and got some bugs out of the code by doing so.
Release tonight!
