### ISSUE TITLE
StartOf Week

### ISSUE THREAD

**Issue by Morbix** [malcommac/SwiftDate#153]
I can't find the startOf the week, because the code below is returning always the startOf the current day:

```swift
NSDate().startOf(.Weekday, inRegion: .defaultRegion())
```

**Comment by Hout** [comment]
That is the correct behaviour.
To get the start of the week you should use:
```
let date = xyz
let startOfWeek = date.startOf(.WeekOfYear)
```

**Comment by Morbix** [comment]
@Hout I am trying to get the NSDate equivalent of the firstWeekDay. Do you know how can i do this?

**Comment by Hout** [comment]
@Morbix that is what I intended to answer in my previous reaction. Can you elaborate on your issue please as I wonder how you cannot get the first day of the week by using the code above?

**Comment by Morbix** [comment]
I am really sorry @Hout . I didn't even tried to run your code. It worked perfectly. 

Just the name "weekOfYear" is a little bit confuse, because suppose that is going to return the first week of the year (like New Year's week). This was the reason that I, unfortunately, didn't tried to run.

But wherever, it is returning what I am needing.

**Comment by Hout** [comment]
No problem! If you want to know the rationale behind the apparently confusing name then check out the Apple documentation on `weekOfYear`, `weekOfMonth` and `yearForWeekOfYear`.

**Comment by filipejtdias** [comment]
Just an update to Swift 3

let date = xyz
let startOfWeek = date.startOf(component: .weekOfYear)

;)
