### ISSUE TITLE
"toString" format not working properly with 12 hour clock

### ISSUE THREAD

**Issue by TadeasKriz** [malcommac/SwiftDate#155]
I have a date `2016-02-06 18:39:00 UTC` (in variable `date`). When I do `date.inRegion().toISO8601String()`, I get the correct output: `2016-02-06T18:39:00.000Z`. But when I do simply: `date.toString(.ISO8601)`, what I get is something unexpected and possibly a wrong value: `2016-02-06T7:39:00+0100`. Am I using it wrongly or is it a bug? Thanks.

**Comment by Hout** [comment]
Good find!
NSDate and DateInRegion should behave the same in the default region. Hence this is a bug.

**Comment by netgfx** [comment]
```
let d = data.toDate(DateFormat.Custom("MM/dd/yyyy")) // "2016-02-02 18:00:29" 
```
this syntax returns nil

Is this the same bug or related?

**Comment by malcommac** [comment]
You have provided the wrong format according to your date string in the comment.

**Comment by netgfx** [comment]
So to get this straight, the DateFormat should match the date string provided?

I thought it was the format based on which the Date is returned.
So how can I know which dateformat to use?

**Comment by Hout** [comment]
The `toDate` function needs a lead to know which characters in the string represent which data. Different countries and different programmers use different date formats. E.g. "11-12-13"  could mean 11 December 2013, 13 December 2011 or 12 November 2013...

**Comment by Hout** [comment]
@netgfx coming back to your question: you must know the date format of the string you provide before passing it on. How you obtain that is your challenge.

**Comment by netgfx** [comment]
Yes I understand now and I was able to convert the given date to a custom formatted one.
Thanks for clarifying things.

**Comment by Hout** [comment]
Woops reopened since the original bug with ISO8601 date formatting in the default region is still prevailing.

**Comment by malcommac** [comment]
I think we should reuse same function to express same features. In this way ```toISO8601String()``` is simply a shortcut for ```toString(.ISO8601)```.
So this commit (now in a separate feature) will accomplish this task: https://github.com/malcommac/SwiftDate/commit/165309fd926fac2574902025bd81343f846574b9.
Any cons?

**Comment by Hout** [comment]
I think we should consolidate to a minimum number of functions that describe the function of the function. In this case I would vote for the `toString(style)` format and deprecate the `toStyleString()`  format. The former is more flexible.

**Comment by malcommac** [comment]
Totally agree. It now uses toString(.ISO8601) format but it's marked as deprecated. https://github.com/malcommac/SwiftDate/commit/9451ed3fcf3ba996a347ea96ce45694371aa4f3a
