### ISSUE TITLE
Downgrade OSX Version?

### ISSUE THREAD

**Issue by JeanAzzopardi** [malcommac/SwiftDate#156]
Hi, 

Would it be possible to downgrade the supported version of OSX to, say OSX 10.10 or 10.9 to support machines which haven't yet upgraded to El Capitan?

**Comment by JeanAzzopardi** [comment]
Bump - I'm interested in this primarily as I'm using it on a project where the OSX version is unlikely to be El Capitan, most likely Yosemite. As is, there are no purely El Capitan specific features that are used.

**Comment by malcommac** [comment]
Yeah ok, can you make a new PR which also modify .podspecs for CocoaPods (your change cover only Carthage right?)

**Comment by JeanAzzopardi** [comment]
I think it's already in the .podspec actually: https://github.com/malcommac/SwiftDate/blob/master/SwiftDate.podspec

```MACOSX_DEPLOYMENT_TARGET = 10.10```

**Comment by malcommac** [comment]
Done in develop. Thanks
