### ISSUE TITLE
SwiftDate 在真机环境中使用会返回nil，但模拟器不会什么原因？

### ISSUE THREAD

**Issue by lxkbest** [malcommac/SwiftDate#158]
调用
var createTime: String? {
        didSet {
               createTimeDate = createTime?.toDate(.Custom("MMM dd, yyyy KK:mm:ss aa"))
             }
      # }
    
真机环境createTimeDate得到nil
模拟器环境createTimeDate得到UTC时间 

究竟什么原因

**Comment by malcommac** [comment]
Ehm :-) Can you post in english?

**Comment by lxkbest** [comment]
Real machine environment createTimeDate is nil  
The simulator createTimeDate is not nil
What's the cause of the

**Comment by malcommac** [comment]
Maybe a different locale between simulator and real device?
Can you post your configuration (locale) on both devices and your source string to parse?

**Comment by lxkbest** [comment]
this source string ： Feb 12, 2016 5:06:06 PM

**Comment by lxkbest** [comment]
Chinese：
最后 我查看你的源代码，做了以下调整。在 DateInRegion.Swift中的初始化方法里的case .Custom 中添加
cFormatter.locale = NSLocale(localeIdentifier: "en_US")
 
English：
Finally I see your source code, do the following adjustments.  DateInRegion.Swift
cFormatter.locale = NSLocale(localeIdentifier: "en_US")

.Custom case (dateFormat let):
       cFormatter.dateFormat = dateFormat
       cFormatter.locale = NSLocale(localeIdentifier: "en_US")
       ParsedDate = cFormatter.dateFromString (date)
}

**Comment by lxkbest** [comment]
hi man  thank you

**Comment by malcommac** [comment]
In order to parse your string you need provide the right format.
For you source string you can accomplish it using "MMM dd, yyyy K:mm:ss a" (see http://waracle.net/iphone-nsdateformatter-date-formatting-table/):

```swift
let str = "Feb 12, 2016 5:06:06 PM"
let region = Region(calendarName: CalendarName.Gregorian, timeZoneName: TimeZoneName.Gmt, localeName: LocaleName.EnglishUnitedStates)
let dateObj = DateInRegion(fromString: str, format: DateFormat.Custom("MMM dd, yyyy K:mm:ss a"), region: re)
```
