### ISSUE TITLE
NSDate initializer buggy

### ISSUE THREAD

**Issue by twiedow** [malcommac/SwiftDate#161]
There is this NSDate init which takes date components to init a date:

    public convenience init(refDate date : NSDate,
        era						: Int? = nil,
        year					: Int? = nil,
        month					: Int? = nil,
        day						: Int? = nil,
...

Unfortunately the month component is not set correctly. It does not use the provided month integer but the weekOfYear attribute to set the month component:

            newComponents.month = weekOfYear ?? date.weekOfYear ?? 1

I think this is a bug.

**Comment by twiedow** [comment]
I just opened a pull request for this issue (Fix month component initialization #162).

**Comment by malcommac** [comment]
Thank you @twiedow; I've refused pr to add your change in develop instead of master.
