### ISSUE TITLE
Remove component dictionaries

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#163]
Creation from component dictionaries seems superfluous. Dates can be created with optional parameters alike a date component dictionary:
```
let date1 = NSDate(year: 2016, month: 2, day: 21)
let date2 = NSDate(dateComponentDictionary: [year: 2016, month: 2, day: 21)])
```
The latter seems equally functional but with more clutter...
Unless this has a broader rationale than flexibility in creation of dates, I propose to get rid of this construction.

**Comment by malcommac** [comment]
I agree, we could mark it as deprecated

**Comment by Hout** [comment]
That will be for 3.0.5 then.
