### ISSUE TITLE
Mixing relative and non-relative format for different time components

### ISSUE THREAD

**Issue by deville** [malcommac/SwiftDate#164]
I need dates formatted the following way:
"yesterday 3:25 AM"
"today 4:00 PM"
"tomorrow 10:00 PM"
"3 days ago 10:00 PM"

I am not sure this is possible with SwiftDate 3.0.2 I am using (though I must admit I might not have understood something, there seem to be so many parameters). Here is what I tried:

![screen shot 2016-02-22 at 10 40 00](https://cloud.githubusercontent.com/assets/4421971/13214556/ab756d6a-d950-11e5-973e-28428f40c1f9.png)

`date.toString(.ShortStyle, relative: true)` is the closest to what I need, but not quite it. I need more control over the resulting string. For instance, I would like to be able to control capitalization, or get rid of comma, or output "yest" instead of "yesterday".

Deprecation note for `toRelativeString()` method says I should "Use toNaturalString() with relative parameters". However, I can't seem to figure out how to do this. `FormatterStyle` struct, which is supposed to be used for configuration, does not expose any parameters to configure relative formatting.

Also, there is Issue #79, `toComponentsStrings` might be of help, but it is not included in 3.0.2.

**Comment by malcommac** [comment]
I'm working on a new implementation. I'll post more infos during this week.

**Comment by Hout** [comment]
Do you have any specs yet so I can write the test code?

**Comment by malcommac** [comment]
Yup I'll post specs before weekend (hope later today)

**Comment by malcommac** [comment]
I'll close this. Now we have an initial implementation; we can continue here: #168
