### ISSUE TITLE
Fix Travis

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#166]
Apparently Travis is not connected anymore?

**Comment by Hout** [comment]
This works now

**Comment by Hout** [comment]
@malcommac would you mind to register SwiftDate with Travis CI again?

**Comment by malcommac** [comment]
Ehm I didn't know Travis. What should I do? :)

**Comment by Hout** [comment]
Ow... :smile: Sowwy!
Just login to [travis](https://travis-ci.org/) with your github account and submit the SwiftDate repository.
That justifies this badge in the README.md:
 [![CI Status](https://travis-ci.org/malcommac/SwiftDate.svg)](https://travis-ci.org/malcommac/SwiftDate)
