### ISSUE TITLE
Can't use Carthage & Cocoapods anymore (3.0.5)

### ISSUE THREAD

**Issue by alpennec** [malcommac/SwiftDate#167]
When using Carthage, I have this error

`A shell task failed with exit code 74:
xcodebuild: error: Unable to read project 'Nimble.xcodeproj' from folder '/Users/Axel/Developer/Hivy/Carthage/Checkouts/SwiftDate/XCode/Carthage/Checkouts/Nimble'.
	Reason: Project /Users/Axel/Developer/Hivy/Carthage/Checkouts/SwiftDate/XCode/Carthage/Checkouts/Nimble/Nimble.xcodeproj cannot be opened because it is missing its project.pbxproj file.`

**Comment by Hout** [comment]
Woops! And Cocoapods too.
Working on this now.

**Comment by Hout** [comment]
This works now

**Comment by Hout** [comment]
@malcommac would you mind to trunk this version with CocoaPods pls?

**Comment by malcommac** [comment]
Pushed!
