### ISSUE TITLE
DateFormatter: dealing with time interval formatting in SwiftDate

### ISSUE THREAD

**Issue by malcommac** [malcommac/SwiftDate#168]
Recently there was a discussion about the opportunity to use `NSDateComponentsFormatter` class in order to provide a string representation (both colloquial and by time unit components) of the interval between two dates.
You can learn more about it starting [here](https://github.com/algal/RelativeDatePlayground).

In the meantime we belive it's good to provide an similar alternative; this is what we are doing in [`TimeIntervalFormatter`](https://github.com/malcommac/SwiftDate/tree/feature/TimeIntervalFormatter) gitflow feature of the develop branch (planned to go live for 3.1 release).
The main class is called `DateFormatter` ([link to commit](https://github.com/malcommac/SwiftDate/blob/feature/TimeIntervalFormatter/SwiftDate_src/DateFormatter.swift)) and allows you to print date interval in 5 different styles:

**TIME INTERVAL COMPONENTS STYLES**

- `Positional` (A style that uses the position of a unit to identify its value and commonly used for time values where components are separated by colons . `"1:10:00"`)
- `Abbreviated` (The abbreviated style represents the shortest spelling for unit values.` "1h 10m"`)
- `Short` (A style that uses the short spelling for units.` “1hr 10min”`)
- `Full` (A style that spells out the units fully. `“1 hour, 10 minutes”`)
- `Colloquial` (For some relevant intervals this style print out a more colloquial string representation (`"last month", "on 2016", "next year", "in 5 minutes", "just now"` and so on).

**DateFormatter CLASS**
DateFormatter  class allows you to specify several attributes used to customise the output string:

- `unitsStyle` allows you to specify the string length used to print each time component (described above)
- `allowedUnits` specify what kind of time units (`seconds,hours,minutes`...) maybe part of the output stirng (some units maybe dropped if zero, depending of `zeroBehaviour` parameter).
- `maxUnitCount` if not nil specify the max number of time components used to compose the output string (from the high ordered time unit - year - to the smallest one, second). This value is not used for .Colloquial style.
- `zeroBehavior` specify how to threat time units with zero values (should be included in the output string? how?). Possible values are `.None` (None, it does not remove components with zero values), `.DropLeading` (Units whose values are 0 are dropped starting at the beginning of the sequence until the first non-zero component), `.DropMiddle` ( Units whose values are 0 are dropped from anywhere in the middle of a sequence.), `.DropTrailing` (Units whose value is 0 are dropped starting at the end of the sequence back to the first non-zero component) and `.DropAll`. This param is not used for `.Colloquial` style.
- `includeRelevantTime` this parameter is valid only for `.Colloquial` style. If specified for each interval of time (in years, in hours, in seconds...) a relevant time string will be added at the end of the output. For example for colloquial representation `"in 2 hours"` the final string maybe `"in 2 hours (at 21:30)"`.
- `allowsNowOnColloquial` this paramter is valid only for `.Colloquial` style. If specified for a time interval < 5 minutes the output will be "just now"

Public methods of the class are:
- `public func toString(interval: NSTimeInterval) -> String?`
- `public func toString(fromDate f: DateInRegion, toDate t: DateInRegion) -> String?`

**.strings FILE SPECS**
The localized strings (at this time only en was created) are contained inside SwiftDate.bundle bundle.
The file itself is documented, but basically it contains:

- unit names strings (`unitname_`): how to spell years/minutes/seconds... in .Positional,.Short... styles)
- colloquial strings (`colloquial_`): representation of the colloquial strings for each relevant amount of time
- relevant time strings (`relevanttime_`): specify the date string format to add for each relevant variant
- value separator (`valuesep_`): specify the separator string between each time unit in each style
- unit separator (`unitsep_`) specify the separator string between each time unit component

[Codes for languages](http://stackoverflow.com/questions/3040677/locale-codes-for-iphone-lproj-folders).

**COLLOQUIAL REPRESENTATION TABLE**

This is the logic used when you want to print a colloquial representation of the differences between two dates.

| TIME DIFFERENCE | FUTURE        | PAST           | RELEVANT TIME     |
|-----------------|---------------|----------------|-------------------|
| = 1 year        | next year     | last year      | (Feb 2016)        |
| > 1 year        | on 2016       | 2016           | (Feb 2016)        |
| = 1 month       | next month    | past month     | (Feb 17, 2016)    |
| > 1 month       | in 3 months   | 3 months ago   | (Feb 17, 2016)    |
| = 1 week        | next week     | past week      | Wed, Feb 17 2016) |
| > 1 week        | in 3 weeks    | 3 weeks ago    | Wed, Feb 17 2016) |
| = 1 day         | tomorrow      | yesterday      | Wed, Feb 17 2016) |
| > 1 day         | in 2 days     | 2 days ago     | Wed, Feb 17 2016) |
| = 1 hour        | in one hour   | one hour ago   | (at 13:20)        |
| > 1 hour        | in 3 hours    | 3 hours ago    | (at 13:20)        |
| = 1 minute      | in one minute | one minute ago | none              |
| > 1 minute      | in 3 minutes  | 3 minutes ago  | none              |
| < 5 minutes     | just now      | just now       | none              |
| = 1 second      | in one second | one second ago | none              |
| > 1 second      | in 3 seconds  | 3 seconds ago  | none              |

I would also add special today time ranges:
- today between `00:00 -> 06:00` -> _this night_ (relevant time is the hour `'HH:mm'`)
- today between `06:00 -> 12:00` -> _this morning_ (relevant time is the hour `'HH:mm'`)
- today between `12:00 -> 18:00` -> _this afternoon_ (relevant time is the hour `'HH:mm'`)
- today between `18:00 -> 24:00` -> _this evening_ (relevant time is the hour `'HH:mm'`)

I'll add it very soon but it should be enough to start first tests.
cc @Hout

**Comment by Hout** [comment]
Nice job! :-)

Remarks:
- please mention the source date (17-Feb-16) for the examples in the table.
- I am not sure about the unit granularity. Depending on circumstances I would mention "February next year"  or just "next year". Or "tomorrow at 20h15".
- Weeks are not in the allowed units set?
- Difference between day parts (morning afternoon, night) differs per locale. E.g. in Indonesia day parts exist for sunrise-11 (pagi), 11-14 (siang), sore (14-sunset), malam (night).

Dutch strings on their way

**Comment by Hout** [comment]
This is complicated matter. In The Netherlands, days are indicated as (English equivalents):
- the day after tomorrow ("overmorgen")
- the day before yesterday ("eergisteren")
- day name if within the week or closest weekend
- "next week" day name if in next week e.g. "Friday next week" --> "volgende week vrijdag"
- "last week" day name if in last week e.g. "Friday last week" --> "vorige week vrijdag"
- OR: "Last Friday"

Of course we want to keep things as simple as possible.

**Comment by Hout** [comment]
Also: 
- colloquial_f_s is never used in practice. "Now" is appropriate.
- colloquial_thisnight is different for future and past, also in English: "last night", if it is the previous night, "tonight" if it is the next night (and night is including the evening in the UK), "this night" if from within the "night" time frame.

**Comment by malcommac** [comment]
> Difference between day parts (morning afternoon, night) differs per locale. E.g. in Indonesia day parts exist for sunrise-11 (pagi), 11-14 (siang), sore (14-sunset), malam (night).

Okay good to know, so there is no reason to increase complexity. So, first of all we can drop "today's" variants because they are too locale dependant.

> I am not sure about the unit granularity. Depending on circumstances I would mention "February next year" or just "next year". Or "tomorrow at 20h15".

Can you explain cricumstances? We could provide variants of relevant time strings for each unit if needed.

> Weeks are not in the allowed units set?

weeks are available with "_w_" and "_ww_" code

> colloquial_f_s is never used in practice. "Now" is appropriate.

Basically I agree but it's a param and by removing it we lose unit granularity (seconds) you can omit with using allowsNowOnColloquial = true. Is it a good idea?

> colloquial_thisnight is different for future and past, also in English: "last night", if it is the previous night, "tonight" if it is the next night (and night is including the evening in the UK), "this night" if from within the "night" time frame.

We will remove it according to the first point, okay? any better idea?

**Comment by Hout** [comment]
> Okay good to know, so there is no reason to increase complexity. So, first of all we can drop "today's" variants because they are too locale dependant.

Agreed

> Can you explain cricumstances? We could provide variants of relevant time strings for each unit if needed.

Maybe we should include the number of units? E.g. next year can be "next year" (1 unit) "February next year" (2 units), 27 February next year (3 units) etc.

> weeks are available with "w" and "ww" code

Because of this code in DateFormatter?
```
    /// Tell what kind of time units should be part of the output. Allowed values are a subset of
    /// the NSCalendarUnit mask
    /// .Year, .Month, .Day, .Hour, .Minute, .Second are supported (default values enable all of
    /// them)
    public var allowedUnits: NSCalendarUnit = [.Year, .Month, .Day, .Hour, .Minute, .Second]
```

> Basically I agree but it's a param and by removing it we lose unit granularity (seconds) you can omit with using allowsNowOnColloquial = true. Is it a good idea?

Yep agreed but also depending on circumstances. What about a time interval that can be specified for using "now"? With a default on 29 seconds?

> We will remove it according to the first point, okay? any better idea?

Ok, but remember it for later. It might be easy to add after all. Let us take small steps.

**Comment by Hout** [comment]
For investigation: maybe we can retrieve some of the strings from `NSDateFormatter`?

**Comment by Hout** [comment]
E.g. put this in a playground:

let f = NSDateComponentsFormatter()
let units: NSCalendarUnit = [.Day]
f.allowedUnits = units
f.unitsStyle = .Full
let components = NSDateComponents()
```
components.day = -1
print(f.stringFromDateComponents(components))
components.day = 1
print(f.stringFromDateComponents(components))
components.day = 2
print(f.stringFromDateComponents(components))
```

**Comment by malcommac** [comment]
Yeah, this was my first choice but I've discarded that because it fill only partially our strings needs (colloquial forms still missing, we can have only unit names). So, at least for now, I'll tend to avoid using it because it does not solve the entire problem but create an useless dependency for a fistful of strings. What do you think?

**Comment by Hout** [comment]
Maybe it is a good fallback for those locales that we do not have all strings for?

**Comment by malcommac** [comment]
We can use NSDateFormatterStyle for time and date to add relevant time information to the colloquial version of the string. What do you think? It should be easier than maxUnits

**Comment by malcommac** [comment]
I've tried with NSDateFormatterStyle but I think it's not the best choice because it's a bit constrained.
You can't obviously decide what format of date/time print so for example you can't print Feb 17 or Wen Feb 17 etc.
A manual pick with a specified date format seems the best reasonable way and it should be customized based upon locale habits.

**Comment by Hout** [comment]
I made a typo; the strings should be obtained from `NSDateComponentFormatter`not `NSDateFormatter`(tongue in cheeck) sorry.

**Comment by malcommac** [comment]
Okay I've moved components based print of DateFormatter to `NSDateComponentFormatternot` since commit https://github.com/malcommac/SwiftDate/commit/00dd0eae3d6aec7542417d4e436fa5ee60606884

**Comment by malcommac** [comment]
Less than 1 minute differences are now simply "just now" as you said some time ago :)
