### ISSUE TITLE
Minimum deployment targets for frameworks

### ISSUE THREAD

**Issue by malcommac** [malcommac/SwiftDate#169]
@Hout, I've noticed that with the new project which build frameworks have now these min deployment target:
- iOS: 9.3
- OSX: 10.11
- WatchOS: 2.2
- TvOS: 9.2

I think we can set iOS to 8.0, OSX to 10.10, WatchOS 2.0 and TvOS 9.0.
What do you think?

**Comment by Hout** [comment]
Absolutely! Publish tomorrow.

**Comment by Hout** [comment]
Done
