### ISSUE TITLE
Xcode 6.3.2 returns nil

### ISSUE THREAD

**Issue by ageorgios** [malcommac/SwiftDate#17]
let date = "Fri, 09 Sep 2011 15:26:08 +0200".toDate(format: DateFormat.RSS)
returns nil

**Comment by ageorgios** [comment]
It only works when in english

**Comment by malcommac** [comment]
Mhhh, sorry I can't understand. Your test example is in english, and it uses the default date formatter so should work even with other langs. Can you provide more infos? thx

**Comment by ageorgios** [comment]
When the iOS Simulator language is changed to Greek for example, it returns nil.
