### ISSUE TITLE
Documents need to update

### ISSUE THREAD

**Issue by WyattZhang** [malcommac/SwiftDate#172]
Some of the init methods does't work, maybe deprecated and the documents need to update.
thx!

let newYork = DateRegion(timeZoneID: "EST")

// Create a date for XMas Day at midnight in New York
let date1 = NSDate(year: 2015, month: 12, day: 25, region: newYork)
let date2 = NSDate(year: 2015, month: 12, day: 25, timeZoneID: "EST")
Create a DateInRegion object

Creation of DateInRegion objects is equivalent to that of NSDate objects:

// Create a local date for XMas Day at midnight
let date1 = `DateInRegion`(year: 2015, month: 12, day: 25)

let date3 = DateInRegion(yearForWeekOfYear: 2016, weekOfYear: 1, weekday: 1, region: rome)
let date4 = DateInRegion(yearForWeekOfYear: 2016, weekOfYear: 1, weekday: 1, timeZone: TimeZoneNames.Europe.Rome, localeID: "it_IT")
let date5 = DateInRegion(yearForWeekOfYear: 2016, weekOfYear: 1, weekday: 1, timeZoneID: "CET", localeID: "it_IT")

// Create date from an `NSDate`
let date6 = nsdateObject.inRegion(rome)

**Comment by Hout** [comment]
This works for me. What is the issue exactly with the inits? 
And what documentation are you refering to?

**Comment by Hout** [comment]
No response, case closed. May be reopened when sufficient information is provided.
