### ISSUE TITLE
toNaturalString & maxUnits = 1 sometimes shows 2 units 

### ISSUE THREAD

**Issue by owenbirdsall** [malcommac/SwiftDate#174]
When the difference is 8 days,  it will show "1 week, 1 day" instead of "1 week" or "8 days"

**Comment by malcommac** [comment]
Number of days in a weeks are obtained from calendar's locale; in your case the value obtained is 7 days so you have one week plus one day. That's right.
What's your locale? Can you print it?

**Comment by owenbirdsall** [comment]
Yes, it should be one week plus one day, but I thought that setting maxUnits to one would restrict the result to be a single value - either 1 week or 8 days... or have I misunderstood this functionality?

My region settings are: gregorian; Europe/London:GMT; en_US

**Comment by malcommac** [comment]
toNaturalString now uses NSDateComponentsFormatter but it will be replaced soon as the new formatter functions will come to a stable release. More info about that are available at this thread: https://github.com/malcommac/SwiftDate/issues/168.
You can contribuite with your opinion; we will discuss them. At this time maxUnits only specify the non-zero unit style you want to show in the output string.
