### ISSUE TITLE
Initialize region with NSTimeZone is internal

### ISSUE THREAD

**Issue by TadeasKriz** [malcommac/SwiftDate#176]
A while ago I was able to initialize the `Region` with the instance of `NSTimeZone`, but now it's internal and cannot be used. Is this intentional? What is a correct way to do it now?

**Comment by malcommac** [comment]
We would to keep the library consistent so the main way to pass a timezone is to specify it's by TimeZoneName (ie. TimeZoneName.AfricaBamako).
Do you need to pass directly an NSTimeZone instance?

**Comment by TadeasKriz** [comment]
Yes, because the only thing I have is an offset in seconds from GMT and I need to use it as a timezone.

**Comment by malcommac** [comment]
Seems reasonable.
https://github.com/malcommac/SwiftDate/commit/befb264587247574b8f350412b363286a6bfce61
