### ISSUE TITLE
1.years - 2.hours

### ISSUE THREAD

**Issue by StrelnikovEugene** [malcommac/SwiftDate#180]
let date5 = (1.years - 2.hours).fromNow()
let date6 = (1.years + 2.hours).fromNow()

date5	NSDate	2015-03-13 01:48:29 UTC
date6	NSDate	2017-03-13 05:48:29 UTC

**Comment by malcommac** [comment]
Cannot reproduce this bug.
That's the result of my test:

```swift
let date = NSDate() // 2016-03-14 19:30:38 +0000 (UTC)
let date5 = (1.years - 2.hours).fromNow() // 2017-03-14 17:30:38 +0000
let date6 = (1.years + 2.hours).fromNow() // 2017-03-14 21:30:38 +0000
```

What's your UTC offset/timezone?

**Comment by malcommac** [comment]
closed for now, waiting for more info.
