### ISSUE TITLE
Adding firstDayOfWeek/lastDayOfWeek property both for DateInRegion and Date

### ISSUE THREAD

**Issue by bb-git** [malcommac/SwiftDate#187]
The function of the documentation is not returning an NSDate, as it should.

**Comment by Hout** [comment]
Stale docs. Needs an update.

Workaround: use `startOf` function.
```
let date = NSDate(blahblah) // initialise as desired
let firstDayOfWeek = date.startOf(.WeekOfYear)
```
Please let me know if this works for you.

**Comment by malcommac** [comment]
Added `.startWeek` and `.endWeek` properties both for `Date` and `DateInRegion`.
(https://github.com/malcommac/SwiftDate/commit/a38152e5efd40378c0ddb0cba0872ce82ceab9df)
