### ISSUE TITLE
ISO8601Date deprecated message is not correct

### ISSUE THREAD

**Issue by redent** [malcommac/SwiftDate#193]
`DateFormat.ISO8601Date` deprecated message is not correct. It reads `Use ISO8601(.Date)` where it should be `Use ISO8601Format(.Date)` as the first one doesn't even compile.

**Comment by redent** [comment]
I'm referring to [this line of code](https://github.com/malcommac/SwiftDate/blob/f492c98bfb25e3fc99b08673541ca3c643887a03/Sources/SwiftDate/NSDateFormatter%2BSwiftDate.swift#L101).

**Comment by Hout** [comment]
Resolved in develop branch. Thanks for the find!
