### ISSUE TITLE
String.ISO8601Formatter should be public

### ISSUE THREAD

**Issue by redent** [malcommac/SwiftDate#194]
The [`String.ISO8601Formatter`](https://github.com/malcommac/SwiftDate/blob/master/Sources/SwiftDate/NSDateFormatter%2BSwiftDate.swift#L168) should be `public` in order to be used from the application. It's not used or referenced from anywhere else, so it's practically inaccessible if declared `internal`.

Additionally, it should return `ISO8601Type` instead of the format string to avoid duplicated format declarations and to be usable as `DateFormat.ISO8601Format` parameter. I'm not sure if keeping it `static` or even as a `String` extension make any sense either.

To sum up, I would replace it with this:

```
static func ISO8601Formatter(fromString string: String) -> ISO8601Type {
    
    var dateFormatter = ISO8601Type.Full
    
    if let dateStringCount = IS08601Format(rawValue: string.characters.count) {
        switch dateStringCount {
        case .Year:
            dateFormatter = ISO8601Type.Year
        case .YearAndMonth:
            dateFormatter = ISO8601Type.YearMonth
        case .CompleteDate:
            dateFormatter = ISO8601Type.Date
        case .CompleteDatePlusHoursAndMinutes, .CompleteDatePlusHoursAndMinutesAndZ:
            dateFormatter = ISO8601Type.DateTime
        case .CompleteDatePlusHoursMinutesAndSeconds, .CompleteDatePlusHoursAndMinutesAndSecondsAndZ:
            dateFormatter = ISO8601Type.Full
        case .CompleteDatePlusHoursMinutesSecondsAndDecimalFractionOfSecond, .CompleteDatePlusHoursMinutesSecondsAndDecimalFractionOfSecondAndZ:
            dateFormatter = ISO8601Type.Extended
        }
    }
    return dateFormatter
}
```

Then, it could be used like this:

```
text.toDate(DateFormat.ISO8601Format(String.ISO8601Formatter(fromString: text)))
```

And it shouldn't break backward compatibility because it's declared as internal and not used anywhere.

A convenience method for this would be appreciated too, so I would also replace the current version of [`toDateFromISO8601`](https://github.com/malcommac/SwiftDate/blob/f492c98bfb25e3fc99b08673541ca3c643887a03/Sources/SwiftDate/DateInRegion%2BFormatter.swift#L301), that currently only parses `.Full` format to this:

```
public func toDateFromISO8601() -> NSDate? {
    return toDate(DateFormat.ISO8601Format(String.ISO8601Formatter(fromString: self)))
}
```

This change shouldn't break compatibility as it will continue to parse ISO8601 `.Full` dates, but it will also parse any other compatible format.

**Comment by redent** [comment]
Minor update: the solution proposed above doesn't process `2015-11-26T14:21:10.000+01:00` as `.Extended` as it has 29 characters and it doesn't match any declared `ISO8601Format` enum.

**Comment by Hout** [comment]
Thanks for your report!

**Comment by malcommac** [comment]
```ISO8601DateTimeFormatter``` is now public and port lots of the features that ```ISO8601Formatter``` implements in iOS10+
