### ISSUE TITLE
Dates get truncated inappropriately

### ISSUE THREAD

**Issue by marchy** [malcommac/SwiftDate#196]
Why does the library truncate dates? This is causing problems comparing timestamps we have that get generated in our back-end:

```
ie: "2016-04-22T13:45:53.1088331+00:00".toDate( .ISO8601Format( .Extended ))!
==> "2016-04-22 13:45:53 +0000"
```

Even if you pass in a custom format with the full precision it still truncates the last 4 digits:
```
ie: DateInRegion( absoluteTime: "2016-04-22T13:45:53.1088331+00:00".toDate( .Custom( "yyyy-MM-dd'T'HH:mm:ss.SSSSSSSZZZZZ" ))).toString( .Custom( "yyyy-MM-dd'T'HH:mm:ss.SSSSSSSZZZZZ" ))!
==> "2016-04-22T09:45:53.1080000-04:00"
```

**Comment by Hout** [comment]
Thanks for your report!

**Comment by malcommac** [comment]
Using S....prints fractional seconds (truncated to the count of letters)
I think you should use A....to print Milliseconds in day up to 6 digits.
https://github.com/malcommac/SwiftDate/blob/develop/Documentation/1.CreateDates.md
