### ISSUE TITLE
Time format with 12 hours time - hh:mm a

### ISSUE THREAD

**Issue by balazsnemeth** [malcommac/SwiftDate#198]
I would like to get 7:30 PM instead of the 19:30PM, on an NSDate:  `date`

`date.toString(DateFormat.Custom("hh:mm a"))`

I tried with HH:MM a, in every possible custom formatting, but it does not results the expected.

Could you take a look?

**Comment by malcommac** [comment]
Cannot reproduce this bug.
What's your default `NSLocale/NSTimezone`?
Have you tried to use `toString()` with the additional `inRegion` parameter by passing something like `LocaleName.EnglishUnitedStatesComputer` in order to force 12h format?

**Comment by malcommac** [comment]
it currently works, just set the locale:

```swift
let enRegion = Region(tz: TimeZoneName.europeRome, cal: CalendarName.gregorian, loc: LocaleName.englishUnitedStates)
let date = try DateInRegion(components: [.hour: 22], fromRegion: enRegion)
let c = date.string(custom: "hh:mm a") // print "10:00 PM"
```
