### ISSUE TITLE
weekdayName property not accessible?

### ISSUE THREAD

**Issue by ianthiel** [malcommac/SwiftDate#200]
I'm not seeing the weekdayName property when playing with a created date.

Here's how I'm creating the date (today's date):

```
let date = NSDate()
let userRegion = Region(calType: CalendarType.Gregorian, loc: NSLocale.currentLocale())
let localDate = date.inRegion(userRegion).localDate!
```

When I try to access the weekdayName:

`localDate.weekdayName
`

I get the following error: "Value of type 'NSDate' has no member 'weekdayName'"

**Comment by malcommac** [comment]
it's marked as public in develop branch.
scheduled for 3.0.8
