### ISSUE TITLE
toDate(_: ) return value wrong

### ISSUE THREAD

**Issue by cikpis** [malcommac/SwiftDate#201]
Hey guy, if you try the follow code, date is "1986-03-02 23:00:00 +0000" instead of nil.

```
let date = "31/02/1986".toDate(DateFormat.Custom("dd/MM/yyyy"))
```

The follow code is how the date should be checked:

```
func toDate(format: String = "yyyy-MM-dd'T'HH:mm") -> NSDate? {
   let dateFormatter = NSDateFormatter()
   dateFormatter.dateFormat = format
   return dateFormatter.dateFromString(self)
}
```

**Comment by malcommac** [comment]
I think it is a specific behavior of UIKit and not a bug, if you notice Feb 1986 has 28 days (+3 days) = 03 March. It try to "fix" your input date, probability it works only with leap days in feb.

**Comment by cikpis** [comment]
The problem is that I should know if the passed string date is valid or not. Return nil should be the logic to let you know that.

Anyway, I have another question. How come the toDate(_:) method was removed from version 4.x of SwiftDate? Which one should I use now? Thanks in advance for your answer.

Carmelo

**Comment by malcommac** [comment]
I agree but we cannot override the default behavior or UIKit without rewriting the entire logic and this is not in our plan.

We have just made a site with examples and docs about SwiftDate; you can found [datetime parsing functions here](http://malcommac.github.io/SwiftDate/parse_create_dates.html#fromstring) about date time parsing here.
Basically you can call:

```swift
let str = dateString.date(format: DateFormat)
```

**Comment by cikpis** [comment]
Thanks for the code. I've already tried that but I got a DateRegion object instead of NSDate or Date. Any clue?

**Comment by malcommac** [comment]
In fact we have missed to make public `.absoluteDate` or `.date `property. I've scheduled it for the next minor update 4.0.3.

**Comment by cikpis** [comment]
I see. Well, thanks for the info and let me know when that version is out ;)

Cheers!

**Comment by malcommac** [comment]
Sure.
Just follow issue #267

**Comment by cikpis** [comment]
Hi @malcommac, what is the new format of toDate(DateFormat.ISO8601Format(.Extended))?

I'm using 
```
createdAt = try json["createdAt"].stringValue.date(format: DateFormat.extended).absoluteDate
```
but always failed. Also, there is some other way to get the date without the try and catch?

**Comment by malcommac** [comment]
You can use ```.withInternetDateTime```:
```
let date4 = DateInRegion(string: "2001-02-03T15:30:00+01:00", format: .iso8601(options: .withInternetDateTime), fromRegion: regionRome)
```

**Comment by cikpis** [comment]
I tried but always failed.

**Comment by malcommac** [comment]
Ops my mistake, I did not see seconds.
Let's try:
```swift
let test = "2016-08-05T18:20:24.388Z"
do {
  let d = try test.date(format: .custom("yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ"))
  print("Parsed date is: '\(d)'")
} catch let err {
  print("Ops, failed to parse date: \(err)")
}
```

**Comment by cikpis** [comment]
I thought there was some default settings for that format. I knew I could use the custom one :)

Thanks for your time man. Chat to you soon!

**Comment by malcommac** [comment]
It could be a new option in ISO8601DateTimeFormatter class. See #293

**Comment by cikpis** [comment]
Cool! You rock!
