### ISSUE TITLE
Convert date to DotNet JSON date

### ISSUE THREAD

**Issue by canisal** [malcommac/SwiftDate#203]
Is it possible to convert a date from DD/MM/YYYY format to .NET JSON Format with SwiftDate.

Example: How to convert 03/06/1984 to something like "/Date(928138800000+0300)/"

Thanks.

**Comment by malcommac** [comment]
We have added it for 3.0.8 (need to write some unit tests for it).
Meanwhile it's available on develop branch since this commit https://github.com/malcommac/SwiftDate/commit/d909c124c0d9ebce97c8b9ced6824574dcbf7c62.
Thank you for your suggestion.

**Comment by canisal** [comment]
Thanks.
