### ISSUE TITLE
how time diff?

### ISSUE THREAD

**Issue by leancmscn** [malcommac/SwiftDate#204]
eg:
3m ago
1h ago
3days ago

1m end
2h end
3days end

from current time

**Comment by leancmscn** [comment]
recommend https://github.com/remirobert/Tempo
to do chat app time label

**Comment by malcommac** [comment]
Operation with dates:
https://github.com/malcommac/SwiftDate/blob/develop/Documentation/3.OperationsWithDates.md

Date to string with relative/colloquial formatting:
https://github.com/malcommac/SwiftDate/blob/develop/Documentation/6.DatesToString.md
