### ISSUE TITLE
NSDate().toString(DateFormat.Custom("yyyyMMddHHmmss")) return wrong result.

### ISSUE THREAD

**Issue by naokits** [malcommac/SwiftDate#205]
Hi.

> let now = NSDate().toString(DateFormat.Custom("yyyyMMddHHmmss"))
> print(now!)

my expected result is `20160506194315` but SwiftDate result `20160506午後74315`. 
my environment is:
- Xcode 7.3
- iOS 9.3.1
- Language Setting -> Japanese

**Comment by malcommac** [comment]
Cannot reproduce this bug event settings my iPhone to Japanese. Should I set something more?
Have you tried to also set a region toString(..., inRegion:) and using an english locale?

**Comment by EthanJoe** [comment]
try: NSDate().toString(format: DateFormatt.custom("..."))

**Comment by malcommac** [comment]
You should set your region's locale to english.
