### ISSUE TITLE
#199 was merged into develop branch with conflicts.

### ISSUE THREAD

**Issue by cgoldsby** [malcommac/SwiftDate#206]
The `develop` branch project no longer opens in XCode due to unresolved conflicts on [L922-L926](https://github.com/mrchenhao/SwiftDate/blob/aca65950c68871ea9a3714e741da4abd32ea7dcf/XCode/SwiftDate.xcodeproj/project.pbxproj#L922-L926) and [L951-L955](https://github.com/mrchenhao/SwiftDate/blob/aca65950c68871ea9a3714e741da4abd32ea7dcf/XCode/SwiftDate.xcodeproj/project.pbxproj#L951-L955).

```diff
- <<<<<<< Updated upstream
				CLANG_ENABLE_MODULES = YES;
- =======
				CODE_SIGN_IDENTITY = "iPhone Developer";
- >>>>>>> Stashed changes
```

**Comment by malcommac** [comment]
Fixed, thank you

**Comment by cgoldsby** [comment]
Sorry, but it looks like this is still not fixed in in the `develop` branch. #207 will resolve this bug.
