### ISSUE TITLE
Sample code for creating date from ISO8601 string returns nil

### ISSUE THREAD

**Issue by yigitserin** [malcommac/SwiftDate#208]
Hi there,

I need to convert ISO8601 string to date. However, the sample code returns nil. Here is the said code:

```
// Create date from string
let date1 = "2015-01-05T22:10:55.200Z".toDate(DateFormat.ISO8601)
```

[from here:](https://github.com/malcommac/SwiftDate/blob/master/Documentation/UserGuide.md)

**Comment by cgoldsby** [comment]
Looks like the documentation is incorrect. This example date string is using the [`ISO8601Type.Extended`](https://github.com/malcommac/SwiftDate/blob/0dd3a3c610f2147a92c834cb4bdb5d983dd5f37b/Sources/SwiftDate/NSDateFormatter%2BSwiftDate.swift#L78) format so the correct code would be:
```swift
let date1 = "2015-01-05T22:10:55.200Z".toDate(.ISO8601Format(.Extended))
```

**Comment by malcommac** [comment]
Fixed in develop. Thank you
https://github.com/malcommac/SwiftDate/commit/ec667aa0b07c1ca3312968105abce8c3fa7d4241

**Comment by efremidze** [comment]
👍
