### ISSUE TITLE
DateRegion or Region init(timezoneID:String value) don't found

### ISSUE THREAD

**Issue by jfbarragan** [malcommac/SwiftDate#209]
Hello,
In the documentation says that you can specify you region like this:
let newYork = DateRegion(timeZoneID: "EST")

But for doesn't appear for me any initializer with "timezoneID" that supports the string convention from timezone just this inits.
-Region()
-Region(calendarName: <#T##CalendarName?#>, timeZoneName: <#T##TimeZoneName?#>, localeName: <#T##LocaleName?#>)

I want to work just with UTC values, and convert the local timezone from my device to UTC and then compare with other UTC value.

Thanks, 
Francisco

**Comment by cgoldsby** [comment]
Documentation appears to be outdated. Looks like `DateRegion` only uses the `TimeZoneName` enum now. There are `TimeZoneName.Local` and `TimeZoneName.Gmt`. Hopefully, this may help you.

```
let newYork = DateRegion(timeZoneName: .AmericaNewYork)
let utc = DateRegion(timeZoneName: .Gmt) // UTC/GMT

// Create a date for XMas Day at midnight in New York
let date1 = NSDate(year: 2015, month: 12, day: 25, region: newYork) // 2015-12-25 10:00:00 +0000
let date2 = NSDate(year: 2015, month: 12, day: 25, hour: 5, region: utc) // 2015-12-25 10:00:00 +0000

if date1 == date2 {
    print("Dates are equal.")
}
```

Seems like `TimeZoneName.Custom(String)` would be a useful enhancement, though...

**Comment by malcommac** [comment]
You are correct, documentation is outdated. We have refreshed it in develop branch: https://github.com/malcommac/SwiftDate/tree/develop.
We will post the new one with 3.0.8 release.

I don't think TimeZoneName.Custom() is acceptable because the TimeZone should always return a valid object in order to simplify the creation.

**Comment by raf66** [comment]
Here's my issue: I am reading the timezone name from a Web Service.  Without timeZoneID (or the suggested TimeZoneName.Custom() solution), how can I possibly create a DateRegion from that JSON string?
