### ISSUE TITLE
Use of unresolved identifier 'DateFormat'

### ISSUE THREAD

**Issue by dmyers** [malcommac/SwiftDate#21]
Have you seen this error before?

```
Use of unresolved identifier 'DateFormat'
.toDate(format: DateFormat.ISO8601)
```

**Comment by malcommac** [comment]
Are you using it via CocoaPods?

**Comment by dmyers** [comment]
Yeah I am.

**Comment by malcommac** [comment]
Cannot reproduce the same problem. Here it works fine (added import SwiftDate); can you make a small project?
