### ISSUE TITLE
Why difference(toDate:unitFlags:) returns an optional?

### ISSUE THREAD

**Issue by bzmario** [malcommac/SwiftDate#211]
I don't see `difference(toDate:unitFlags:)` can return any error. It can only crash if `DateInRegion`'s `calendar` property is `nil`.

**Comment by malcommac** [comment]
You are correct.
Fixed in https://github.com/malcommac/SwiftDate/commit/704c29e678564dc66a7ffd02f157b63a39a32efd and scheduled for 3.0.8.
