### ISSUE TITLE
convert dateInRegion to NSDate type

### ISSUE THREAD

**Issue by brokeniceinteractive** [malcommac/SwiftDate#212]
I have a DateInRegion object, if i call abolutetime i get a UTC time, if i call toString i obtain a localTime, how can i obtain a local time as NSDate object? .localTime is deprecated!

**Comment by brokeniceinteractive** [comment]
i use this now:

> let dt = date.inRegion(DateRegion())
        
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
        let dat:String? = dt.toString(DateFormat.Custom("yyyy-MM-dd HH:mm:ss"))
        return dateFormatter.dateFromString(dat!)!

**Comment by malcommac** [comment]
I've just added .localAbsoluteTime in develop branch https://github.com/malcommac/SwiftDate/commit/1d53ffe082dff5d25bca65715f4358bf4677ab2e.
We will release it with 3.0.8 but you can use the implementation code as workaround in order to avoid string-date conversions.
```swift
public var localAbsoluteDate: NSDate {
   let seconds = self.timeZone.secondsFromGMTForDate(self.absoluteTime)
   return NSDate(timeInterval: NSTimeInterval(seconds), sinceDate: self.absoluteTime)
}
```

**Comment by Hout** [comment]
Objection your honour! There is no such thing as a *local* absolute date or time. By introducing this you create ambiguity in the library data model.

@brokeniceinteractive you are missing the point. The `absoluteTime` property does not returns UTC time; it returns NSDate which is an absolute time independent of location. However it is represented as UTC time in Cocoa but you are free to represent it in any format in any location.

**Comment by malcommac** [comment]
It's right, there not an ```localAbsoluteDate``` and it does not make sense. You can still get the absolute date by using ```.absoluteDate``` property or convert it to a GMT/UTC region using ```toRegion(Region.GMT())``` function.

**Comment by samad5353** [comment]
I want DateInRegion() as Date?? 
I am using version 4.0.3 and i am not getting ```localAbsoluteDate```

**Comment by GuiAfonso** [comment]
Hi, I have a DateInRegion but my function(query pedometer) don't accept DateInRegion type how can I get the Date without missing my region Timezone. 

```
let date1 = Date()               2017-05-06 20:22:14 +0000 (Wrong Timezone)
let date2 = DateInRegion()       6 May 2017 17:22:14 GMT-3 (Right Timezone but not 'Date' type)
let date3 = date1.inRegion()     6 May 2017 17:22:14 GMT-3 (Right Timezone but not 'Date' type)
let date4 = date2.absoluteDate   2017-05-06 20:22:14 +0000 (Wrong Timezone)
```

I already put `Date.setDefaultRegion(Region.Local())`  on my  AppDelegate
Sorry if is a noob question, but I'm not found the answer yet.

**Comment by malcommac** [comment]
Hi,
`NSDate/Date` only represents an absolute point in time. It has no concept of timezone or calendar. When you create a NSDate instance it is just a number of seconds since January 1st 2001 GMT It does not matter if you are in New York, Rome or Barcelona.
So when you are asking for `absoluteDate` (old was `localAbsoluteDate`) you are asking for the absolute representation of the date in GMT zone.
If you need to get a string representation of the date including the timezone you can use `string(format: .iso8601Auto)` or any other options of the ISO8601.
