### ISSUE TITLE
Create Date/DateInRegion at the next day of the week (ie. "Next Friday" [since ref date])

### ISSUE THREAD

**Issue by otymartin** [malcommac/SwiftDate#214]
@malcommac 
I'm new to this library so I haven't discovered yet how to create these objects. I couldn't find any direct references in the swift files.

`Next Friday`
`Next Saturday`
`Next Sunday`

**Comment by malcommac** [comment]
We don't support it yet, but seems a nice addition.
Meanwhile you can user NSCalendar nextDateAfterDate.
Let me show to you an example:

```swift
let components = NSDateComponents()
components.weekday = 1 // in Gregorian 1 is Sunday
let nextSunday = self.calendar.nextDateAfterDate(self.absoluteTime, matchingComponents: components, options: [.MatchNextTimePreservingSmallerUnits])
```

**Comment by Hout** [comment]
If added then please add to docs that next Friday means *the first Friday after today*.
Not to be confused with *the Friday in next week*.

**Comment by otymartin** [comment]
@malcommac Thanks

I had since simplified what i was trying to do however I believe that would be a really handy convenience method to offer. I basically wanted my users to create events. Using `UIDatePicker`  I wanted to limit the possible options to the following `Friday` `Saturday` or `Sunday` on the condition that those days are `atleast 5 days` away. (Gives users time to organize themselves)

So my first time using the library, i was playing around trying to create these objects with this syntax
`var nextFriday = NSDate().nextFriday` I guess it just felt natural even though the method didn't exist.
etc..

//My simplified solution 😂
```swift
       let today = NSDate()
        let day1 = today + 1.days
        let day2 = today + 2.days
        let day3 = today + 3.days
        let day4 = today + 4.days
        let day5 = today + 5.days
        let day6 = today + 6.days
        let day7 = today + 7.days
```

**Comment by malcommac** [comment]
I've scheduled it for 4.1.0.

**Comment by otymartin** [comment]
@malcommac Dope 🙌

**Comment by malcommac** [comment]
Added in 4.0.8 (https://github.com/malcommac/SwiftDate/commit/b9d6cecd2c4ed79fc350e2ef0573396450072356).
We have .next() func both for Date and DateInRegion objects.

Examples:

``` swift
let now = DateInRegion() // 30 nov 2016, 13:55:04 CET
let nextFriday = now.next(day: .friday) // 02 dic 2016, 00:00:00 CET
let nextMonday = now.next(day: .monday) // 05 dic 2016, 00:00:00 CET
``` swift

**Comment by otymartin** [comment]
beautiful thanks @malcommac

**Comment by malcommac** [comment]
Thank you for your suggestion :)
