### ISSUE TITLE
let date = (2015.years | 12.months | 25.days) returns NSDateComponents

### ISSUE THREAD

**Issue by guidolodetti** [malcommac/SwiftDate#217]
Hello,

differently from the documentation, the following code returns an `NSDateComponents ` instead of `NSDate`:

`let date = (2015.years | 12.months | 25.days)`

<img width="981" alt="screen shot 2016-05-31 at 11 44 38" src="https://cloud.githubusercontent.com/assets/7063023/15670306/089fa1c8-2725-11e6-8aad-8fc40fe6ae33.png">

**Comment by Hout** [comment]
Stale docs. Nowadays you shoul dinitialise with:
```
let date = NSDate(year: 2015, month: 12, day: 25)
```

**Comment by malcommac** [comment]
Since SwiftDate 4 you can init it using:

```swift
let date = try! DateInRegion(components: [.year: 2015, .month: 12, .day: 25])
```
