### ISSUE TITLE
readme.md question

### ISSUE THREAD

**Issue by 3895177** [malcommac/SwiftDate#218]
" It encapsulates a moment in time that is  internally stored as the number of seconds since Jan 1, 2001 at 00:00 UTC. "  in the ReadMe.md.
Is writing wrong?
The time should be "Jan 1, 1900 at 00:00 UTC. " .

**Comment by Hout** [comment]
Nope! Please refer to the [docs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSDate_Class/):

`NSDate` objects encapsulate a single point in time, independent of any particular calendrical system or time zone. Date objects are immutable, representing an invariant time interval relative to an absolute reference date (00:00:00 UTC on 1 January 2001).
