### ISSUE TITLE
NSDateInterval is an actual class with iOS 10.0+

### ISSUE THREAD

**Issue by brianmichel** [malcommac/SwiftDate#220]
As of iOS 10.0+, `NSDateInterval` is an actual class in the iOS SDK. This class needs to renamed in the SwiftDate library in order to be used within Xcode 8.0.

Reference: https://developer.apple.com/reference/foundation/nsdateinterval

**Comment by ddunbar** [comment]
To clarify a bit more, I believe what is going on here is that it has become an error in the updated clang to redeclare an Objective-C class in Swift and then export it.

**Comment by brianmichel** [comment]
> To clarify a bit more, I believe what is going on here is that it has become an error in the updated clang to redeclare an Objective-C class in Swift and then export it.

Either way, renaming this class should solve the problems.

**Comment by ddunbar** [comment]
Yes!

**Comment by Hout** [comment]
Thx! `NSDateInterval` was added from the Swift.org Foundation library with the intention to merge it once published. I.e. our version should be removed and the Swift 3.0 version used.

The pull request is a nice workaround for the time being though.

**Comment by Hout** [comment]
I will work on it when I find time. Any help appreciated.

**Comment by brianmichel** [comment]
> Thx! NSDateInterval was added from the Swift.org Foundation library with the intention to merge it once published. I.e. our version should be removed and the Swift 3.0 version used.
> 
> The pull request is a nice workaround for the time being though.

While I agree wit this (that this class ultimately be removed) I'd be nice to not wait until the finalization of Swift 3.0 to make this library compatible.

**Comment by fabiomassimo** [comment]
I agree with @brianmichel that for the time being this fix would help users of the SwiftDate to easily integrate it with Swift 2.3 which I believe is going to be used for a while due to major changes that comes with Swift 3.0.

**Comment by AndrewBarba** [comment]
Any updates on this now that the GM's are released? Would be really helpful to get this working with Swift 2.3 at the very least

**Comment by Hout** [comment]
I will investigate this tomorrow.

**Comment by AndrewBarba** [comment]
Any updates here?

**Comment by malcommac** [comment]
Fixed in SwiftDate4
