### ISSUE TITLE
Ago format missing

### ISSUE THREAD

**Issue by netbe** [malcommac/SwiftDate#225]
I might be mistaken but could not see any helper to get the "2 days ago" or 1h ago syntax. There is something similar like:

```
        let twoDaysAgo = NSDate.today() - 2.days
        let region = Region(calendarName: nil, timeZoneName: nil, localeName:  LocaleName.GermanGermany)
        var style = FormatterStyle(style: .Full, units: .Day, max: 1)
        style.approximate = true
        return twoDaysAgo.toNaturalString(NSDate.today(), inRegion: region, style: style)!
       // this will produce "about 2 Tage"
```

So the approximate word is not localised and there is no choice in it only *about* or *remaining*.

**Comment by malcommac** [comment]
Just added colloquial functions which should be able to do what are you searching for.
[Check out it here](http://malcommac.github.io/SwiftDate/formatters.html#colloquial).
Thanks.
