### ISSUE TITLE
getting nil from custom format

### ISSUE THREAD

**Issue by ilandbt** [malcommac/SwiftDate#226]
Hi,
I'm getting a utc date from my server.
locally i'm in a different time zone.

```swift
let stringDate = "2016-07-14T04:00:00.000Z"
let date = stringDate.toDate(.Custom("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"))
```
In this case date is nil

The other way it works (NSDate to string)
```swift
let stringDate = NSDate().toString(.Custom("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"))
```

Thanks

**Comment by malcommac** [comment]
Fixed in https://github.com/malcommac/SwiftDate/commit/4f7d5a81bc0c1f09e6ef352e95e679962be15483 (develop, swift 23 and swift 3 branches)

**Comment by ilandbt** [comment]
Thanks
