### ISSUE TITLE
localization like  MatthewYork/DateTools?

### ISSUE THREAD

**Issue by ryh** [malcommac/SwiftDate#23]
[MatthewYork/DateTools](https://github.com/MatthewYork/DateTools) is also MIT licensed Open source project, Can we just copy `*.strings` [bundle](https://github.com/MatthewYork/DateTools/tree/master/DateTools/DateTools.bundle)
 and paste it, and credit it?

**Comment by malcommac** [comment]
Library should not be related to any language, it's a date manipulation library and it must remain independent.
