### ISSUE TITLE
Swift 2.3 support - branch missing?

### ISSUE THREAD

**Issue by alpennec** [malcommac/SwiftDate#230]
Hello,
I can't find any branch for iOS Swift 2.3.
Is is possible to have one so we can start migrating SwiftDate to Swift 2.3 (+ use it in our projects with Carthage and CocoaPods).
Thanks,
Axel

**Comment by malcommac** [comment]
Checkout Swift_23 branch
https://github.com/malcommac/SwiftDate/tree/feature/swift_23

**Comment by alpennec** [comment]
Thanks!

**Comment by marchy** [comment]
Is this already merged to master / a Cocoapods release?

**Comment by fphcare** [comment]
Do you have a version which support swift 2.3? Thanks
