### ISSUE TITLE
.startOf(.Day) return a wrong date

### ISSUE THREAD

**Issue by panuavakul** [malcommac/SwiftDate#231]
Hi, I'm running into problem where 
`print(NSDate())` -> `2016-08-01 02:18:24 +0000`
`print(NSDate().startOf(.Day))` -> `2016-07-31 15:00:00 +0000`

I'm thinking that because .startOf for `NSDate` just convert `NSDate` to `DateInRegion` and then use the `.startOf` method of the `DateInRegion`. So the `NSDate()` create the absolute time which is 2016-08-01 02:18:24 +0000 (I'm in Japan time zone) and then it got converted `DateInRegion` and then back to absolute time which is -9 hours due to going back to UTC time and it messed up then.

Is this happen to be a bug?

edited: Actually I was wrong, the time that I was printing it out was `11:18:24` so that mean 
`print(NSDate())` -> `2016-08-01 02:18:24 +0000` is already the UTC time
so when `.startOf(.Day)` was done it go back to `2016-08-01 00:00:00 +0000` and then go back another 9 hours to `2016-07-31 15:00:00 +0000`, so this really seems like a bug to me or am I just not using it properly?

**Comment by malcommac** [comment]
Fixed in SwiftDate4:

```swift
print(Date()) // 2016-09-30 18:47:52 +0000
print(Date().startOf(component: .day)) // 2016-09-30 00:00:00 +0000
```
