### ISSUE TITLE
DateInRegion / toString / toDate is not using default NSLocale

### ISSUE THREAD

**Issue by francisykl** [malcommac/SwiftDate#232]
As per title, the functions toString:inRegion / toString does not take into account of default locale that is set.

```
        let calendar = NSCalendar(calendarIdentifier: NSCalendarIdentifierGregorian)
        calendar?.locale = NSLocale(localeIdentifier: "en_US_POSIX")

        SwiftDate.Region.setDefaultRegion(Region(cal: calendar, tz: _ANYTIMEZONE_, loc: NSLocale(localeIdentifier: "en_US_POSIX")))

```

**Comment by malcommac** [comment]
Fixed.

Since SwiftDate 4 ```.defaultRegion``` is a ```Region``` which has:
- GMT as ```TimeZone```
- Device's locale as ```Locale```
- Device's calendar as ```Calendar```

You can however change it anytime using ```.setDefaultRegion()```.
You can, for example, use ```Region.Local()``` to get a region created using all locale's settings, including timezone.
