### ISSUE TITLE
Differences in Unit between two dates

### ISSUE THREAD

**Issue by szuniverse** [malcommac/SwiftDate#233]
Hi

Im a little bit confused.
Is it possible with this SwiftDate library to calculate the difference between two NSDate() in seconds?
If yes, could you write me an example?
thanks

**Comment by tcurdt** [comment]
I was also hoping for

```
let a = NSDate(..)
let b = NSDate(..)
let d: NSTimeInterval = a - b
```

but `timeIntervalSinceDate` seems still the way to go.

**Comment by malcommac** [comment]
It will be part of the new major update (and it will be reserved to Swift 3).
Basically you will be able to write:

```
let date1 = ...
let date2 = ...
let diff = (date2-date1).in(.seconds) // or .hour, .days etc.
```

**Comment by malcommac** [comment]
added in SwiftDate 4 as [TimeInterval extension](http://malcommac.github.io/SwiftDate/extensions.html#timeinterval).
Thanks for your suggestion.
