### ISSUE TITLE
How to display "mo" instead of "m" for months

### ISSUE THREAD

**Issue by netgfx** [malcommac/SwiftDate#235]
Trying to get month to display as "mo" instead of "m" because it is confusing with minutes. Is there a way to change this?

Using the following:

```
 let myDate = date.toDate(DateFormat.Custom("yyyy-MM-dd HH:mm:ss "))
 let timeDiffence = NSTimeZone.localTimeZone().secondsFromGMTForDate(myDate!)
```

Thanks in advance!

**Comment by malcommac** [comment]
I'm sorry but I don't understand what you try to accomplish with the code below and what you wrote :(

**Comment by netgfx** [comment]
nevermind, I figured it out. thanks anyways.
