### ISSUE TITLE
String toDate with .Custom format with 'Z' is nil

### ISSUE THREAD

**Issue by roma86** [malcommac/SwiftDate#236]
Hello. Thank you for this great library.

I may be wrong, but i stuck for about half of the day with string to date conversion. 
Finally i have found this inconsistent behaviour: 

- NSDateFormatter successfully convert date like `2016-09-01T00:00:00.000Z` to the `NSDate` with format `yyyy-MM-dd'T'hh:mm:ss.SSS'Z'`

- SwiftDate with same input and settings return `nil`

Screenshot:

![dateformattests swift edited 2016-09-03 22-56-45](https://cloud.githubusercontent.com/assets/3889620/18227377/eb2c2f70-722a-11e6-92ea-ae6df533ba1d.jpg)

Maybe I misunderstood how to use `toDate .Custom`?

### In addition 1

`date.toString(.Custom("yyyy-MM-dd'T'hh:mm:ss.SSS'Z'"))` does work with success.

### In addition 2

in my examples format `yyyy-MM-dd'T'hh:mm:ss.SSS'Z'` is incorrect and should be `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`, but this does not change issue general flow.

**Comment by roma86** [comment]
### In addition

`date.toString(.Custom("yyyy-MM-dd'T'hh:mm:ss.SSS'Z'"))` does work with success.

**Comment by malcommac** [comment]
checked in SwiftDate4 and it's okay.

**Comment by hackolein** [comment]
If I try this: "2016-09-16T13:13:05+02:00".date(format: DateFormat.custom("yyyy-MM-dd'T'HH:mm:ssZZZZZ"), fromRegion: Region(tz: TimeZoneName.europeRome, cal: CalendarName.gregorian, loc: LocaleName.germanGermany))
let (colloquial,relevantTime) = try! (message?.callEnd)!.colloquialSinceNow()

I got the error "fatal error: unexpectedly found nil while unwrapping an Optional value" in Line 226 in DateInRangeFormatter.
But the Date is valid and the absoluteTime is correct.
