### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kanishkatn** [malcommac/SwiftDate#237]
Hi,

I installed the lib through pod. I am not able to use any of the NSDate methods. 

Could anyone please help me set this up?

BTW, I am using swift 3.

**Comment by malcommac** [comment]
see https://github.com/malcommac/SwiftDate/issues/238

**Comment by malcommac** [comment]
On [swift-3.0 branch](https://github.com/malcommac/SwiftDate/tree/feature/swift-3.0) you will found a 3.0 version.
I'm also working on a major update of the library which will be better suits in Swift 3.0. Hope to post some news in two weeks.

**Comment by ArilexWang** [comment]
me too , i pod  'SwiftDate', '~> 4.0.13' and after compile, it still doesn't work
