### ISSUE TITLE
Swift 3 Refactoring

### ISSUE THREAD

**Issue by mecid** [malcommac/SwiftDate#238]
Xcode 8 GM, Swift 3.0
In Xcode 8 beta 4 Calendar.Unit appears to be renamed to Calendar.Component.
Please fix this, i need to publish new build before iOS 10 released.

`extension Calendar.Unit {
}`

**Comment by malcommac** [comment]
I'm working on it in https://github.com/malcommac/SwiftDate/tree/feature/swift-3.0 but there are tons of different things around here (I've started thinking that we should need a big refactor due to some deep change).
Actually this branch does not compile...

**Comment by RickPasveer** [comment]
There is a class naming duplication with DateFormatter.

Apple renamed NSDateFormatter to DateFormatter.
But SwiftDate also has a class named DateFormatter which doesn't have dateFormat, timeZone variables.

**Comment by malcommac** [comment]
On [swift-3.0 branch](https://github.com/malcommac/SwiftDate/tree/feature/swift-3.0) you will found a 3.0 version.
I'm also working on a major update of the library which will be better suits in Swift 3.0. Hope to post some news in two weeks.
