### ISSUE TITLE
DateFormatter conflicts with iOS own "DateFormatter" class

### ISSUE THREAD

**Issue by estemendoza** [malcommac/SwiftDate#242]
On Swift 3, Apple renamed NSDateFormatter to DateFormatter, making a conflict between the SwiftDate class "DateFormatter" in https://github.com/malcommac/SwiftDate/blob/feature/swift-3.0/Sources/SwiftDate/DateFormatter.swift

For example, the following code:

```
let dateFormatter = DateFormatter()
dateFormatter.locale = Locale(localeIdentifier: "en_US")
```

tells me that DateFormatter has no "locale" member

I am using Xcode 8 GM.

Hope you can fix this.

**Comment by scrainie** [comment]
I simply placed a prefix on the DateFormater.swift class for now...

public class SCDateFormatter {

}

**Comment by ddhhz** [comment]
I'm using fully qualified name SwiftDate.DateFormatter for now.

**Comment by balazsnemeth** [comment]
Or otherwise you can use this: `Foundation.DateFormatter()`

**Comment by malcommac** [comment]
Fixed in SwiftDate 4. Thanks.
