### ISSUE TITLE
error: can't unsafeBitCast between types of different sizes

### ISSUE THREAD

**Issue by raven** [malcommac/SwiftDate#243]
Hi there 👋 

I'm using the `feature/swift-3.0` branch, with Xcode 8 (Appstore release), and am getting a crash on https://github.com/malcommac/SwiftDate/blob/feature/swift-3.0/Sources/SwiftDate/Calendar%2BSwiftDate.swift#L44 of
> error: can't unsafeBitCast between types of different sizes

when doing a simple `Date().add(components: 9.hours)`. 

Any thoughts or more information I could provide?

**Comment by raven** [comment]
So I'm not super up to date with `unsafeBitCast` but I can have a rough guess as to what's gone down.
Previously the extension was on `NSCalendar`, which would require a class pointer, then recently there was the change to make the extension for `Calendar` instead, which is a struct, which has a different size. 

I was able to successfully carry on by changing the line to:
`return unsafeBitCast(self as NSCalendar, to: CFCalendar.self)`

**Comment by malcommac** [comment]
Merged
