### ISSUE TITLE
Maybe it is the time to update the changelog and user guide

### ISSUE THREAD

**Issue by vulgur** [malcommac/SwiftDate#251]
I've noticed that many APIs have changed, so hope that changelog and user guide update too

**Comment by malcommac** [comment]
I'm working on a new fully Swift 3 compatible version of swiftdate-4.0 branch. It will takes at least another week so be patient :(

**Comment by malcommac** [comment]
We have wrote a new site at [http://www.swift-date.com](http://www.swift-date.com) where you can found both examples and docs.
