### ISSUE TITLE
DateFormatterComponentsStyle lacks a lot of what FormatterStyle offered?

### ISSUE THREAD

**Issue by robertjpayne** [malcommac/SwiftDate#255]
Just upgrading and noticed that `toNaturalString` along with `FormatterStyle` is pretty much gone and replaced with just a simple enum of `DateFormatterComponentsStyle`.

Is there any way to still use `FormatterStyle`? It had a lot more to offer in regards to flexibility etc…

**Comment by malcommac** [comment]
Check out SwiftDate 4 colloquial [functions here](http://malcommac.github.io/SwiftDate/formatters.html#colloquial)
