### ISSUE TITLE
Swift-3.0 branch does not test properly

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#258]
Many tests in the Swift-3.0 branch failed. 

The tests were written to check whether the code complies with the specs. The intention is that you cannot submit code that breaks the tests. Either the specs and the tests have to be adapted in order to improve the code OR the tests should run successful.

I will submit a few fixes tonight. Your help appreciated!

**Comment by Hout** [comment]
Pull request #252 fixes some. Checking...

**Comment by malcommac** [comment]
We have started rewrote all the tests using XCTest in order to avoid gap in Swift updates (as it happened between Swift 2 and 3).
There are about 80 tests right here; we can continue from here. Now all the tests compiles in Swift3 of course.
