### ISSUE TITLE
Seconds to hh:mm:ss format in SwiftDate Swift 3.0

### ISSUE THREAD

**Issue by dhamukrish** [malcommac/SwiftDate#260]
Could you please help me what is wrong in Swift 3 code. Basically this function converts elapsed seconds to  this format - `s, ss, m:ss mm:ss, h:mm:ss`. Below function was working fine in Swift 2.x but in Swift 3 returning as `m,ss` rather `m:ss` (comma rather colon).

**Swift 2.x**
```
public class func secondsToTimeString(seconds: Double) -> String {
    var format = FormatterStyle()
    format.maxUnits = 3
    format.style = .Positional
    
    let refDate = NSDate()
    return refDate.toNaturalString(refDate + Int(seconds).seconds, style: format)!
}
```
**Swift 3.0**
```
open class func secondsToTimeString(_ seconds: Double) -> String {
    let refDate = Date()
    let toDate = refDate + Int(seconds).seconds
    
    return toDate.toString(fromDate: refDate, inRegion: nil, style: .positional)!
}
```

**Comment by malcommac** [comment]
you need to specify the component separator.
Check out the new SwiftDate 4 [functions here](http://malcommac.github.io/SwiftDate/formatters.html#timecomponents).
