### ISSUE TITLE
Duplicate interface definition for class 'NSDateInterval'

### ISSUE THREAD

**Issue by monica18p** [malcommac/SwiftDate#262]
My project specification is Swift 2.3, ios 8+, Xcode 8
My pod description is 
`pod 'SwiftDate' , :git => 'https://github.com/malcommac/SwiftDate', :commit => 'f1225b89f41cd668acee9030ad472d4052209974'`

I am getting following two errors :
1. Duplicate interface definition for class 'NSDateInterval' - in `SwiftDate-Swift.h` file
2. Could not build objective C module 'SwiftDate'

Please tell me what am I missing.

**Comment by monica18p** [comment]
Even if i specify `pod 'SwiftDate'`
Still i get the same errors

**Comment by rogpfreck** [comment]
This worked for me:

1. remove SwiftDate from pod file
2. pod install in terminal
3 add 
pod 'SwiftDate', :git => 'https://github.com/malcommac/SwiftDate.git', :branch => 'feature/swift_23'
to pod file
3. pod install in terminal

good luck

Roger

**Comment by rogpfreck** [comment]
terminal 3 = terminal

**Comment by rogpfreck** [comment]
This worked for me:

1. remove SwiftDate from pod file
2. pod install in terminal 
3. add pod 'SwiftDate', :git => 'https://github.com/malcommac/SwiftDate.git', :branch => 'feature/swift_23' to pod file
4. pod install in terminal
good luck

Roger

**Comment by monica18p** [comment]
Worked for me. 
Thanks.

**Comment by malcommac** [comment]
It was fixed in SwiftDate 4 on master branch.
