### ISSUE TITLE
how to properly get values of colloquialSinceNow()?

### ISSUE THREAD

**Issue by pml2571** [malcommac/SwiftDate#265]
The function breaks when I run. What is the proper way of getting values of `colloquialSinceNow()`  

`let seconds = post.createdAt?.doubleValue`
`let dateObject = Date(timeIntervalSince1970: seconds) as Date`
`var createdAt = DateInRegion(absoluteDate: dateObject)`
`let (timeAgo, time) = try! createdAt.colloquialSinceNow()`  <- breaks
`let time = timeAgo`

What I am doing wrong here?

console:
![screen shot 2016-09-29 at 6 10 05 pm](https://cloud.githubusercontent.com/assets/3819719/18977540/0e98b3d0-8670-11e6-91c8-0e2e219a5661.png)

**Comment by malcommac** [comment]
Seems SwiftDate.bundle was not copied into framework.
Just pushed 4.0.1,try a pod update and tell me if it works.
Thanks

**Comment by malcommac** [comment]
Should be solved in 4.0.2. Make a pod update and tell me if it's okay.

**Comment by pml2571** [comment]
It works on simulator. However, it crashes and gives same error when run on my device. 

Another error I'm getting is on my simulator for the post that just has been created, I think it cannot correctly calculate colloquialSinceNow for the 'time now' but it works fine after relaunching since the time gets passed some seconds (prints 'just now' as it should, but when the time is same exactly same as colloquialSinceNow it crashes)

console:
![screen shot 2016-10-01 at 12 28 44 am](https://cloud.githubusercontent.com/assets/3819719/19012583/0c92a33e-876f-11e6-9e88-c9ed9796ed20.png)

**Comment by malcommac** [comment]
The first one should be related to #271 and should be okay for 4.0.3. You can try it in [4.0.3 branch](https://github.com/malcommac/SwiftDate/tree/feature/4.0.3) (I'll release it on monday).

Have you received a `.FailedToCalculate` exception when both dates are equals? Can you post a snippet of code?

**Comment by malcommac** [comment]
Ok reproduced and closed for 4.0.3.
See #272

**Comment by pml2571** [comment]
Thank you!
