### ISSUE TITLE
Unnecessary strings are printed in Xcode console

### ISSUE THREAD

**Issue by dhamukrish** [malcommac/SwiftDate#269]
I can see unnecessary strings `minute` and  `second` are printed in the Xcode console when I invoke below function. Please advise.

Please note that SwiftDate version is 4.0.2

```
func secondsToTimeString(_ seconds: TimeInterval) -> String {
  let refDate = Date()
  let toDate = refDate + Int(seconds).seconds
    
  do {
    return try (refDate - toDate).string(unitStyle: .positional, max: 4, zero: nil, separator: ":", locale: nil)!
  } catch {
    return ""
  }
}
```

**Comment by malcommac** [comment]
Thank you. It was fixed and will be part of the upcoming 4.0.3 release (see https://github.com/malcommac/SwiftDate/commit/2118282dc505873a1e8ad340805840b3bea797b5)
