### ISSUE TITLE
DateInRegion to Date object in version 4.0.2

### ISSUE THREAD

**Issue by dhamukrish** [malcommac/SwiftDate#270]
Could you please advise how do we get `Date` object from `DateInRegion`.

Basically in previous version, I could see we had Date overload.
`Date(year: 2020, month: 12, day: 31)`

But I could not see any property or method to get `Date` object from SwiftDate `DateInRegion` in version SwiftDate 4.0.2.

Please advise.

**Comment by malcommac** [comment]
Hi @dhamukrish see #267
