### ISSUE TITLE
Swift 2.3 migration crash in formatter

### ISSUE THREAD

**Issue by sherm4n90** [malcommac/SwiftDate#278]
Previously i was using this code: 

```
    let style = FormatterStyle(style: .Abbreviated, units: [.Hour, .Minute, .Second], max: 1)
    guard let shortDate = date.toString(NSDate.networkDate(), inRegion: nil, style: .Abbreviated) else {
      return "+24h"
    }
    return date < 24.hours.ago ? "+24h" : shortDate
```

It worked ok.
Now I updated to swift 2.3 using Xcode 8 and It wont let me to use the `FormatterStyle` class so I changed my code to this:

```
    let formatter = DateFormatter(unitsStyle: .Abbreviated)
    formatter.allowedUnits = [.Hour, .Minute, .Second]
    formatter.maxUnitCount = 1
    guard let shortDate = formatter.toString(date.timeIntervalSinceDate(NSDate.networkDate())) else {
      return "+24h"
    }
    return date < 24.hours.ago ? "+24h" : shortDate
```

Now getting a crash in the `guard` line. Following it to:
![screen shot 2016-10-04 at 10 29 45 am](https://cloud.githubusercontent.com/assets/12735630/19076027/9c08abc0-8a1d-11e6-87d4-59832163b3e5.png)

The crash reason is:`fatal error: unexpectedly found nil while unwrapping an Optional value`

**Comment by malcommac** [comment]
Sorry I've not enough time to support old 2.3 version.
I'll be happy to integrate any bug fixing related PR.
