### ISSUE TITLE
Make Swift 3 main branch

### ISSUE THREAD

**Issue by abunur** [malcommac/SwiftDate#281]
Not sure why Swift 3 is not the master / dev branch currently?  We are well past Swift 3 release and pre-swift 3 won't even compile in Xcode 8.  Pulling from the latest on Swift 3 branch I am at version 3.0.9 while the latest version is 4.0.4.  If main branch is already Swift 3 moving forward please delete the Swift 3 branch to avoid confusion.

thanks

**Comment by raven** [comment]
@abunur `master` is already Swift 3 / Xcode 8 compatible, so I guess you're asking for the maintainers to remove the branch `feature/swift-3.0` to avoid confusion?

**Comment by abunur** [comment]
Yes exactly - was not sure if master was Swift 3 or not, b/c of the existence of separate Swift 3 branch still.  So please remove the branch.

**Comment by Damnum** [comment]
I can't get the current master to work with Swift 3. I get the same error reported in https://github.com/malcommac/SwiftDate/issues/222#issuecomment-245939262

Only branch `feature/swift-3.0` works for me with Carthage.

**Comment by raven** [comment]
@Damnum this sounds like a different issue. Could you open a new issue with and supply the output of the following commands:
`carthage version`
`xcode-build -version`
`cat Cartfile`
And the command you're using to build with Carthage ie `carthage update`? 

FYI I got both 4.0.4 and master building using carthage 0.18 and Xcode 8.0

**Comment by Damnum** [comment]
@raven sorry my bad, it works now.

My mistake was I declared the dependency in the Cartfile like this:

`github "malcommac/SwiftDate"`

Because there is an old tag named "v3.0.0" in the repository, Carthage thought this was the newest tag and downloaded it.

`github "malcommac/SwiftDate" ~> 4.0.4`

works. But it would be helpful to rename this tag to prevent this from happening.

**Comment by malcommac** [comment]
Ok I've removed the branch. It should now work fine.
