### ISSUE TITLE
Issue with Colloquial?

### ISSUE THREAD

**Issue by KyleGoslan** [malcommac/SwiftDate#290]
Am I misusing the `colloquial` method or is this a bug?

```swift
try! Date().colloquial(to: date).colloquial
```

<img width="1130" alt="screen shot 2016-10-07 at 18 14 26" src="https://cloud.githubusercontent.com/assets/6042643/19199017/e8a82354-8cb9-11e6-9834-0f34f53e0964.png">

`date` is a future `Date` : 2016-10-16 00:00:00 +0000

**Comment by wsdwsd0829** [comment]
may be a fix
https://github.com/wsdwsd0829/SwiftDate/commit/8e5e6b120004d9464a86cc9cf18ce7f97336b3da

**Comment by malcommac** [comment]
Yep it was actually fixed in 4.0.4 :)
