### ISSUE TITLE
func setDefaultRegion is an instance method of Date?

### ISSUE THREAD

**Issue by hongxinhope** [malcommac/SwiftDate#292]
Found that:
```
internal var DateDefaultRegion: Region = Region.GMT()
public func setDefaultRegion(_ region: Region?)
```

```setDefaultRegion``` is an instance function, so how can it called like ```Date.setDefaultRegion(:)``` in the [documentation](http://malcommac.github.io/SwiftDate/main_concepts.html#default_region)?

In my opinion, both ```setDefaultRegion``` and ```DateDefaultRegion``` should be static, is this a mistake?

**Comment by malcommac** [comment]
it's a bug, clearly there need to be static methods of Date object.

**Comment by malcommac** [comment]
Fixed in https://github.com/malcommac/SwiftDate/commit/73b4b97d9991c7886ec893d80c5c13e215421ba8.
Scheduled for the next minor update 4.0.5.
