### ISSUE TITLE
ColloquialsinceNow crash

### ISSUE THREAD

**Issue by raven** [malcommac/SwiftDate#294]
https://github.com/malcommac/SwiftDate/issues/283 did not get fixed in 4.0.4. The issue was closed because a fix went in, that since got reverted.

**Comment by codingrhythm** [comment]
@raven I don't think the fix was merged to 4.0.4 when I was looking at the commit history of master branch

**Comment by malcommac** [comment]
It's on 4.0.5. My mistake :)
I'll release it soon later today.
