### ISSUE TITLE
Carthage build fails for version 4.0.5

### ISSUE THREAD

**Issue by nezhyborets** [malcommac/SwiftDate#296]
SwiftDate 4.0.5
iOS 8.0+
Integrating with Carthage

Fails with following output http://pastebin.com/Xm0x5dBC

**Comment by malcommac** [comment]
I've tried right now and it works fine.
My cartfile:
```
github "malcommac/SwiftDate" ~> 4.0.5
```
Result:
<img width="494" alt="screen shot 2016-10-10 at 17 27 05" src="https://cloud.githubusercontent.com/assets/235645/19241528/5a19d346-8f0f-11e6-94b9-bc574d476a22.png">


Are you sure you have the latest build of carthage which support xcode8?
If you have both XCode7 and XCode8 you need to properly set the xcode's toolchain to the v.8; from terminal:

```bash
sudo xcode-select -s /Applications/Xcode.app // path to your xcode 8
```

**Comment by nezhyborets** [comment]
I'm sorry, seems that `brew update` helped. I didn't know it could help

**Comment by malcommac** [comment]
np :)
