### ISSUE TITLE
Thread-safe date formatter

### ISSUE THREAD

**Issue by AJ1310** [malcommac/SwiftDate#3]
When handling multiple threads, the shared date formatter can provide a result different than expected due to one thread having a different date_format than another one and being performed at the same time.

**Comment by malcommac** [comment]
I've created a per-thread cache for NSDateFormatter.
It was published with 5d5f25abf6fda25358bb55fe25fbad316fa6801d and available via cocoapods as 1.0.5.
Basically I save and retrive the object from inside the NSThread dictionary; this ensure you to get the instance relative to that thread called only once. It should be enough, tell me if you have problems.

```swift
private class func cachedObjectInCurrentThread<T: AnyObject>(key: String, create: () -> T) -> T {
	if let threadDictionary = NSThread.currentThread().threadDictionary as NSMutableDictionary? {
		if let cachedObject = threadDictionary[key] as! T? {
			return cachedObject
		} else {
			let newObject = create()
			threadDictionary[key] = newObject
			return newObject
		}
	} else {
		assert(false, "Current NSThread dictionary is nil. This should never happens, we will return a new instance of the object on each call")
		return create()
	}
}

private class func localThreadDateFormatter() -> NSDateFormatter {
	return NSDate.cachedObjectInCurrentThread("com.library.swiftdate.dateformatter") {
		let dateFormatter = NSDateFormatter()
		dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
		return dateFormatter
	}
}
```
