### ISSUE TITLE
Date - Date order issue

### ISSUE THREAD

**Issue by fever324** [malcommac/SwiftDate#306]
If we have  (not sure if it will compile, just want to show that D2 is later than D1)
D1 = "1/2/2015"
D2 = "1/2/2016" 

I was expecting D2 - D1 would give me 365 days. But in fact in [code](https://github.com/malcommac/SwiftDate/blob/master/Sources/SwiftDate/Date%2BMath.swift#L106-L107)  we have to use D1 - D2 to get the actual time interval.

Is this intended behavior? 

Thank you!

**Comment by malcommac** [comment]
Hi, you can use ```.in()``` method an specify the ```.day``` as parameter.

```swift
let D1 = try! "1/2/2015".date(format: .custom("dd/MM/yyyy"))
let D2 = try! "1/2/2016".date(format: .custom("dd/MM/yyyy"))
let v = (D2 - D1).in(.day) // 365
```

**Comment by fever324** [comment]
I believe this will crash because [in here](https://github.com/malcommac/SwiftDate/blob/master/Sources/SwiftDate/Date%2BMath.swift#L106-L107) we specifies the lhs is the start of the interval instead of the end of the interval.

Please try run the code above and let me know!

**Comment by malcommac** [comment]
I've tried it right now; do you encounter a crash?

**Comment by fever324** [comment]
Hi @malcommac I tested your code and it works fine.
But I don't understand why using `Date` instead of `SwiftDate.DateInRegion` in the following code crashes
```
let today = Date()
let tomorrow = Date() + 1.days
print(tomorrow - today) // This crashes here
```

**Comment by malcommac** [comment]
I've tried using DateInRegion(), it works fine, in the comments what I get

```swift
let today = DateInRegion()
let tomorrow = DateInRegion() + 1.days
let diffInDays = (tomorrow - today).in(.day) // -> 1
print(tomorrow - today) // -> in seconds = 86400.0012260079
```
Can you post your crash?

**Comment by fever324** [comment]
The problem is that I have to use Date(). 
The crash message is 
```
fatal error: Reverse intervals are not allowed: file /Users/hongfeili/Documents/GitHub/Just Did It/Carthage/Checkouts/SwiftDate/Sources/SwiftDate/DateTimeInterval.swift, line 69
```

I still think the [Date+Math](https://github.com/malcommac/SwiftDate/blob/master/Sources/SwiftDate/Date%2BMath.swift#L106-L107) order should be reversed or consider absolute like how it is done in [DateInRegion+Math](https://github.com/malcommac/SwiftDate/blob/master/Sources/SwiftDate/DateInRegion%2BMath.swift#L82)

Is the order of minus between Dates intended?

**Comment by malcommac** [comment]
Ok should be fixed 👍
