### ISSUE TITLE
Incorrect spelling…

### ISSUE THREAD

**Issue by ryanmaxwell** [malcommac/SwiftDate#313]
Hey, appreciate the pod. Doesn't instil a lot of confidence when the introduction in both your [Readme](https://github.com/malcommac/SwiftDate/blob/master/README.md) and [Documentation](http://malcommac.github.io/SwiftDate/) spell 'probably' incorrectly in different ways! 

Thought i'd point it out so you can correct ;)

**Comment by malcommac** [comment]
Fixed. thanks.
