### ISSUE TITLE
Translations with language+region fails

### ISSUE THREAD

**Issue by tdimeco** [malcommac/SwiftDate#317]
Hi team,

Thank you for your quick fix #314 about missing french translation ;-)

I have another issue with this. The french strings bundle is named `fr.lproj`. SwiftDate targets the folder using the `collatorIdentifier` property of `NSLocale`. On my device, the result is `fr-FR`, so the french translation is not loaded but the english one (`DateInRegionFormatter` line 124).

Even stranger, on another french device (same language and region settings, both on iOS version 10.0.2), the result is `fr` and everything works as expected.

Do you have any solution for that?

Maybe by using `NSLocale.languageCode` which returns `fr` in all cases, but I don't know if it's ok for other languages like chinese ones.

Also, the issue may affects other languages in the bundle.

Thanks!

![French Date Debug](https://cloud.githubusercontent.com/assets/3112087/19652205/3f40eb2a-9a10-11e6-8d25-996a4c56e590.png)

**Comment by rbukovansky** [comment]
Interesting... Following returns `nil` for all 4 on Linux. Any idea, why?
```swift
print("Locale.current.languageCode = \(String(describing: Locale.current.languageCode))")
print("Locale.current.collatorIdentifier = \(String(describing: Locale.current.collatorIdentifier))")
print("NSLocale.current.languageCode = \(String(describing: NSLocale.current.languageCode))")
print("NSLocale.current.collatorIdentifier = \(String(describing: NSLocale.current.collatorIdentifier))")
```

**Comment by rbukovansky** [comment]
BTW I believe those folders with translations should be named after collatorIdentifier, like fr-FR.lproj.
There is i.e. portugal in Portugal (pt-PT) and portugal in Brasil (pt-BR) which can be different in some words. Chinese are having 2 languages as well, Chinese Traditional and Chinese Simplified (and maybe more).
Heck, there is en-GB and en-US (i.e. colour vs. color etc.)...

**Comment by malcommac** [comment]
I think the best solution is, as you said, to use the collatorIdentifier.
i've fixed all folders in order to support this.
As default fallback we will return to en-US.

**Comment by rbukovansky** [comment]
BTW Issue was reported to Swift bugtracking about those `nil` values: https://bugs.swift.org/browse/SR-3202
