### ISSUE TITLE
Translations dosen't work because of collator identifier

### ISSUE THREAD

**Issue by janweinkauff** [malcommac/SwiftDate#318]
I tried to use the german translations on `colloquialSinceNow()` but it always gives me the englisch translation.

As far as I unterstand the approach to select translations is based on the `collatorIdentifier()` . The `collatorIdentifier()` returns the language + region e.g. `de_DE`. But SwiftDate seems to assume that only the language is returned.

But the 'Swift.bundle' only contains a 'de.lproj' directory. 

I would suggest that the assumption that `collatorIdentifier()` only returns the language instead of language + region is not always correct?

See DateInRegionFormatter.swift:124

```
let localeID = locale.collatorIdentifier
guard let innerLanguagePath = self.resourceBundle!.path(forResource: localeID, ofType: "lproj") else {
	// fallback to english if language was not found
	let englishPath = self.resourceBundle!.path(forResource: "en", ofType: "lproj")!
	return Bundle(path: englishPath)
}
return Bundle(path: innerLanguagePath)
```

**Comment by tdimeco** [comment]
Agree, see #317 :)

**Comment by malcommac** [comment]
Duplicate of #317
