### ISSUE TITLE
Missing german translations for "just now" and "%d hours ago"

### ISSUE THREAD

**Issue by janweinkauff** [malcommac/SwiftDate#319]
Proposal:

`de.lproj/SwiftDate.strings`
```
"colloquial_p_hh" = "vor %d Stunden";
"colloquial_now"  = "gerade eben";
```

**Comment by malcommac** [comment]
Just fixed and planned for 4.0.8. Thank you

**Comment by janweinkauff** [comment]
Missing proposed translations in release 4.0.8.

**Comment by malcommac** [comment]
Added in https://github.com/malcommac/SwiftDate/commit/a7c41006ea9425d49f3fa0b0a6a8cbbb266ea77c (4.0.9).
Thanks.
