### ISSUE TITLE
What method should be use in Swift 3.0 instead of the method today() in Swift 2.3

### ISSUE THREAD

**Issue by archerLj** [malcommac/SwiftDate#326]
I am updating my source from swift 2.3 to swift 3.0 today, and there's a method named today() in swift 2.3, used like following:
```
var loanStartDate = NSDate.today() - 20.years
```

and my question is which method should i use to instead of it in swift 3.0?

**Comment by rbukovansky** [comment]
@archerLj The easiest way: NSDate() or Date() should be per API reference enough to get current date and time (you get: 2016-11-09 08:56:34, but not as string, but (NS)Date).

Little bit harder way just to get just current date:
```swift
import Foundation

let dateComponents = Calendar.current.dateComponents([.day, .month, .year], from: Date())
let today: Date? = Calendar.current.date(from: dateComponents)
```

**Comment by akifumi** [comment]
@archerLj 
I think the best way to use `Date().startOfDay`.

**Comment by rbukovansky** [comment]
@akifumi Are you it works? My Xcode says no...

```swift
Playground execution failed: error: Test.playground:1:13: error: value of type 'Date' has no member 'startOfDay'
let today = Date().startOfDay
```

**Comment by akifumi** [comment]
@rbukovansky 
`startOfDay()` method is here.
https://github.com/malcommac/SwiftDate/blob/master/Sources/SwiftDate/Date%2BComponents.swift#L242-L244

**Comment by rbukovansky** [comment]
I see. Sorry! My bad!

**Comment by malcommac** [comment]
The equivalent is:
```swift
let d = Date().startOf(component: .day) - 20.years
```
