### ISSUE TITLE
Option to remove "about" in toRelativeString()

### ISSUE THREAD

**Issue by agquick** [malcommac/SwiftDate#33]
Should be a way to opt out of having "about" in result of toRelativeString(), especially when the abbreviated option is true.

**Comment by adwayish** [comment]
+1 also get rid of "ago". These are application specific so users can add them if they want.

**Comment by malcommac** [comment]
Okay I've temporary disabled it, seems legitimate.

**Comment by MarvinNazari** [comment]
Are u gonna push to Cocoapods for this?
