### ISSUE TITLE
Parsing ISO8601 strings with milliseconds

### ISSUE THREAD

**Issue by joachimboggild** [malcommac/SwiftDate#333]
Hi,

Thanks for a very nice component :-)

I am trying to create a date from an ISO8601 string that looks like this:
`2016-11-10T07:58:35.566Z`.

I get errors when the time string contains milliseconds. Is it possible to configure SwiftDate to parse a string that contains milliseconds?

**Comment by malcommac** [comment]
Try `withInternetDateTimeExtended`:

```swift
let format = try! str.date(format: .iso8601(options: .withInternetDateTimeExtended))
```
