### ISSUE TITLE
sd_localizedString always returns ""

### ISSUE THREAD

**Issue by mark-anders** [malcommac/SwiftDate#336]
I'm using the Swift 2.3 branch, installed via Carthage and when calling toString( style: .Colloquial), I'm always getting a blank string.  I traced it down to sd_localizedString and loading the frameworkBundle fails:

        guard let frameworkBundle = NSBundle(identifier: "com.danielemagutti.SwiftDate") else {
            return ""
        }

Other than adding the following to my Cartfile and adding it as I do with other Carthage frameworks, is there anything I need to do?

       github "malcommac/SwiftDate" "feature/swift_23"

**Comment by malcommac** [comment]
I'm sorry but I've not enough time to maintain the old 2.3 branch. I've focused on 3+. However I'll be happy to integrate any sort of PR about bug fixing.
Thanks.
