### ISSUE TITLE
Express DateComponents in other time units (ex. x.seconds.in(.minute))

### ISSUE THREAD

**Issue by leojkwan** [malcommac/SwiftDate#337]
Is this still a feature? 120.seconds.in(.minutes)?

**Comment by malcommac** [comment]
Yeah it will be available since 4.0.8 (this commit https://github.com/malcommac/SwiftDate/commit/6855337fd49792f309a56ab05b45401908593f34):

The signature is:
```swift
public func `in`(_ component: Calendar.Component, of calendar: CalendarName? = nil) -> Int?
```

Your example:
```swift
let x = 120.seconds.in(.minute)
```
