### ISSUE TITLE
compare() func return wrong result comparing using .nanosecond as granularity

### ISSUE THREAD

**Issue by cikpis** [malcommac/SwiftDate#346]
As the title, I'm trying the follow code:
`date_1.isAfter(NSCalendarUnit.Nanosecond, ofDate: date_2)`

between the following dates:
`2016-11-18T16:20:12.311Z - 2016-11-18T16:20:12.212Z`

I got a false such as result. Any clue?

**Comment by malcommac** [comment]
Just for completeness that's the code for SwiftDate:

```swift
let date1 = try! "2016-11-18T16:20:12.311Z".date(format: .iso8601(options: .withInternetDateTimeExtended))
let date2 = try! "2016-11-18T16:20:12.212Z".date(format: .iso8601(options: .withInternetDateTimeExtended))
let is1After2 = date1.isAfter(date: date2, granularity: .nanosecond) // return false
```

```
(lldb) po date.absoluteDate
▿ 2016-11-18 16:20:12 +0000
  - timeIntervalSinceReferenceDate : 501178812.21199989


(lldb) po self.absoluteDate
▿ 2016-11-18 16:20:12 +0000
  - timeIntervalSinceReferenceDate : 501178812.31100011
```

According to [NSDate](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/DatesAndTimes/Articles/dtDates.html) documentation:
```"[NSDate] ... makes possible a wide and fine-grained range of date and time values, giving precision within milliseconds for dates 10,000 years apart [...]"```

So I think it's a rounding error (even if comparing two dates using Calendar and nanosecond seems a bit weird).
I've just added a workaround (planned for 4.0.8) you can found here:
https://github.com/malcommac/SwiftDate/commit/7edca0338fa5948c349e64f63344c8dc6e93fd27

**Comment by cikpis** [comment]
Cool! Thanks man!

**Comment by cikpis** [comment]
BTW, do you know already the date for 4.0.8?

**Comment by malcommac** [comment]
If it's all okay I plan to release it later tomorrow (dec. 1)
