### ISSUE TITLE
PM/AM Formatting not working correctly

### ISSUE THREAD

**Issue by OliverZiegler** [malcommac/SwiftDate#349]
When changing your iPhone settings to 12 hour format and trying to get an iso date string, the string is not right.

Trying to parse an PM date the resulting output is an AM date

    Printing description of gmtTimeDate: 30.11.2016, 10:00:00 PM GMT

    gmtTimeDate.string(format: .iso8601(options: [.withInternetDateTime]))
    "2016-11-30T10:00:00Z"

Is there anything I do wrong or is this a bug in SwiftDate.

My recent Settings of Date&Time are:
24-hours: off
automatic timezone: on
Timezone: Berlin

**Edit:**
Probably this is unexpected behaviour of NSDateFormater as you can see [here](http://touchwonders.com/blog/12-hour-clock)

**Comment by malcommac** [comment]
Hi,
In order to parse correctly a 12h clock you need to use `hh` in place of `HH` for hour.
Based upon your string I suggest you to use a custom formatter:

Below an example:

```swift
let str = "30.11.2016, 10:00:00 PM GMT"
let date = try! str.date(format: .custom("dd.MM.yyyy',' hh:mm:ss a ZZZZ")) // 30 nov 2016, 23:00:00 CET
```

It will return `30 nov 2016, 23:00:00 CET` as you need.
More on formatting options are [available here](http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns)

**Comment by OliverZiegler** [comment]
Unfortunately this won't solve my problem.

I need to parse a given date to the right ISO8601 String which won't happen if your device is on 12 hour mode.

If I create a Date with `Date()` or `DateInRegion()` and current time for example 10:00 PM or 22:00 the resulting ISO8601 string after formatting will be: `2016-11-30T10:00:00Z` which is not the correct ISO8601 string.

Using following code will give me the right ISO8601 String for my date:

    let region = Region(tz: TimeZoneName.gmt, cal: CalendarName.current, loc: LocaleName.englishUnitedStatesComputer)
    let gmtDate = DateInRegion(absoluteDate:Date(), in: region)
    let gmtTimeDate = try! gmtDate.atTime(hour: newValue.hour, minute: newValue.minute, second: newValue.second)
    let string = gmtTimeDate.string(format: .iso8601(options: [.withInternetDateTime]))
    print(string)

So prints out `2016-11-30T22:00:00Z`

But trying to parse this string back to a `Date` or `DateInRegion` this won't work, so `try "2016-11-30T22:00:00Z".date(format: .iso8601(options: [.withInternetDateTime]))` will raise an exception.

As ISO8601 is strictly defined I think this is very unexpected behaviour and should be fixed.

**Comment by malcommac** [comment]
I think you are right, we should set en_US_POSIX manually.
Added for 4.0.9.

**Comment by malcommac** [comment]
Just for reference, this is the official statement from Apple regarding [NSDateFormatter and Internet Date&Time](https://developer.apple.com/library/content/qa/qa1480/_index.html)
