### ISSUE TITLE
SwiftDate on Linux

### ISSUE THREAD

**Issue by rbukovansky** [malcommac/SwiftDate#352]
I'm trying to compile SwiftDate on Linux using latest DEV snapshot of Swift, but I'm getting these issues:

```
/home/rbukovansky/Projects/SwiftDate/Sources/SwiftDate/DateInRegionFormatter.swift:252:93: error: contextual type 'CVarArg' cannot be used with array literal
                                let colloquial_date = try self.stringLocalized(identifier: "colloquial_now", arguments: [])
                                                                                                                        ^~
/home/rbukovansky/Projects/SwiftDate/Sources/SwiftDate/DateInRegionFormatter.swift:261:92: error: contextual type 'CVarArg' cannot be used with array literal
                        let colloquial_date = try self.stringLocalized(identifier: "colloquial_now", arguments: [])
                                                                                                                ^~
/home/rbukovansky/Projects/SwiftDate/Sources/SwiftDate/DateInRegionFormatter.swift:284:28: error: use of unresolved identifier 'NSLocalizedString'
                let relative_localized = NSLocalizedString(id_relative,
                                         ^~~~~~~~~~~~~~~~~
/home/rbukovansky/Projects/SwiftDate/Sources/SwiftDate/DateInRegionFormatter.swift:315:20: error: use of unresolved identifier 'NSLocalizedString'
                        let localized = NSLocalizedString(identifier, tableName: "SwiftDate", bundle: bundle, value: "", comment: "")
                                        ^~~~~~~~~~~~~~~~~
/home/rbukovansky/Projects/SwiftDate/Sources/SwiftDate/DateInRegionFormatter.swift:333:23: error: use of unresolved identifier 'NSLocalizedString'
                var localized_str = NSLocalizedString(identifier, tableName: "SwiftDate", bundle: bundle, comment: "")
                                    ^~~~~~~~~~~~~~~~~
/home/rbukovansky/Projects/SwiftDate/Sources/SwiftDate/Extensions.swift:59:18: error: value of type 'TextCheckingResult' has no member 'rangeAt'
                        let msRange = match.rangeAt(1)
                                      ^~~~~ ~~~~~~~
Foundation.TextCheckingResult:9:14: note: did you mean 'range'?
    open var range: Foundation.NSRange { get }
             ^
Foundation.TextCheckingResult:10:15: note: did you mean 'range'?
    open func range(at idx: Int) -> Foundation.NSRange
              ^
/home/rbukovansky/Projects/SwiftDate/Sources/SwiftDate/Region.swift:98:21: error: type 'Locale' has no member 'autoupdatingCurrent'
                let loc = (auto ? Locale.autoupdatingCurrent : Locale.current)
                                  ^~~~~~ ~~~~~~~~~~~~~~~~~~~
/home/rbukovansky/Projects/SwiftDate/Sources/SwiftDate/LocaleName.swift:42:11: error: type 'Locale' has no member 'autoupdatingCurrent'
                        return Locale.autoupdatingCurrent
                               ^~~~~~ ~~~~~~~~~~~~~~~~~~~
```

One thing is for sure, on Linux there isn't NSLocalizedString() available as Swift for Linux doesn't know how to pack built code and resources together (yet!). Is there any solution that can replace NSLocalizedString()?

The rest, which I'm not sure about, is probably you should take a look. If not, I will take over and will create a PR where I try to resolve it. Thanks.

**Comment by Casperhr** [comment]
Dump here! Could be awesome to see this lib work on Linux

**Comment by malcommac** [comment]
Looking at Swift foundation library I can see that calendar/locale traking was not implemented yet (see for example [here](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSCalendar.swift#L205)).
BTW we can use `current` variant.

My only other concern is about localizable strings. As far I know there is not any support for bundles in linux (am I wrong?) so the only alternative I know is to use a classic folder with all variants and read from it based upon locale.
Any other suggestion?

**Comment by rbukovansky** [comment]
@malcommac They are not (yet). That's one way how to do that, but I don't like it (GoLang is able to have binary with all resources on Linux), so I hope that Swift will be able to do that too.

I was thinking more about generating file with dictionaries with translations and some function that will replace NSLocalizedString.

**Comment by malcommac** [comment]
Since 4.0.12 SwiftDate allows to load a custom localization `.strings` file in `DateInRegionFormatter`.
More on #380.
The next step will include conditional compiling for `autoupdating` `Locale` and `Calendar` and the replacement of NSLocalizableString call on Linux inside `Localization`.
I'll do it later the next week.

**Comment by crarau** [comment]
Any news on this. I read this on the main webpage and started implementing it, just to notice that it doesn't work
`It works on iOS, macOS, watchOS, tvOS and virtually on any Swift compatible platform (yeah Linux too!).`

**Comment by malcommac** [comment]
Follow #568
