### ISSUE TITLE
Make timezone, calendar and locale public in Region

### ISSUE THREAD

**Issue by TadeasKriz** [malcommac/SwiftDate#353]
Right now they are internal and cannot be accessed. I'd like to use them to setup UIDatePicker's timezone and locale since I have "DateInRegion" instance.

Does this make sense? Or should I do it differently?

Thanks!

**Comment by malcommac** [comment]
Yeah you are right.
[Added here](https://github.com/malcommac/SwiftDate/commit/529738ed1ca9461d95430c134a87fde3ac313ff2), it will be available since 4.0.9.
Thanks
