### ISSUE TITLE
Vietnamese translation

### ISSUE THREAD

**Issue by solbadguyky** [malcommac/SwiftDate#354]
I want to use Colloquial String in colloquialSinceNow() in Vietnamese, so how can I do that? Thank you
Ive searched but I just found the only way to do is commit my language bundle, right?

**Comment by malcommac** [comment]
Hi @solbadguyky,
Yeah you can make a PR with the bundle.
You can also paste here the translation of [this file](https://github.com/malcommac/SwiftDate/blob/master/Sources/SwiftDate/SwiftDate.bundle/en-US.lproj/SwiftDate.strings) in your language (be sure to mantain the format strings `%d` and translate the `month/year/day` formats according to your locale). I'll add it for you into the next release.

**Comment by solbadguyky** [comment]
[SwiftDate.strings.zip](https://github.com/malcommac/SwiftDate/files/629097/SwiftDate.strings.zip)
Here my translated SwiftDate.strings file. Thank for your help :)

**Comment by malcommac** [comment]
Added and scheduled for 4.0.9. [commit](https://github.com/malcommac/SwiftDate/commit/3a641f154ac6966c1a7aa99ede801d78c1a7db01)
Thank you!
