### ISSUE TITLE
Disable heuristics date guessing inside the formatter

### ISSUE THREAD

**Issue by JGCR** [malcommac/SwiftDate#356]
I'm using SwiftDate to validate string dates, but I find that it accepts as valid the 31st of ANY month (Feb, Nov, whatever). The 32nd of any month fails on a SwiftDate.DateError.FailedToParse.

The following is taken from an example on the SwiftDate GitHub page (I changed the date). 

```swift
let regionRome = Region(tz: TimeZoneName.europeRome, cal: CalendarName.gregorian, loc: LocaleName.italian) 
// Parse a string which a custom format 
let date1 = try! DateInRegion(string: "1999-02-31 23:30:00", format: .custom("yyyy-MM-dd HH:mm:ss"), fromRegion: regionRome)
print(date1) //Gives '03 mar 1999, 23:30:00 CET'
```

Am I overlooking something? I assume this result isn't intended.

**Comment by malcommac** [comment]
Hi,
I've made several test and actually I'm able to reproduce this "issue" even with plain `DateFormatter`:

```swift
var str = "1999-02-31 23:30:00"
var f = DateFormatter()
f.dateFormat = "yyyy-MM-dd HH:mm:ss"
f.locale = LocaleName.italian.locale
//f.calendar = CalendarName.gregorian.calendar // if you set the calendar 31/02 is adjusted to the 03/03
f.timeZone = TimeZoneName.europeRome.timeZone
let parsedString = f.date(from: str)
```

`parsedString` is `nil` if does not set the calendar object; once you have set it the date is 'magically' parsed.

**Comment by JGCR** [comment]
Hi, thanks for going to the trouble of following-up on this. The DateFormatter problem can also be solved by using “f.isLenient = false”. I’m using DatePicker these days for date inputs, BUT I’m using SwiftDate for many other requirements. It’s great.
Thanks again, John Reid.

**Comment by malcommac** [comment]
Cool, great find!
I will add ```isLenient``` as property of the formatter later into the next minor release.

**Comment by malcommac** [comment]
In order to avoid API breaking changes I've added a new formatter option called `strict`.
When you use `strict` instead of `custom` heuristics guessing of the date is disabled and invalid date still remains invalid.

This is the reference commit:
https://github.com/malcommac/SwiftDate/commit/5ede1940500ee3ef89ee5932a369ca569ead9b2e

**Comment by adrianodiasx93** [comment]
@malcommac Shouldn't isLenient be set to `false` to achieve the behaviour mentioned by @JGCR ?

https://github.com/malcommac/SwiftDate/blob/9608361b6a7ee726b12a9d40a29a4614faec12fb/Sources/SwiftDate/Formatters/Formatter%2BProtocols.swift#L120

**Comment by adrianodiasx93** [comment]
If that's really the case, I have opened a PR. #629

**Comment by malcommac** [comment]
You're right @adrianodiasx93
