### ISSUE TITLE
Colloquial & ColloquialSinceNow issues

### ISSUE THREAD

**Issue by xeo-it** [malcommac/SwiftDate#359]
Hey there, I believe there are still a couple of issues in Colloquial and ColloquialSinceNow.  
Given the following code:  

```swift
let future = Date().add(components: 8.minutes)
let futureStringOne = try future.colloquialSinceNow().colloquial
let futureStringTwo = try Date().colloquial(to: future,  max: 1 ).colloquial
```

- `futureStringOne` outputs  `just now`
- `futureStringTwo` outputs `8 minutes ago`.
I would expect both string to be `in 8 minutes`.

Also, all the parameters passed in colloquialSinceNow are ignored, it will always return the same string no matter what other parameters I pass in the function.

I'm using version 4.0.8.  
Thanks

**Comment by xeo-it** [comment]
I realized I might have called colloquial with inverted date, but when calling it this way:  

`let futureStringTwo = try future.colloquial(to: Date(), max: 1 ).colloquial`  

it also returns just now.  
I can't find a way to write future dates if the interval is less than 1 hour.

**Comment by malcommac** [comment]
Hi,
Okay that's clearly a bug; when gap between two dates is expressed in minutes the value in your example is -8 and -8 < 5 minutes, so it's wrong perceived in "just now" case.
I've solved it in this commit https://github.com/malcommac/SwiftDate/commit/88067f1485391558acf5b44a515d568630519703. You will found it in 4.0.9 upcoming release.
Thank you
