### ISSUE TITLE
iTunes Connect rejects builds with SwiftDate 4.0.9 

### ISSUE THREAD

**Issue by darrarski** [malcommac/SwiftDate#364]
When submitting an app to iTunes Connect (for TestFlight or AppStore distribution) with SwiftDate 4.0.9 integrated via Cocoapods 1.1.1, the app gets rejected. Rejection reason:

> Unrecognized Locale - The directory located at ('Payload/MyApp.app/Frameworks/SwiftDate.framework/SwiftDate.bundle/jp-JP.lproj' ) has an unrecognized locale name. Refer to the [Language and Locale Designations](https://developer.apple.com/library/ios/#documentation/MacOSX/Conceptual/BPInternational/Articles/LanguageDesignations.html%23//apple_ref/doc/uid/20002144-SW3) guide for more information on naming your language-specific directories.

When using version 4.0.8 everything seams to be fine (no rejection emails, app working correctly).

**Comment by malcommac** [comment]
It should be `ja-JP`. Fixed in https://github.com/malcommac/SwiftDate/commit/9d72d1072b0e574f74f152db880e1b6d3bc87731
I'll release it in 4.0.10 right now.

**Comment by darrarski** [comment]
👍

**Comment by malcommac** [comment]
Can you make a test? It should be available on cocoapods

**Comment by darrarski** [comment]
Looks like problem is solved in 4.0.10. Thanks!

**Comment by malcommac** [comment]
Thank you for your report!

[Daniele Margutti - Contact Using Hop](http://GetHop.com/?_hmid=1482335488)

On December 21, 2016 at 15:49 GMT, Dariusz Rybicki <notifications@github.com> wrote:

Closed [#364](https://github.com/malcommac/SwiftDate/issues/364).
