### ISSUE TITLE
Can't set year in the past

### ISSUE THREAD

**Issue by twiedow** [malcommac/SwiftDate#368]
I have a question if this is a bug or a feature:

I want to change the date of a Date object which is in the past January 1st 1900. This manipulation fails with SwiftDate because an error is thrown. The cause of the problem is that calling Calendar.current.date(bySetting:value:of:) returns a nil value when setting the .year component to a year in the past.

Do you know if this the desired behaviour or if this is just a bug?

Here is a snippet to be used in a playground:

```swift
let now = Date()

// is nil because a FailedToSetComponent error is thrown
let min = try? now.at(unitsWithValues: [.year: 1900, .month: 1, .day: 1])

// is nil as well
let dateyear = Calendar.current.date(bySetting: .year, value: 2015, of: now)

// returns a value
let dateyear2 = Calendar.current.date(bySetting: .year, value: 2017, of: now)
```

**Comment by cruisediary** [comment]
+1

**Comment by malcommac** [comment]
Hi,
There is a problem with that func which prevents settings multiple components by keeping the old values while generating a valid date.
Since 4.1.0 both in `Date` and `DateInRegion`:
```swift
 public func at(unitsWithValues dict: [Calendar.Component : Int]) throws -> DateInRegion
 public func at(unitsWithValues dict: [Calendar.Component : Int]) throws -> Date
```

are deprecated.
Replacement functions are:

``` swift
public func at(values: [Calendar.Component : Int], keep: Set<Calendar.Component>) -> DateInRegion?
public func at(values: [Calendar.Component : Int], keep: Set<Calendar.Component>) -> Date?
```

Both of them allows you to specify:
- a set of components,values which alter the instance of the date
- a set of components values which must copied from self instance to the new instance

So your func become:

```swift
let now = Date() // 2017-03-31 17:32:42 +0000
		
let d1 = DateInRegion(absoluteDate: now, in: Region.GMT())
print("d1: \(d1)") // Mar 31, 2017, 5:32:42 PM GMT

let d2 = d1.at(values: [.year: 1900, .month: 1, .day: 1], keep: [.hour, .minute, .second])!
print("d2: \(d2)") // Jan 1, 1900, 5:32:42 PM GMT

// or, if you don't need to keep time values...
let d3 = DateInRegion(components: [.year: 1900, .month: 1, .day: 1], fromRegion: Region.GMT())!
print("d3: \(d3)") // Jan 1, 1900, 12:00:00 AM GMT
```
