### ISSUE TITLE
How config Formatter to show `today`, `yesterday`, `%d days ago`?

### ISSUE THREAD

**Issue by Lyfeway** [malcommac/SwiftDate#373]
I read the source code, 
```Swift
DateInRegionFormatter.colloquial(from fDate: DateInRegion, to tDate: DateInRegion)
```
still can't figure out how to use `colloquialSinceNow()` function to format by nature daily, like: 
```
`today`, `yesterday`, `%d days ago`
```

Is there configrable? Thank you.

**Comment by malcommac** [comment]
You should set allowedComponents to day in order to avoid formatting with lower time components.
Cannot try it right now but it should be:

```swift
let fmt = DateInRegionFormatter()
fmt.allowedComponents = [.day]
let formatted = try fmt.colloquial(from: fromDate, to: toDate).colloquial 
```

**Comment by Lyfeway** [comment]
It works. Thank you so much.
