### ISSUE TITLE
There is no way to get local timezone date?

### ISSUE THREAD

**Issue by kidsid-Ixigo** [malcommac/SwiftDate#378]
I have a timestamp and I want to convert into local date object in swift. I tried using swiftDate date extension like this:

`Date(timeIntervalSince1970: value!/1000).inLocalRegion()`
 Which returns DateInRegion object, but there is no way to get local date object out of it :(

**Comment by malcommac** [comment]
If you want to get absolute `Date` object adjusted to the local region offset you can use `.absoluteDate` property.
