### ISSUE TITLE
Replace useImminentInterval property with a configurable value in DateInRegionFormatter

### ISSUE THREAD

**Issue by kevinrenskers** [malcommac/SwiftDate#381]
At the moment the colloquial string is `just now` when the difference between the 2 dates is less then 5 minutes. For a project that I am working on, I need this cut off to be only one minute. Would it be possible to make this configurable instead of having it hardcoded to 5 minutes?

**Comment by malcommac** [comment]
Hi,
Great addition; I've replaced old `useImminentInterval` with `useImminentInterval` which defines an optional `Int`:
- if `useImminentInterval = nil` fallback is not supported. `just now` fallback is never printed
- if `useImminentInterval = <value>` where `value` must be an Int between `1...60` (not included). if differences between two dates is lower than `value` then the `just now` fallback string is printed

By default `useImminentInterval = 5` which means fallback is active with differences lower than 5 minutes.

Changes will be available in 4.0.12.
This is the reference commit: https://github.com/malcommac/SwiftDate/commit/5ad817a5ae0cdf9e71cf599ad96becc1572545b7

**Comment by kevinrenskers** [comment]
Awesome! Thanks.
