### ISSUE TITLE
toDate() has changed

### ISSUE THREAD

**Issue by szuniverse** [malcommac/SwiftDate#383]
Hi 
I had this code in swift2.3:

```
if let date = dateString.toDate(DateFormat.Custom("yyyy-MM-dd")) {
    //code
}
```

But in swift 3.0 the toDate() method has dissapeared, how can I do the same with the latest SwiftDate version?

**Comment by malcommac** [comment]
Hi @szuniverse,
You, it was renamed to `date()`:

```swift
do {
  let parsedDate = try "".date(format: .custom("yyyy-MM-dd"))
} catch {
  ...
}

// or, if you want to force try
let parsedDate = try! "".date(format: .custom("yyyy-MM-dd"))
```

**Comment by szuniverse** [comment]
thank you. and after that I have another question the old date() function's return type was Date but now it is DateInRegion. If I use the absoluteDate property is it the same as before?

**Comment by malcommac** [comment]
Right, it's the same property and return the absolute time from `DateInRegion` which is not dependent from the timezone.

**Comment by szuniverse** [comment]
Thanks a lot! :)
