### ISSUE TITLE
'-' overload for Date

### ISSUE THREAD

**Issue by gtsifrikas** [malcommac/SwiftDate#387]
Hello,
I noticed when i use - to find the duration between two dates if for example we have, x - y where x > y it gives a negative result. 
Wouldn't expect, given that x > y, to be positive?

**Comment by malcommac** [comment]
Thank you. Just fixed it in 4.1.0.
Reference commit is https://github.com/malcommac/SwiftDate/commit/0c23cb8adba2a3c2ef3716b9df8e75533be365de
