### ISSUE TITLE
weekday in spanish region is not correct

### ISSUE THREAD

**Issue by lolohouse** [malcommac/SwiftDate#390]
date.weekday != DateFormatter.dateFormat = "e"
In Spanish region

date(26-02-2017)
date.weekday -> 1 "Monday" in English is correct in Spanish not
DateFormatter.dateFormat = "e" -> 7 "Sunday" in spanish

since 
date.montname -> "Febrero" is correct in Spanish

**Comment by malcommac** [comment]
If you want to get the name in the locale you need to set the locale in region.
That's an example with GMT region but with locale in Italian and Spanish:

```swift
let region_it = Region(tz: TimeZoneName.gmt, cal: CalendarName.gregorian, loc: LocaleName.italianItaly)
let region_es = Region(tz: TimeZoneName.gmt, cal: CalendarName.gregorian, loc: LocaleName.spanishSpain)
		
let d1 = "26-02-2017".date(format: .custom("dd-MM-yyyy"), fromRegion: region_it)!
print("Weekday: \(d1.weekday), Name: \(d1.weekdayName)") // Weekday: 1, Name: domenica

let d2 = "26-02-2017".date(format: .custom("dd-MM-yyyy"), fromRegion: region_es)!
print("Weekday: \(d2.weekday), Name: \(d2.weekdayName)") // Weekday: 1, Name: domingo
```
