### ISSUE TITLE
weekOfYear in 12-31 result = 1

### ISSUE THREAD

**Issue by lolohouse** [malcommac/SwiftDate#391]
for date : ▿ 2014-12-30 23:00:00 +0000
  - timeIntervalSinceReferenceDate : 441673200.0
date.weekOfYear -> 1

since in 2013-12-30  the result is 53 is Ok

but 2014 the result is 1 ¿?
in region Spanish for ios 10.2

**Comment by malcommac** [comment]
`2014/12/30 <-> 2015/01/04` is week 1 (see https://www.epochconverter.com/weeks/2014)
Also `2013/12/30` <-> `2015/01/05` is week 1 (see https://www.epochconverter.com/weeks/2013)

Also if I try with SwiftDate the result for both of them is 1.
That's the code:

```swift
let d1 = "2014-12-30 23:00:00".date(format: .custom("yyyy-MM-dd HH:mm:ss"), fromRegion: Region.GMT())!
print(d1.weekOfYear) // 1

let d2 = "2013-12-30 23:00:00".date(format: .custom("yyyy-MM-dd HH:mm:ss"), fromRegion: Region.GMT())!
print(d2.weekOfYear) // 1
```

**Comment by TimeDelta** [comment]
@malcommac Thanks for the explanation. I ran into this same thing and also thought it was a bug.
