### ISSUE TITLE
Difference between two dates reversed?

### ISSUE THREAD

**Issue by innovative1** [malcommac/SwiftDate#392]
In arithmetic, if a and b are numbers, `a - b < 0 iff a < b`

I would think that when subtracting dates, this relationship would hold true since they can be represented as numbers. The reverse is however true: 

    let now = Date()
    let futureDate = now + 1.days
    futureDate - now        // this is negative

This is very counterintuitive, since the result is the opposite of regular arithmetic. And is especially confusing when the result of this is positive:
    
    futureDate.timeIntervalSinceReferenceDate - now.timeIntervalSinceReferenceDate

 Is there a reason for this behaviour?

**Comment by techno246** [comment]
I encountered this issue when running on iOS 9, but not when I ran it on the simulator which runs iOS 10. Can you please confirm which iOS version you are testing this on? 

I have had to use .absoluteDate.timeIntervalSince(....) to maintain compatibility with iOS 9 so far...

**Comment by malcommac** [comment]
Yeah that's right; I've fixed it in 4.1.0.
Reference commit is https://github.com/malcommac/SwiftDate/commit/0c23cb8adba2a3c2ef3716b9df8e75533be365de
