### ISSUE TITLE
toRelativeString fails on ios 8 / swift 1.2

### ISSUE THREAD

**Issue by chrissancho** [malcommac/SwiftDate#4]
toRelativeString returns an unexpected value on devices running iOS 8+

This seems to be the offending line:

```
let unitList : [String] = ["year", "month", "week", "day", "hour", "minute", "second"]
```

This is likely due to the deprecation of the "week" property for NSDateComponents.

https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/NSDateComponents_Class/index.html

Changing to "weekOfYear" seems to have fixed things, but a nice check would be good to have in place to cover all bases and have a more reliable backwards compatibility.

**Comment by malcommac** [comment]
I plan to set the minimum req for SwiftDate to iOS8+, so your fix should be enough.
