### ISSUE TITLE
Austrian/Swiss Support (German)

### ISSUE THREAD

**Issue by Dandiccf** [malcommac/SwiftDate#406]
Hi there, I love your library, there is just one thing I would ask you to fix.

There are 3 countries with german language (Germany, Austria and Swiss) but you just provide the "Germany"-version (de-DE). Here in Austria this version perfectly fits too, so I would kindly ask you to change the folder name in the SwiftDate.bundle from de-DE.lproj to de.lproj, or just duplicate the file to de-AT.lproj.

thx a lot

**Comment by malcommac** [comment]
I've added a `de-AT.lproj` which basically is a clone of `de-DE.lproj`

**Comment by Dandiccf** [comment]
thx - works great
