### ISSUE TITLE
"yesterday" bug with colloquial when difference between two dates > 24 but < 48 hours

### ISSUE THREAD

**Issue by eastsss** [malcommac/SwiftDate#409]
#397  still doesn't work :( sorry, probably my explanations were bad. Please take a look at this example
```
let to = Date()
let from = Date(timeIntervalSince1970: to.timeIntervalSince1970 - 47 * 60 * 60)
        
let fromDate = DateInRegion(absoluteDate: from, in: nil)
let toDate = DateInRegion(absoluteDate: to, in: fromDate.region)
let formatter = DateInRegionFormatter()
formatter.localization = Localization(locale: fromDate.region.locale)
formatter.imminentInterval = 1
let col = try! formatter.colloquial(from: fromDate, to: toDate).colloquial
        
print("col = \(col)")
```

`from = 2017-04-01 15:07:52 UTC`
`to = 2017-04-03 14:07:52 UTC`

shows
> yesterday

so basically if **difference between two dates more(!) than 24 hours**, but less than 48 hours, and its **not two consecutive days** it still shows "yesterday"

P.S. sorry i don't know how to change status on issue #397 so i created this one

**Comment by malcommac** [comment]
Thank you, just closed for 4.1.1
