### ISSUE TITLE
Parse String using toDate(formatString: ) is incorrect

### ISSUE THREAD

**Issue by harryworld** [malcommac/SwiftDate#42]
The example in README `let date = "22/01/2015".toDate(formatString: "DD/MM/YYYY")` will parse to `Optional(2014-12-20 16:00:00 +0000)`

**Comment by malcommac** [comment]
According to Apple date formatting doc (you can see at the bottom of the readme file) day should be "dd" not "DD".

**Comment by harryworld** [comment]
I found out already, it should be `dd/MM/yyyy` in order to parse correctly.

Please correct this in README.

Thanks.

**Comment by malcommac** [comment]
Just fixed, thank you
