### ISSUE TITLE
String of format "HH:mm:ss" is parsed as a date (since version 4.1.1)

### ISSUE THREAD

**Issue by andrew-frank** [malcommac/SwiftDate#421]
Hey,

I believe time formatting has been broken in the latest version ( 4.1.1 ). We're using `SwiftDate` to format also time strings and it was fine in the previous versions. Now it tries to read String in format `HH:mm:ss` as a date instead of time.

A sample code:
```
let formatter = DateFormat.iso8601(options: .withTime)
let timeFrom = "15:00:00"
let timeTo = "22:00:00"
if let timeStartInRegion = timeFrom.date(format: formatter), let timeEndInRegion = timeTo.date(format: formatter) {
    let timeStartDate = timeStartInRegion.absoluteDate
    let timeEndDate = timeEndInRegion.absoluteDate
    let timeStart : String = timeStartDate.string(dateStyle: .full, timeStyle: .full, in: nil)
    let timeEnd : String = timeEndDate.string(dateStyle: .full, timeStyle: .full, in: nil)
    print(" start: \(timeStart) \n end: \(timeEnd)")
}
```
... and the console prints:

1) for `timeFrom = "15:00:00"` and `timeTo = "22:00:00"` :
```
start: Sunday, December 31, 1516 at 11:58:45 PM GMT-00:01:15
end: Wednesday, January 1, 2217 at 12:00:00 AM Greenwich Mean Time
```
2) for `timeFrom = "08:00:00"` and `timeTo = "13:00:00"` :
```
start: Saturday, December 31, 816 at 11:58:45 PM GMT-00:01:15
end: Thursday, December 31, 1316 at 11:58:45 PM GMT-00:01:15
```

Note the years:
- for `15:00:00` it's `1516`
- for `22:00:00` it's `2217`
- for `08:00:00` it's `816`
- for `13:00:00` it's `1316`

😄 

Was there support for Strings containing Time only in previous versions? Or only Dates (optionally with Time added to them) were supported and it just happened to work for me in previous versions?

Thanks

**Comment by malcommac** [comment]
New introduced ISO8601 parser assumes current year/month/day if no date portion is specified.
I've tried with 4.1.2 and it seems to work fine:

```
(lldb) po timeStartInRegion
May 8, 2017, 3:00:00 PM GMT


(lldb) po timeEndInRegion
May 8, 2017, 10:00:00 PM GMT
```

While the output is converted in `Region.Local()` because you are passing a `nil` timezone. Can you repeat the test with 4.1.2 fork?

**Comment by malcommac** [comment]
Any news?
