### ISSUE TITLE
Do you have a plan that adds the feature about "time ago"?

### ISSUE THREAD

**Issue by muukii** [malcommac/SwiftDate#422]
like this, https://github.com/kevinlawler/NSDate-TimeAgo

**Comment by malcommac** [comment]
Have you tried `colloquial` func and `DateInRegionFormatter`?. Should accomplish what you are searching for.

**Comment by muukii** [comment]
I would like to get formats following.

- `now`
- `30s ago`
- `1m ago`
- `1years ago`

Can I get it?
I think that would need some localization bundles.

**Comment by malcommac** [comment]
Take a look at colloquial functions, it returns what you are searching for. If your language is not part of the current set you may help us to support it. Also take a look at unit tests for concrete examples.
Thank you!
