### ISSUE TITLE
StartWeek and Region

### ISSUE THREAD

**Issue by Arnoymous** [malcommac/SwiftDate#423]
I'm French and I try to create a calendar with **.startWeek**? 
When I set the simulator region on US, the first day of a week is **Sunday**, but in France the first day is **Monday**.
I have tried to play with 
`let region = Region(tz: .europeParis, cal: .gregorian, loc: .frenchFrance)
Date.setDefaultRegion(region)`
but Date().startWeek.day is a **Sunday** :(
how can i get a **startWeek** -> **Monday** for all region ?

Exemple the startWeek of May 4 is, in France May 1 (Monday), but in us April 30 (Sunday)

**Comment by malcommac** [comment]
You must modify `Calendar`'s `firstWeekday` property.
However since 4.1.2 there is a `firstWeekday` property directly inside the `Region` struct.
That's an example from tests:

```swift
var region = Region(tz: TimeZoneName.europeParis, cal: CalendarName.gregorian, loc: LocaleName.frenchFrance)
		region.firstWeekday = .monday
		let new_date = DateInRegion(absoluteDate: Date(), in: region)
		XCTAssertEqual("lundi", new_date.startWeek.weekdayName, "Failed to set the firstWeekday for a Region")
```

Thank you for your report!
D.
