### ISSUE TITLE
Issue with Date.dates(between:and:increment) method

### ISSUE THREAD

**Issue by afladmark** [malcommac/SwiftDate#425]
Hello,

I believe I've run into an issue with the `Date.dates(between startDate: Date, and endDate: Date, increment components: DateComponents) -> [Date]` extension method. I'm giving it the first and last day of a 7 day range (with 00:00:00 time on both dates) and asking it for the dates between, like so:

```swift
let endDate = Date().startOfDay
let startDate = endDate - 6.days
let datesInRange = Date.dates(between: startDate, and: endDate, increment: 1.day)
```

I would expect to get back 7 values, but I actually get 8. It gives me a last date of one day greater than end date:

```
(lldb) po startDate
▿ 2017-04-26 00:00:00 +0000
  - timeIntervalSinceReferenceDate : 514857600.0

(lldb) po endDate
▿ 2017-05-02 00:00:00 +0000
  - timeIntervalSinceReferenceDate : 515376000.0

(lldb) po datesInRange
▿ 8 elements
  ▿ 0 : 2017-04-26 00:00:00 +0000
    - timeIntervalSinceReferenceDate : 514857600.0
  ▿ 1 : 2017-04-27 00:00:00 +0000
    - timeIntervalSinceReferenceDate : 514944000.0
  ▿ 2 : 2017-04-28 00:00:00 +0000
    - timeIntervalSinceReferenceDate : 515030400.0
  ▿ 3 : 2017-04-29 00:00:00 +0000
    - timeIntervalSinceReferenceDate : 515116800.0
  ▿ 4 : 2017-04-30 00:00:00 +0000
    - timeIntervalSinceReferenceDate : 515203200.0
  ▿ 5 : 2017-05-01 00:00:00 +0000
    - timeIntervalSinceReferenceDate : 515289600.0
  ▿ 6 : 2017-05-02 00:00:00 +0000
    - timeIntervalSinceReferenceDate : 515376000.0
  ▿ 7 : 2017-05-03 00:00:00 +0000
    - timeIntervalSinceReferenceDate : 515462400.0
```

I had a quick look at the code. The next value is appended even if it equals or exceeds the endDate and then the check (`<= endDate`) is performed after, so it's running another iteration more than it should/adding values which exceed the range in some cases (like when the last value is equal as in my example).

**Comment by malcommac** [comment]
Fixed for 4.1.2. Details in commit alongside tests.
Thank you!
