### ISSUE TITLE
How to convert DateInRegion into Date object 

### ISSUE THREAD

**Issue by iOSUser110** [malcommac/SwiftDate#426]
How to convert DateInRegion into Date object

**Comment by malcommac** [comment]
you can use `.absoluteDate` which return the `Date` representation of the `DateInRegion` instance.

**Comment by matuella** [comment]
The .absoluteDate is a representation of the DateInRegion that is outside the region. 
I.e: 
**Date()** prints _2017-11-23 12:33:41 +0000_
**Date().inLocalRegion()** prints _23 Nov 2017 10:33:41 GMT-2_
**Date().inLocalRegion().absoluteDate** prints _2017-11-23 12:33:41 +0000_

The absoluteDate var says: "Absolute date represented outside the region"
