### ISSUE TITLE
Error: Build failed due to use of undeclared type of ISO8601Configuration

### ISSUE THREAD

**Issue by Nik20112** [malcommac/SwiftDate#428]
Hi,

I have installed latest version of Cocoa Pods of SwiftDate but facing build error issue.

Build failed due to use of undeclared type of ISO8601Configuration

I am using latest Xcode version 8.3.2

> pod 'SwiftDate

Please help me to resolve this issue.

Thanks
Nikunj

**Comment by KaroleM** [comment]
same as here

**Comment by Nik20112** [comment]
Issue resolve by pod uninstall and install again.
