### ISSUE TITLE
"Time Components" returns inconsistent results

### ISSUE THREAD

**Issue by jmosouza** [malcommac/SwiftDate#429]
The `timeComponents(to:options:shared:)` function returns varying results on different runs of the app I'm working on. The goal is to display the age in years and months for the next vaccine in a vaccination card. The age for the vaccine objects are persisted in months and I rely on SwiftDate to get conversion, formatting and translation.

```
let birthDate = Date().startOfDay
let vaccinationDate = birthDate.add(components: [.month : 24])
let formattedAge = try vaccinationDate.timeComponents(
                           to: birthDate,
                           options: ComponentsFormatterOptions(
                               allowedUnits: [.month, .year],
                               style: .full,
                               zero: .dropAll))
```

On some runs of the app, the `formattedAge` is `2 years`, but in others it's `1 year, 11 months`.

I followed this documentation: http://malcommac.github.io/SwiftDate/formatters.html#timecomponents

**Comment by malcommac** [comment]
Hi, can you tell me more about these results; I've tried both on simulator and device with different timezones and I always get 2 years. Can you also try with 4.1.2? I've just fixed several issues with `colloquial` functions.

**Comment by malcommac** [comment]
Any news?
