### ISSUE TITLE
Project failing Pod Repo Push

### ISSUE THREAD

**Issue by RichAppz** [malcommac/SwiftDate#430]
Hi guys, just implemented your project to sort out some issues we have been having with timezones. It has worked perfectly.

The issue we are running into though is pushing the podspec - it is not linting, so the code that is being used is:

```
extension String {
    
    var dateFromISO8601: Date? {
        guard let timezone = TimeZone(abbreviation: .timezoneAbbreviation) else { return Formatter.getISO8601.date(from: self) }
        let region = Region(tz: timezone, cal: Calendar.localized, loc: Locale.autoupdatingCurrent)
        
        // THIS IF STATEMENT IS CAUSING THE PODSPEC LINTING ISSUE
        if let regionDate = DateInRegion(string: self, format: .iso8601(options: .withInternetDateTime), fromRegion: region) {
            return regionDate.absoluteDate
        }
        return Formatter.getISO8601.date(from: self)
    }
    
}
```

The `DateInRegion` when trying to pass a podspec lint is failing with the following:

![screen-shot-2017-05-05-at-10 21 37](https://cloud.githubusercontent.com/assets/2961823/25810814/2d1d9658-3409-11e7-9d6a-c56c70f091ba.png)

If you would like anymore information please let me know

**Comment by RichAppz** [comment]
Guys do you have an answer for this issue?

**Comment by malcommac** [comment]
Since the last update `DateInRegion` `init` functions does not throws anymore. It returns nil value if parsing fails. Seems you are building against an old version or something like that. Have you tried to clean and build?

**Comment by RichAppz** [comment]
Sorry, I never got an email notification, I will relook into this and get back to your shortly, Thanks 👍

**Comment by RichAppz** [comment]
Brilliant all fixed, sorry again for the long delay in answering! **Note to self check notification settings**
