### ISSUE TITLE
Build fail with carthage for 4.1.2 version

### ISSUE THREAD

**Issue by jojo91** [malcommac/SwiftDate#432]
Hi,
When I try to update my swifDate version to 4.1.2 with carthage the build fail with this error.

```
** CLEAN SUCCEEDED **

=== BUILD TARGET SwiftDate OF PROJECT SwiftDate WITH CONFIGURATION Release ===

Check dependencies
No architectures to compile for (ARCHS=armv7k, VALID_ARCHS=arm64 armv7 armv7s x86_64 i386).
warning: no umbrella header found for target 'SwiftDate', module map will not be generated

** BUILD FAILED **
```

**Comment by ladmini** [comment]
The same error for me, any update?

**Comment by RiverbayChris** [comment]
Same here.

**Comment by bkostjens** [comment]
Also the same here.

**Comment by emmekappa** [comment]
+1

**Comment by RiverbayChris** [comment]
Anyone successful in fixing this?  I tried removing the offending ARCH from the project file in 4.1.2, but then there were more Carthage errors.  The last version I can successfully build with Carthage is 4.0.14.

**Comment by malcommac** [comment]
I've tried with an empty project.
First of all I've created the `Cartfile` file (`touch Cartfile`)
Then I've added the record for SwiftDate (`github "malcommac/SwiftDate" "feature/4.1.5"` - I've tried the repo currently in development but it's the same with `develop` or `master`).
Then I've tried to build:

```
diesel-mac:test daniele$ carthage update --platform iOS
*** Please update to the latest Carthage version: 0.23.0. You currently are on 0.22.0
*** Cloning SwiftDate
*** Checking out SwiftDate at "f8206f5457e773e03df1ad1f8f9587420784f145"
*** xcodebuild output can be found in /var/folders/m4/6h1cv6ds2_q18rc_6w5z22dc0000gp/T/carthage-xcodebuild.iopPUg.log
*** Building scheme "SwiftDate" in SwiftDate.xcodeproj
diesel-mac:test daniele$ 
```

Everything was okay.
Then I've added it to my project, added `Copy Phase` for Framework and tried to run.
No problem found.

Can anyone tell me the exact steps to reproduce the problem?
Thanks

**Comment by RiverbayChris** [comment]
Good to go now, thanks.  I was running "carthage update SwiftDate".  Adding the "--platform iOS" fixed  it for master.

**Comment by malcommac** [comment]
I'll investigate on armv7k, the watchOS architecture.

**Comment by jojo91** [comment]
I still can have this issue, it's very simple to reproduce. 
Put this line in your Cartfile.
```github "malcommac/SwiftDate" == 4.1.2```
And then just do a carthage update.

Like @RiverbayChris said when you use "--platform iOS" it works. So this issue probably come from an other platform.
