### ISSUE TITLE
Date from String conversion is not working?

### ISSUE THREAD

**Issue by kidsid-Ixigo** [malcommac/SwiftDate#433]
I have a string and I am trying to get a Date object from it but it seem conversion is not happening properly here.
Eg. 

```
let actualArrivalTimeDate = "18 May 2017 10:48"
let date  = actualArrivalTimeDate.date(format: .custom("dd MMM yyyy HH:mm"))?.absoluteDate
```

I am posting here my terminal results.
```

(lldb) po actualArrivalTimeDate
"18 May 2017 10:48"


(lldb) po date
▿ Optional<Date>
  ▿ some : 1474-05-18 04:54:32 +0000
    - timeIntervalSinceReferenceDate : -16617899128.0


(lldb) po actualArrivalTimeDate.date(format: .custom("dd MMM yyyy HH:mm"))
▿ Optional<DateInRegion>
  ▿ some : 18 May 2017 BE, 10:48:00 am GMT+5:53:28
```

Here DateInRegion object looks fine (In terminal) but the final converted date has a year as "1474" which is weird. How to get a correct date from a string or a correct date from the DateInRegion object.

**Comment by hamsternik** [comment]
It's such a strange behaviour. I tested your case, but didn't get any problems with a year or another parts of date in string format. You can see this from the screen below.
<img width="1180" alt="screenshot 2017-05-24 15 24 48" src="https://cloud.githubusercontent.com/assets/4441804/26403039/59d52d3a-4095-11e7-9735-76c2660de0ff.png">

**Comment by kidsid-Ixigo** [comment]
[
![simulator screen shot 24-may-2017 6 46 05 pm](https://cloud.githubusercontent.com/assets/22613154/26404954/4cf31624-40b1-11e7-8261-b0c8bb1ea3e8.png)
](url)

@hamsternik  Do you have same region settings?
