### ISSUE TITLE
weekdayName, weekdayShortName return different depend on iPhone's language settings

### ISSUE THREAD

**Issue by yosuke1985** [malcommac/SwiftDate#435]
weekdayName, weekdayShortName return different depend on iPhone's language settings,

I want to only return English,
Can I do that?

Would you please give me advice?

**Comment by malcommac** [comment]
Results depend on your `Region` settings.
If you are using `Date` objects you can set the `defaultRegion` and change only the locale parameter.
Following example keeps the current device's calendar + timezone and set only the locale to english (ignoring current device's locale).

```swift
Date.setDefaultRegion(Region(tz: TimeZoneName.current, cal: CalendarName.current, loc: LocaleName.englishUnitedStates))
print("Current weekday name is \(Date().weekdayName)")  // saturday
```
