### ISSUE TITLE
Big size of dynamic framework file (10 MB)

### ISSUE THREAD

**Issue by Dschee** [malcommac/SwiftDate#437]
I'm including the latest version of SwiftDate (4.1.2) into my project via Carthage (using dynamic frameworks) and for me it seems for a date helper library 10 MB is quite large. Can you explain why this might be? Is there a possibility to decrease the file size (by excluding unnecessary files / libraries)?

Most other frameworks I included (that sometimes supposedly do more than SwiftDate) are somewhere around 1-3 MB.

Thanks for your help!

**Comment by malcommac** [comment]
Are you building a fat framework for all platforms?

**Comment by malcommac** [comment]
Fat frameworks are libs which includes several platforms.
I've tried building SwiftDate for iOS using carthage:

```
carthage update --platform iOS
```

SwiftDate.framework is 10MB.
It includes several architectures: `i386 x86_64 armv7 arm64`

```
diesel-mac:test daniele$ lipo -info /Users/daniele/Desktop/test/Carthage/Build/iOS/SwiftDate.framework/SwiftDate 
Architectures in the fat file: /Users/daniele/Desktop/test/Carthage/Build/iOS/SwiftDate.framework/SwiftDate are: i386 x86_64 armv7 arm64 
```

AppStore's thinning mechanism (bitcode) will exclude non interesting architectures.
So, for example, using `lipo` tool I've tried to keep only `armv7`:

```
cd /Users/daniele/Desktop/test/Carthage/Build/iOS/SwiftDate.framework 
lipo SwiftDate -thin armv7 -output SwiftDate-armv7.a
```

Will output a 2.5MB library as you see below

<img width="590" alt="screen shot 2017-06-10 at 18 57 20" src="https://user-images.githubusercontent.com/235645/27004734-ae6862c8-4e0e-11e7-8cfe-e96c5679ec4e.png">

**Comment by Dschee** [comment]
Ah, by platforms you mean hardware architectures. I see. Okay then with bitcode enabled this should not be a problem. Thanks for the answer!

**Comment by malcommac** [comment]
No you're welcome :)

**Comment by chriswill0w** [comment]
@malcommac I have the same issue. I built the framwork via 
`carthage update --platform iOS`

the framework size is 25.1 MB which seems quite big compared to some other frameworks.

`lipo -info` gives me `armv7 arm64`. 
`lipo SwiftDate -thin armv7 -output SwiftDate-armv7.a`  gives me an ouput file which is still 11.8 MB 

Why does this framework seem to be so big? Is there something I can do to improve the size?
