### ISSUE TITLE
DateInRegion object returning garbage day value

### ISSUE THREAD

**Issue by iOSUser110** [malcommac/SwiftDate#439]
Suddenly DateInRegion Object returns wrong day.

Ex.
```swift
let today = Date.dateInRegion()
```
previously  :- `today.day`  - > return todays date that is  `31`
currently  :- `today.day`  - > returning some garbage date like `132323`

may be it is after updating lib ,..
why this so ? is there any change in library.

please update on this ASAP.

**Comment by malcommac** [comment]
Hi,
There is not any func called Date.dateInRegion.

Current functions return correct values:
```swift
let today_dr = DateInRegion()
let today_d = Date()
print("current day from DateInRegion: \(today_dr.day)") // current day from DateInRegion: 10
print("current day from Date: \(today_d.day)") // current day from Date: 10
```

Same results from debugger.
Are you sure you have compiled SwiftDate without optimizations? (see GCC_OPTIMIZATION_LEVEL for your current Debug release).
