### ISSUE TITLE
Return converted Date()

### ISSUE THREAD

**Issue by quetool** [malcommac/SwiftDate#441]
How for the love of god can I return a Date() object after conversion to a particular region?

I have 

```
let region = Region(tz: TimeZoneName(rawValue: (newOrder?.location.timezone)!)!, cal: CalendarName.gregorian, loc: LocaleName.current)
                                
let date1 = DateInRegion(string: sd, format: .custom("yyyy-MM-dd'T'HH:mm:ssZZZZZ"), fromRegion: region) 
```

if I get date1.iso8601() I get a String() value... Ok, that's fine...

What I want is to get date1 converted as a Date() value, but with the timezone passed in Region(tz....)! If I get date1?.absoluteDate I get a Date() value but it is the original!

For example, this code

```
let sd = "2017-06-06T15:44:44Z"

let region = Region(tz: TimeZoneName(rawValue: (newOrder?.location.timezone)!)!, cal: CalendarName.gregorian, loc: LocaleName.current)
                                
let date1 = DateInRegion(string: sd, format: .custom("yyyy-MM-dd'T'HH:mm:ssZZZZZ"), fromRegion: region)
 print(date1?.iso8601() ?? "")
print(date1?.absoluteDate ?? "")
```

produce this output

```
2017-06-06T11:44:44-04:00
2017-06-06 15:44:44 +0000
```

What I want is FIRST OUTPUT (2017-06-06T11:44:44-04:00) as a Date!

**Comment by malcommac** [comment]
When you play with a `Date` instance you are working with an absolute amount of time which is not related to any timezone or region in the world. That's how Dates works on iOS.
You can get a `Date` in a particular TimeZone because it simply does not make sense.
