### ISSUE TITLE
Default Region Problem / Misunderstanding of the docs

### ISSUE THREAD

**Issue by victoraugustolls** [malcommac/SwiftDate#447]
Hi!

I'm trying to parse a iso date but when converting to string it is decreasing the day by one! Example below!!
```swift
Date.setDefaultRegion(Region.GMT())
let isoDate = DateInRegion(string: user.birthDate, format: .iso8601(options: [.withInternetDateTime]))
let date = isoDate!.string(format: .custom("dd/MM/YYYY"))
debugPrint(isoDate!, date)
```
Output: `21 Jun 1995 00:00:00 GMT "20/06/1995"`

Any help appreciated!!
Thanks!

**Comment by malcommac** [comment]
Hi, can you give to me the input string value? thanks

**Comment by victoraugustolls** [comment]
Of course:
`1995-06-21T00:00:00Z`

Thanks!

**Comment by malcommac** [comment]
I've tried to reproduce your issue but here it works fine.
What's the TZ of your device?
<img width="912" alt="screen shot 2017-07-12 at 14 53 53" src="https://user-images.githubusercontent.com/235645/28118623-09ca5736-6712-11e7-9fa1-dc7e6c4e1815.png">

**Comment by victoraugustolls** [comment]
My device is: GMT -3
But should my device TZ influence in the date even if I set the default region?

**Comment by victoraugustolls** [comment]
Any news here?

**Comment by malcommac** [comment]
No, TZ influence is ignored when you set the default region.
Anyway `defaultRegion` is used when you are working with plain `Date` objects directly.
If you are using `DateInRegion` you can pass the `fromRegion` parameter.

Just to avoid confusion:
when you are parsing an ISO8601 date the timezone is specified by the string; in this case `1995-06-21T00:00:00Z` is specified in UTC timezone. `fromRegion` parameter is used to define the tz (along with calendar and locale) in which the `DateInRegion` should be treated.
So if you set the Rome TZ (now +1) the date will be printed in specified timezone (while the `absoluteDate` property still expressed in absolute datetime).

I've also tried to set -3 in my TZ but I still see the correct date and I can't reproduce your issue. If you want you can send to me an empty project with your set so we'll exclude any other issue.

**Comment by victoraugustolls** [comment]
I just tried your code and using `.iso8601Auto` instead of `.iso8601(options: [.withInternetDateTime]` fixed the issue!!!
