### ISSUE TITLE
startOf and endOF func

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#45]
Hi,

Playing with the idea to use an NSCalendarUnit hare as in:
````
let date = oldDate.endOf(.Day)
````
What do you think?

**Comment by Hout** [comment]
Sorry you already have one...  :D

**Comment by Hout** [comment]
Ah no that was the class func, this one stays open

**Comment by malcommac** [comment]
Great idea, I'll commit it later this week

**Comment by Hout** [comment]
Finished it! :-) 
Check out my development branch!

**Comment by malcommac** [comment]
Yeah, put a pull request so I can figure changes better, thanks. Anything can improve the code is welcome :)
