### ISSUE TITLE
Miliseconds lost in ISO8601 conversion?

### ISSUE THREAD

**Issue by daviskoh** [malcommac/SwiftDate#455]
SwiftDate version as taken from my `Podfile.lock` file:
![image](https://user-images.githubusercontent.com/5395403/28244921-d4c97a82-69c6-11e7-8038-2f174fb34779.png)

I have an ISO8601 String as produced by Javascript's `.toISOString()` func. When i convert it to a `DateInRegion` it seems to be converting correctly down to the second, though there seems to be no way to verify **miliseconds** and `.nanosecond` is `0`. When I take that same `DateInRegion` and convert it back to a String, it appears to be missing the **miliseconds** though the format does look correct.

```
let string = "2017-07-16T03:54:37.800Z"
let date = DateInRegion(
  string: string,
  format: .iso8601(options: .withInternetDateTimeExtended),
  fromRegion: Region.GMT()
)
date.string(format: .iso8601(options: .withInternetDateTimeExtended))) // => "2017-07-16T03:54:37.000Z"
```

According to my understanding of the comments in `SwiftDate/Sources/SwiftDate/ISO8601DateTimeFormatter.swift`, using `.withInternetDateTimeextended` should handle milliseconds level of granularity.

![image](https://user-images.githubusercontent.com/5395403/28244955-21b2ba24-69c8-11e7-8e08-b73106055d7d.png)

Have I made a mistake somewhere? Is this the intended behavior? Help would be appreciated. Thank you!

**Comment by malcommac** [comment]
Thank you for your report. I've fixed the ISO8601 Parser and now it works correctly.

```swift
let string = "2017-07-16T03:54:37.800Z"
let date = DateInRegion(string: string, format: .iso8601(options: .withInternetDateTimeExtended),fromRegion: Region.GMT())
let str = date!.string(format: .iso8601(options: .withInternetDateTimeExtended))
```

Correctly returns: `2017-07-16T03:54:37.800Z`

Fix will be included in 4.1.7.

**Comment by malcommac** [comment]
Reference commit is: 79feaf88

**Comment by daviskoh** [comment]
thank you! 🥇
