### ISSUE TITLE
colloquialSinceNow is broken again

### ISSUE THREAD

**Issue by RolandasRazma** [malcommac/SwiftDate#457]
#SwiftDate 4.1.7 colloquialSinceNow say that date is "tomorrow" when it is not

(lldb) po startTime.colloquialSinceNow()
▿ 2 elements
  - colloquial : "tomorrow"
  ▿ time : Optional<String>
    - some : "Fri, Jul 21"

(lldb) po startTime
▿ 2017-07-21 10:00:00 am +0000
  - timeIntervalSinceReferenceDate : 522324000.0

(lldb) po Date()
▿ 2017-07-19 10:07:27 am +0000
  - timeIntervalSinceReferenceDate : 522151647.46755201

**Comment by plm75** [comment]
I don't know if this is related, but I'm also having trouble with colloquial dates.

For dates that are between now and an hour ago, the colloquial string used to be "xx minutes ago".  Now, I'm only getting "one hour ago" for all values.

**Comment by malcommac** [comment]
@plm75 can you provide some examples?
I've tried with three intervals and it works fine:

```swift
let ago_now = try! Date().colloquialSinceNow().colloquial // just now
let ago_6_minutes = try! (Date() - 6.minute).colloquialSinceNow().colloquial // 6 minutes ago
let ago_45_minutes = try! (Date() - 45.minute).colloquialSinceNow().colloquial // 45 minutes ago	
```

**Comment by malcommac** [comment]
@RolandasRazma can you paste the code here? thx

**Comment by alexsanderkhitev** [comment]
I wonder if there is an error or not.

**Comment by RolandasRazma** [comment]
@malcommac 

```swift
        let startTime = Date(timeIntervalSinceReferenceDate: 522324000.0)
        let nowTime = Date(timeIntervalSinceReferenceDate: 522151647.46755201)
        
        let (colloquial, _) = try! DateInRegion(absoluteDate: startTime).colloquial(toDate: DateInRegion(absoluteDate: nowTime))
        
        print(colloquial)
```

(lldb) po startTime
▿ 2017-07-21 10:00:00 +0000
  - timeIntervalSinceReferenceDate : 522324000.0

(lldb) po nowTime
▿ 2017-07-19 10:07:27 +0000
  - timeIntervalSinceReferenceDate : 522151647.46755201

(lldb) po colloquial
"tomorrow"

**Comment by plm75** [comment]
@malcommac 
Sorry for the delay.  I've put together a test app that shows incorrect colloquial strings displayed.

[Swift Date Test.zip](https://github.com/malcommac/SwiftDate/files/1207104/Swift.Date.Test.zip)

**Comment by malcommac** [comment]
<img width="864" alt="screen shot 2017-09-03 at 18 22 32" src="https://user-images.githubusercontent.com/235645/30004724-e7a34ee6-90d4-11e7-9925-b9affa0279ac.png">

May the date crosses a day?

**Comment by plm75** [comment]
@malcommac 
Hello, just to let you know that after a pod update, the version fetched is 4.1.7 and it looks like it solves the issue.

For reference, the version in the bug demo app is 4.1.2

Cheers!

ps: As far as I'm concerned this issue can be closed now.

**Comment by malcommac** [comment]
Thank you @plm75. We have revisited that functions not so long ago so this explain all.
Have a nice day
