### ISSUE TITLE
Is it possible to get shortWeekdayName?

### ISSUE THREAD

**Issue by prakashraman** [malcommac/SwiftDate#458]
I was looking through the documentation at http://malcommac.github.io/SwiftDate/date_components.html#weekdayname

I did not find a 
> shortWeekdayName

Although there was as a
> shortMonthName

Is there still a way to get "Tue" instead of "Tuesday"? Or do I just write an extension to pull only the first the characters?

Thanks!

p.s love the rest of the features by the way!

**Comment by malcommac** [comment]
Hi,
you can use `weekdayShortName` and `weekdayName`.
I'll unify the name of these variable inside the next minor update.
Thanks

**Comment by prakashraman** [comment]
Great! Thanks!

**Comment by malcommac** [comment]
Reference: https://github.com/malcommac/SwiftDate/commit/77740d9f40d4df36bc8c7e266b174d5ca2ad7e62
