### ISSUE TITLE
dutch locale returns wrong format for differences of more than a year in colloquialSinceNow()

### ISSUE THREAD

**Issue by hammond756** [malcommac/SwiftDate#459]
How to produce:

``` swift
let regionAmsterdam = Region(tz: TimeZoneName.europeAmsterdam, cal: CalendarName.gregorian, loc: LocaleName.dutch)
let threeYearsFromNow = DateInRegion(absoluteDate: Date() + 1.year + 1.month, in: regionAmsterdam)
let colloquial = try! threeYearsFromNow.colloquialSinceNow().colloquial
print(colloquial) // "over 2018 jaar" -> literal translation: "in 2018 years"
```

I also tried it with the `.englishUnitedStates` locale an that returns "on 2018", which also doesn't seem like desired behavior.

**Comment by malcommac** [comment]
It should be "on 2016". what's the equivalent for "on"? I see "in" in google translate; is this correct?

**Comment by malcommac** [comment]
Can you make a check of the `/Sources/SwiftDate/SwiftDate.bundle/nl-NL.lproj/SwiftDate.strings` and tell me if there is something else wrong?
[File link](https://github.com/malcommac/SwiftDate/blob/feature/4.1.8/Sources/SwiftDate/SwiftDate.bundle/nl-NL.lproj/SwiftDate.strings)
