### ISSUE TITLE
isInSameDayOf with plain Date objects

### ISSUE THREAD

**Issue by timefrancesco** [malcommac/SwiftDate#460]
I might be wrong but here is what is happening to me:

```swift
let today =  Date()
        
let firstDay = (today - weekSpan.week).startWeek
let lastDay =  (today + weekSpan.week ).endWeek + 1.day

var date = firstDay
while !date.isInSameDayOf(date: lastDay) {
   
    date = date + 1.day
}
```

If for example:

```
lastDay = 2017-08-06 11:59:59 +0000
date = 2017-08-05 12:00:00 +0000
```

isInSameDayOf returns true. 🤔

**Comment by malcommac** [comment]
Hi, can you post an example with real data?
I've tried with the result you have printed, so:

```swift
let day_a = DateInRegion(string: "2017-08-06 11:59:59 +0000", format: .iso8601Auto)!
let day_b = DateInRegion(string: "2017-08-05 12:00:00 +0000", format: .iso8601Auto)!
let is_the_same_day = day_a.isInSameDayOf(date: day_b) // false
```

It return false.
I think there is something wrong with TZ of the two dates.

<img width="782" alt="screen shot 2017-09-03 at 18 07 29" src="https://user-images.githubusercontent.com/235645/30004617-f33ed22c-90d2-11e7-9a7d-efd1541de798.png">

**Comment by timefrancesco** [comment]
Hey so actually, the issue is with Date, DateInRegion works fine (so I'm using that now).  
Here is how to replicate the issue, you can copy and paste this code:

```
let today =  Date()      
let firstDay = today.startWeek
let lastDay = today.endWeek
var date = firstDay
        
while !date.isInSameDayOf(date: lastDay) {
   print(String(describing: date) + " not same day of " + String(describing: lastDay))
           
   let newDate = date + 1.day
    date = newDate
 }
        
print (String(describing: date)  + " same day of " + String(describing: lastDay))
```

It will output:

```
2017-09-02 12:00:00 +0000 not same day of 2017-09-09 11:59:59 +0000
2017-09-03 12:00:00 +0000 not same day of 2017-09-09 11:59:59 +0000
2017-09-04 12:00:00 +0000 not same day of 2017-09-09 11:59:59 +0000
2017-09-05 12:00:00 +0000 not same day of 2017-09-09 11:59:59 +0000
2017-09-06 12:00:00 +0000 not same day of 2017-09-09 11:59:59 +0000
2017-09-07 12:00:00 +0000 not same day of 2017-09-09 11:59:59 +0000
2017-09-08 12:00:00 +0000 same day of 2017-09-09 11:59:59 +0000
```

While if replacing Date with DateInRegion:

```
let today =  Date()
let firstDay = today.startWeek
let firstDateInRegion = DateInRegion(absoluteDate: firstDay)
let lastDay = today.endWeek
let lastDateInRegion = DateInRegion(absoluteDate: lastDay)
        
var date = firstDateInRegion
        
while !date.isInSameDayOf(date: lastDateInRegion) {
   print(String(describing: date) + " not same day of " + String(describing: lastDay))
           
   let newDate = date + 1.day
   date = newDate            
}
        
print (String(describing: date)  + " same day of " + String(describing: lastDay))
```


it will output:
```
Sep 3, 2017, 12:00:00 AM GMT+12 not same day of 2017-09-09 11:59:59 +0000
Sep 4, 2017, 12:00:00 AM GMT+12 not same day of 2017-09-09 11:59:59 +0000
Sep 5, 2017, 12:00:00 AM GMT+12 not same day of 2017-09-09 11:59:59 +0000
Sep 6, 2017, 12:00:00 AM GMT+12 not same day of 2017-09-09 11:59:59 +0000
Sep 7, 2017, 12:00:00 AM GMT+12 not same day of 2017-09-09 11:59:59 +0000
Sep 8, 2017, 12:00:00 AM GMT+12 not same day of 2017-09-09 11:59:59 +0000
Sep 9, 2017, 12:00:00 AM GMT+12 same day of 2017-09-09 11:59:59 +0000
```  

So DateInRegion seems to work fine while Date seems strange to me.  
I've dug a little bit and it seems the issue is the Swift Calendar comparison, not sure if it's an issue but I suspect I am not smart enough to understand Timezones properly 🤷‍♂️!

**Comment by malcommac** [comment]
This because when compared both `Date` are moved to your `defaultRegion()` `Region`.
If not changed `Region` is the local region (device's timezone, device's calendar and device's locale).
So (assuming my region, GMT +2) for your last date you will have:
- `date` = `2017-09-09 21:59:59 +0000` -> inDefaultRegion() -> `Sep 9, 2017, 12:00:00 AM GMT+2`
- `lastDay` = `2017-09-09 21:59:59 +0000` -> inDefaultRegion() -> `Sep 9, 2017, 11:59:59 PM GMT+2`

and in that timezone they represent the same day.

A solution is to set the GMT region at startup:
`Date.setDefaultRegion(Region.GMT())`

So your date will be compared against the GMT (/UTC) timezone.

or use `DateInRegion` as you have done.

**Comment by timefrancesco** [comment]
👍
