### ISSUE TITLE
How to format 24 hour time

### ISSUE THREAD

**Issue by antonioreyna** [malcommac/SwiftDate#466]
Hello, i have this code:

```swift
let salida: Date = "06/08/2017 17:35".date(format: .custom("dd/MM/yyyy hh:mm"), fromRegion: Region(tz: TimeZoneName.americaMonterrey, cal: CalendarName.current, loc: LocaleName.current))!.absoluteDate
print(salida.string(format: .custom("dd/MM/yyyy hh:mm")))
print(salida.string(format: .custom("dd/MM/yyyy HH':'mm")))
```

I want to get a string with a 24 hours representation of that time, but i dont know why is not working anymore, i get this as result.

```swift
06/08/2017 05:35
06/08/2017 5:35 p.m.
```

I dont even know why the second adds `p.m.`

Any idea?

**Comment by malcommac** [comment]
Have you tried to set a different locale?
What's your `.currentLocale`?

**Comment by malcommac** [comment]
I'll close it due to no response received.
