### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by abunur** [malcommac/SwiftDate#47]
![screen shot 2015-10-05 at 3 27 30 pm](https://cloud.githubusercontent.com/assets/4803881/10291078/b228c416-6b75-11e5-9991-65b0cfaf92fc.png)
Am getting this error: "Command failed due to signal: Segmentation fault: 11" when trying to run test suite on my project.  Am using SwiftDate via CocoaPods.  Am using few other libraries but only SwiftDate is causing this crash.  For build & run, though it runs fine.

**Comment by abunur** [comment]
ah looks like the Unit Tests in the library need updating.  I made a pull request, will update it and submit.

**Comment by malcommac** [comment]
Just merged your pull request, thank you.
