### ISSUE TITLE
CalendarName init for raw values

### ISSUE THREAD

**Issue by umoruj** [malcommac/SwiftDate#472]
Is there a simple way to save the Region for a date as a String alongside the Date as a String to my database, so that when I request the date I can also request the region to easily parse it. By region I mean  

```swift
let regionRome = Region(tz: TimeZoneName.europeRome, cal: CalendarName.gregorian, loc: LocaleName.italianItaly). 
```

I am building my App in iOS 10.3 with Xcode 8.3.3 with Swift 3.1. Am getting date both in Danish and English. Thanks for your help in advance.

Like in this example I can save the `TimeZoneName` and `LocalName` as String to my database but I can't save the `CalendarName`.
Is there a solution??

```swift
let SimuRegion2 = Region(tz: TimeZoneName(rawValue: "Europe/Copenhagen")!, cal: CalendarName.gregorian  , loc: LocaleName(rawValue: "en")!)
```

**Comment by malcommac** [comment]
`CalendarName` now supports `RawRepresentable` protocol so you can init and extract a `String` from it.

**Comment by umoruj** [comment]
Thanks
