### ISSUE TITLE
SwiftDate and Swift 4 support

### ISSUE THREAD

**Issue by DmitriyBagrov92** [malcommac/SwiftDate#474]
I can't compile the latest version on Xcode 9. Can you help with it?
<img width="1218" alt="screen shot 2017-09-01 at 12 16 53" src="https://user-images.githubusercontent.com/21103526/29963432-81e4c736-8f0f-11e7-959c-6715119ad143.png">

**Comment by malcommac** [comment]
I've updated [swift-4 branch](https://github.com/malcommac/SwiftDate/tree/swift-4)
