### ISSUE TITLE
Reverse intervals are not allowed (4.1.10)

### ISSUE THREAD

**Issue by alexsanderkhitev** [malcommac/SwiftDate#478]
Hello! My code that worked well with previous versions of SwiftDate gets crash because of the following error. Precondition failed: Reverse interval are not allowed: file.

```
        let cardDate = tranformTimeIntervalToDate(card.dateProperties.timeStamp).startOfDay
        let nowDate = Date().startOfDay
        guard let betweenDays = (cardDate - nowDate).in(.day) else {
            return cardDate.string(dateStyle: .short, timeStyle: .none)
        }

```

**Comment by malcommac** [comment]
Use: 

```swift
 guard let betweenDays = (nowDate  - cardDate).in(.day) else {
```

**Comment by alexsanderkhitev** [comment]
Hi @malcommac 

Yes, this problem is gone, I no longer get the app crash

I have a given time stamp in my event 1504580400.0, and it should show up like that on Tuesday, September 5, 2017 7:00:00 AM GMT + 04: 00, and he indicates 12:00 AM. In this method, cardDate.string (dateStyle: .none, timeStyle: .short)

**Comment by malcommac** [comment]
Updated #480
