### ISSUE TITLE
Fix for NSRange under XCode 9 for 4.4.0 tagged release

### ISSUE THREAD

**Issue by daerimin** [malcommac/SwiftDate#483]
[...]/Pods/SwiftDate/Sources/SwiftDate/DOTNETDateTimeFormatter.swift:47:90: Cannot call value of non-function type 'NSRange' (aka '_NSRange')

[...]/Pods/SwiftDate/Sources/SwiftDate/DOTNETDateTimeFormatter.swift:50:66: Cannot call value of non-function type 'NSRange' (aka '_NSRange')

**Comment by malcommac** [comment]
Try 4.4.1 on cocoapods.
Thanks.

**Comment by sakshiGoel26** [comment]
I have updated my pods to 4.4.1, but still getting the same error.

**Comment by malcommac** [comment]
Cannot reproduce it. Can you make a new project with SwiftDate pods and import+compile it?
(You can also try to remove Pods and Pod.lock and update it)

**Comment by sakshiGoel26** [comment]
@malcommac  I removed the SwiftDate pod from my project, & then added it again. Still facing issue in "DOTNETDateTImeFormatter" class. Attaching the screenshot
![screen shot](https://user-images.githubusercontent.com/14308339/30475135-61146c7c-9a23-11e7-997e-0a9c2e23a304.png)

**Comment by jimsmithm3** [comment]
I am started seeing this yesterday as well.  Here is a sample project (does nothing but get the compile error).   https://github.com/jimsmithm3/swiftdatetest2

**Comment by prasadgau** [comment]
Even i am getting same error. Is there any solution for it?

**Comment by jeanmartin** [comment]
Ah, looks like we all didn't RTFM: #485 :D

**Comment by malcommac** [comment]
Just for reference:

* **Swift 4.x**: >= 4.4.0 - Latest is 4.4.0 Download here.
* **Swift 3.x**: Latest compatible version is 4.3.0 Download here
* **Swift 2.3**: Latest compatible version is 3.0.9 on swift_23 branch

**Comment by AlexGZC** [comment]
i have the same issue, can you help me? Please?

**Comment by malcommac** [comment]
Are you using Swift 3? You need to block your pod to 4.30 as specified above, otherwise you will get the latest swift 4 version.

**Comment by Gigglesza** [comment]
When I try force the pod file to use 4.3.0, I get the following error:
"Unable to find a specification for `SwiftDate~> 4.3.0`"

**Comment by oskarko** [comment]
You haven't written correctly. pod 'SwiftDate', '~> 4.3.0'
