### ISSUE TITLE
SwiftDate for Swift 3.x (<= 4.3.0) and Swift 4.x (>= 4.4.0)

### ISSUE THREAD

**Issue by ivanmkc** [malcommac/SwiftDate#485]
Upgrading from 4.3.0 to 4.4.1 causes the following error on compilation.

<img width="920" alt="screen shot 2017-09-15 at 12 37 21 pm" src="https://user-images.githubusercontent.com/1586049/30500662-3854725a-9a14-11e7-9ffd-6dea05108fd6.png">

The file is DOTNETDateTimeFormatter.swift

**Comment by llKoull** [comment]
Same here :S

**Comment by malcommac** [comment]
Are you using 4.4.0 in a Swift 3.x project?

**Comment by llKoull** [comment]
Hi malcommac!

Yes it's a swift 3 project.

**Comment by malcommac** [comment]
That's the problem.
4.4.0 is built for Swift 4
<= 4.3.0 is built for Swift 3.x

Check out the README.md file under 'Current Release' Section:
https://github.com/malcommac/SwiftDate/blob/master/README.md

```
Current Release

Swift 4.x: >= 4.4.0 - Latest is 4.4.0 Download here.
Swift 3.x: Latest compatible version is 4.3.0 Download here
Swift 2.3: Latest compatible version is 3.0.9 on swift_23 branch
A complete list of changes for each release is available in the CHANGELOG file.
```

**Comment by llKoull** [comment]
Ooooh thanks for your answer Malcolmmac! ^_^
