### ISSUE TITLE
colloquialSinceNow broken with Xcode9/swift 3.2 v4.3.1

### ISSUE THREAD

**Issue by electic** [malcommac/SwiftDate#486]
Calling colloquialSinceNow() on a date gives the following text: 

<img width="92" alt="screen shot 2017-09-19 at 9 12 12 pm" src="https://user-images.githubusercontent.com/43028/30626510-3ae2eba0-9d7f-11e7-9866-2a2b4b3e8bbd.png">

**Comment by mittenimraum** [comment]
+1

**Comment by cgoldsby** [comment]
I think this change is related to the fix made for #463.

The colloquial formatted string is returned only for unit style `.full` and `.spellOut`, else it returns a "time formatted" string (which is now the default). [L133](https://github.com/malcommac/SwiftDate/commit/71fa199367248bd1de6924f6044f78cb0036ab65#diff-8fbdfe1d75598c3cc30c5d372693d73cR133)

In the meantime, I've updated my code to use:
```
colloquialSinceNow(unitStyle: .full)
```

**Comment by electic** [comment]
That was it. Thank you!
