### ISSUE TITLE
Invalid Bundle - Disallowed LLVM instrumentation

### ISSUE THREAD

**Issue by plu** [malcommac/SwiftDate#488]
Apple has a new automatic check when validating the binary that was built using Xcode 9 / iOS 11 SDK. If the binary contains some code coverage instrumentation, it will be rejected. The full message is:

> Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with
> LLVM profiling instrumentation or coverage collection enabled. Turn off
> LLVM profiling or code coverage, rebuild your app and resubmit the app.

**Comment by CocoaPriest** [comment]
+1. When using Carthage [building static frameworks], the linker fails. Unchecking `Gather Coverage Data` in SwiftDate fixes this issue.

**Comment by malcommac** [comment]
Resolved in 4.1.2.
https://github.com/malcommac/SwiftDate/commit/affe3b5eea8d3604125a71b4875900414269add6

**Comment by babuiglesiaskhan** [comment]
Hi,
Whenever I upload my build. It shows "Processing" but after 10 mins, I got an message of build "The build is invalid" and when i check my mail. I got this message .


Dear Developer,

We identified one or more issues with a recent delivery for your app, "Domino's Pizza Indonesia". Please correct the following issues, then upload again.

Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.

Best regards,

The App Store Team
