### ISSUE TITLE
Regional text conversion bug

### ISSUE THREAD

**Issue by electic** [malcommac/SwiftDate#490]
I was hoping someone could help me with translating text to the system region and language. If I set the region to China/Chinese (Traditional) the system still outputs the string in English. Here is my code:

`let (colloquial, _) = try! createdAt!.colloquialSinceNow(unitStyle: .full)`

I know the translations are there because I can see them in the code. What am I doing wrong? Or is this a bug? Any help appreciated?

**Comment by malcommac** [comment]
Have you added translations in your project?
By default only english is present even if you have multiple localizable files.

<img width="687" alt="screen shot 2017-10-26 at 19 26 49" src="https://user-images.githubusercontent.com/235645/32067471-a7770c08-ba83-11e7-8396-345b1902bd57.png">

**Comment by electic** [comment]
Thanks for the response. I did. I have translated the app in Japanese and Chinese already.
