### ISSUE TITLE
v4.4.1 human-readable time not return correctly

### ISSUE THREAD

**Issue by atom2ueki** [malcommac/SwiftDate#491]
after migrate to swift 4 version with swift 4 project
`.colloquialSinceNow().colloquial` no longer return me a time as `10 days ago`
but `10 days 20mins 31 sec` instead

is there any extra setting needed in new version?

**Comment by electic** [comment]
Look at this https://github.com/malcommac/SwiftDate/issues/486

**Comment by atom2ueki** [comment]
@electic yep, it works
