### ISSUE TITLE
TimeInterval's `in()` function must accept or not a reference date

### ISSUE THREAD

**Issue by ernestofndz** [malcommac/SwiftDate#505]
Hey guys, amazing work, love it.

I've got a weird behaviour when comparing dates. I'm running the latest version at this moment which is `4.4.2`

<img width="300" alt="screen shot 2017-11-07 at 19 17 41" src="https://user-images.githubusercontent.com/846618/32512898-68d15492-c3f0-11e7-89cd-82ae614a03cd.png">

Date base that I'm using to compare
2017-11-21 00:00:00 +0000 `timeIntervalSince1970 = 1511222400.0` 

**Against** 
2017-11-30 00:00:00 +0000 `timeIntervalSince1970 = 1512000000.0` 
difference in seconds is `777600` which in days is `9`
`SwiftDate` says `9` ✅ 

**Against**
2017-12-01 00:00:00 +0000 `timeIntervalSince1970 = 1512086400.0`
difference in seconds is `864000` which in days is `10`
`SwiftDate` says `9` ❎ 

Dates going forward are also calculated wrong. Any ideas?

**Comment by malcommac** [comment]
Hi @ernestofndz , may I ask to post the code used for these test here so I can make further investigations? Thanks

**Comment by ernestofndz** [comment]
Hi @malcommac, I just created a sample project: https://github.com/ernestofndz/SDDateDiff.

The code in the `AppDelegate` makes no difference, but just keeping it as I have in the other project. If I get some time this weekend will try to take a look myself. Thanks!

**Comment by malcommac** [comment]
Thank you for your report.
Function return wrong values because conversion take care of the interval starting from a specific date (specifically range used by the function is `{Date() - Date() - interval}`).
I've modified the function to allow passing a start reference date.
If date is passed conversion take care of this value.
If date is not passed conversion is absolute but only a small subset of time components are accepted (`.day,.hour,.minute,.second`).

```swift
/// Express given time interval in other time units.
	/// If a reference date (`fromDate`) is not specified conversion is aware of day light saving times and other possible nasty things
	/// (only `.day,.hour,.minute,.second` are supported as components).
	/// If a reference date is specified conversion is made using the interval from passed reference date and include calendar/date
	/// specific events.
	///
	///
	/// - Parameters:
	///   - components: components to extract
	///   - date: reference date; `nil` uses absolute conversion, valida date to set the interval from a specific date.
	///   - calendar: context calendar; `nil` uses `Date.DefaultRegion.calendar` instead
	/// - Returns: components
	public func `in`(_ components: [Calendar.Component], fromDate date: Date? = nil, of calendar: Calendar? = nil) -> [Calendar.Component : Int] {
		guard let refDate = date else {
			// Absolute conversion, not taking care of specific starting date
			let days = Int( (components.contains(.day) ? self / (60 * 60 * 24) : 0) )
			let hours = Int((components.contains(.hour) ? ((self / (60 * 60)) - (Double(days) * 24)) : 0))
			let minutes = Int( (components.contains(.minute) ? ((self / 60) - (Double(days) * 24 * 60) - (Double(hours) * 60)) : 0))
			let seconds = Int( (components.contains(.second) ? Int(self.truncatingRemainder(dividingBy: 60)) : 0))
			
			var components: [Calendar.Component : Int] = [:]
			if (days > 0) 		{ components[.day] = Int(days) }
			if (hours > 0) 		{ components[.hour] = Int(hours) }
			if (minutes > 0)	{ components[.minute] = Int(minutes) }
			if (seconds > 0)	{ components[.second] = Int(seconds) }
			return components
		}
		
		let cal = calendar ?? Date.defaultRegion.calendar
		let dateFrom: Date = refDate
		let dateTo: Date = dateFrom.addingTimeInterval(self)
		let cmps = cal.dateComponents(componentsToSet(components), from: dateFrom, to: dateTo)
		return cmps.toComponentsDict()
	}
```
