### ISSUE TITLE
Ambiguous use of 'compare(to:in:granularity:)'

### ISSUE THREAD

**Issue by Ganiza** [malcommac/SwiftDate#510]
Hi, I installed swiftDate in hand (no cocoaPods ) and after having tested for a couple of hours after doing a clean build folder I got this error in several files:

Date+Compare:
    Ambiguous use of 'compare(to:in:granularity:)'
   instartOf and endOf:  Ambiguous use of 'rangex(of:for:)'
Date+Formatter:
   Ambiguous use of 'string(format:in:)'

etc etc

Versions of SwiftDate (4.5)I don't understand the reason for this error. Can you help me, please?

Thanks in advance

**Comment by malcommac** [comment]
Can you post an example of code?
