### ISSUE TITLE
How to check whether the date is in current date?

### ISSUE THREAD

**Issue by hemangshah** [malcommac/SwiftDate#513]
Hi @malcommac thanks for the great library, I am trying to check if a date is within another date?

**Comment by hemangshah** [comment]
Can't we have something like this?

https://github.com/melvitax/DateHelper#comparing-dates

**Comment by hemangshah** [comment]
We may like simple functions like if it's in the current month, previous month or in next month?

**Comment by malcommac** [comment]
`isInRange()` function allows what you need in SwiftDate 5.x
