### ISSUE TITLE
Differences between two dates in time unit

### ISSUE THREAD

**Issue by hemangshah** [malcommac/SwiftDate#514]
Hi @malcommac, I am trying to find out the difference between two dates.

Here's the code:

```
let requestTimeFromDate = Date.init(fromString: "13:15:00", format: .custom("HH:mm:ss"))
let requestTimeToDate = Date.init(fromString: "15:35:00", format: .custom("HH:mm:ss"))
```

How to get difference like, `requestTimeToDate - requestTimeFromDate` = `?`

**Comment by malcommac** [comment]
There are several ways to accomplish your task. You can use the standard math operation to get the differences in seconds or you can express it in several other time units using the `getInterval()` function.
The example below show the differences between your dates in minutes:

```swift
let requestTimeFromDate = "13:15:00".toDate("HH:mm:ss")!
let requestTimeToDate = "13:35:00".toDate("HH:mm:ss")!
let diff = requestTimeFromDate.getInterval(toDate: requestTimeToDate, component: .minute) // 20 minutes
```

(code was updated to SwiftDate 5.x)
