### ISSUE TITLE
Using .in() to extract calendar specific components without a reference date may return wrong values

### ISSUE THREAD

**Issue by arakweker** [malcommac/SwiftDate#524]
I'm getting a warning from SwiftDate "[SwiftDate] Using .in() to extract calendar specific components without a reference date may return wrong values." How can I get rid of this warning?

My code:

let calendar = Calendar.current
let birthDate = calendar.date(from: calendar.dateComponents([.year, .month, .day], from: myBirthday))!
let dateToday = calendar.date(from: calendar.dateComponents([.year, .month, .day], from: Date()))!
let daysAlive = (dateToday - birthDate).in(.day)

**Comment by ndizazzo** [comment]
In your case, to avoid seeing this message, you can write `birthDate.in(.day, fromDate: dateToday)`.

Looking at `TimeInterval+Extensions.swift`, it seems that a `debugPrint` warns you when passing `Calendar.Component`s, while leaving the `fromDate` parameter empty.

Personally, I think this is awkwardly written. Most of the time, somebody will be computing a `TimeInterval` (as you are) and asking for the delta in a certain unit of time. Why would we need / want to pass a reference date back into the `.in()` method, when the delta is already computed? Strange.

**Comment by arakweker** [comment]
That works, the warning stopped. Thanks for helping out, ndizazzo.
