### ISSUE TITLE
12 and 24 hours format getting merged when getting string value

### ISSUE THREAD

**Issue by ilandbt** [malcommac/SwiftDate#526]
Hi im getting a date from `CMMotionActivity`

`activityMotion.startDate.inLocalRegion().string(custom: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")`

Usually everything works great but sometime im getting very weird dates.

for example: 

> 2018-01-15T1010:22:26.553 AMZ

> 2018-01-14T2210:02:18.240 PMZ

the 24 and 12 hours format are getting merged together.

**Comment by malcommac** [comment]
You can use `toISO()` since SwiftDate 5.x:

```swift
activityMotion.startDate.inDefaultRegion().toISO()
```
