### ISSUE TITLE
[SwiftDate 4.x] Build failure with Carthage: No architectures to compile for (ARCHS=armv7k, VALID_ARCHS=arm64 armv7 armv7s x86_64 i386)

### ISSUE THREAD

**Issue by jdmuys** [malcommac/SwiftDate#528]
Using SwiftDate with Carthage. The Cart File has:

    github "malcommac/SwiftDate" ~> 4.5.1

then I execute `carthage update` and I get a build error.

The error happens when building the watchOS version, and the build error is:

    "No architectures to compile for (ARCHS=armv7k, VALID_ARCHS=arm64 armv7 armv7s x86_64 i386)"

Strangely, the scheme is "SwiftDate_iOS", but the SDK is "watchos".

Any suggestion welcome.

Here is the full `carthage update` output:

*** Fetching SwiftDate
*** Checking out SwiftDate at "4.5.1"
*** xcodebuild output can be found in /var/folders/qb/7l76w8zn78b44v7022m7cft40000gn/T/carthage-xcodebuild.sBAP5q.log
*** Building scheme "SwiftDate-tvOS" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate-watchOS" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate-macOS" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate-macOS" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate-watchOS" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate-tvOS" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate_iOS" in SwiftDate.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/lmsix/Iphone_World/suivi-des-quais/suivi\ des\ quais/Carthage/Checkouts/SwiftDate/SwiftDate/SwiftDate.xcodeproj -scheme **_SwiftDate_iOS_** -configuration Release -derivedDataPath /Users/lmsix/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9Q107o/SwiftDate/4.5.1 -sdk **_watchos_** ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/qb/7l76w8zn78b44v7022m7cft40000gn/T/SwiftDate SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/lmsix/Iphone_World/suivi-des-quais/suivi des quais/Carthage/Checkouts/SwiftDate)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/qb/7l76w8zn78b44v7022m7cft40000gn/T/carthage-xcodebuild.sBAP5q.log

And here is the tail of the log file:

/usr/bin/xcrun xcodebuild -project /Users/lmsix/Iphone_World/suivi-des-quais/suivi\ des\ quais/Carthage/Checkouts/SwiftDate/SwiftDate/SwiftDate.xcodeproj -scheme **_SwiftDate_iOS_** -configuration Release -derivedDataPath /Users/lmsix/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9Q107o/SwiftDate/4.5.1 -sdk **_watchos_** ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/qb/7l76w8zn78b44v7022m7cft40000gn/T/SwiftDate SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/lmsix/Iphone_World/suivi-des-quais/suivi des quais/Carthage/Checkouts/SwiftDate)User defaults from command line:
    IDEArchivePathOverride = /var/folders/qb/7l76w8zn78b44v7022m7cft40000gn/T/SwiftDate
    IDEDerivedDataPathOverride = /Users/lmsix/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9Q107o/SwiftDate/4.5.1

Build settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = **_watchos4.3_**
    SKIP_INSTALL = YES

=== BUILD TARGET SwiftDate OF PROJECT SwiftDate WITH CONFIGURATION Release ===

Check dependencies
No architectures to compile for (ARCHS=armv7k, VALID_ARCHS=arm64 armv7 armv7s x86_64 i386).
warning: no umbrella header found for target 'SwiftDate', module map will not be generated

** ARCHIVE FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by malcommac** [comment]
Hi, unfortunately I'm not able to support both 4.x and 5.x branches.
Carthage works fine in SwiftDate 5.x

```
danielembp15:porva daniele$ carthage update
*** Cloning SwiftDate
*** Checking out SwiftDate at "5.0.12"
*** xcodebuild output can be found in /var/folders/bp/7z5xsw313y18psjjv7pk9z880000gp/T/carthage-xcodebuild.fQE7Fd.log
*** Building scheme "SwiftDate-macOS" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate-tvOS" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate-watchOS" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate-iOS" in SwiftDate.xcodeproj
```
