### ISSUE TITLE
Append "th", "st", "nd" or "rd" to day

### ISSUE THREAD

**Issue by gregorpichler** [malcommac/SwiftDate#53]
It would be nice to have a feature that appends "th", "st", "nd" or "rd" to the day of date. Examples:

05th August, 01st December, 2nd February or 03rd July

**Comment by malcommac** [comment]
Hi @gregorpichler, I've recently removed 'ago'/'since' suffixes from readable date method in order to make something which is not strictly related to any language. It should be a date manipulation library,
For the same reason I think it's not correct to accept your request, I'm sorry :)
