### ISSUE TITLE
Parsing string with date to DateInRegion returns nil.

### ISSUE THREAD

**Issue by 1er4y** [malcommac/SwiftDate#534]
Hi.
I have the string in format `2018-03-09 18:00:00`, and i want parse this string to `DateInRegion` in **24 hours** format with this lines: 

```swift
 if let date = DateInRegion(string: "2018-03-09 18:00:00", format: .custom("yyyy-MM-dd HH:mm:ss")) {
....
}
```

While on device we use 24 Hours format, this code working, but, **after changing  time format to AM/PM on device** in Settings -> General -> Date&Time (24-Hour TIme disabled), this code is stop to work, and `DateInRegion` will return `nil`

Small debugging, show me that SwiftDate file `DateInRegion.swift` have a code started at 101 line:

```swift
public func dateFormatter(format: String? = nil, heuristics: Bool = true) -> DateFormatter {
			var formatter: DateFormatter? = nil
			if useSharedFormatters == true {
				let name = "SwiftDate_\(NSStringFromClass(DateFormatter.self))"
				formatter = localThreadSingleton(key: name, create: { () -> DateFormatter in
					return DateFormatter() ///this never executed for me
				})
			}
                  ....
}
```

**And finally, on my iOS 11.2.6 is not working, but iOS before 11.2 works fine**

**Comment by 1er4y** [comment]
@jsouhail Yes, i founded workaround:

```
 if let date = DateInRegion(string: "2018-03-09 18:00:00", format: .custom("yyyy-MM-dd **HH**:mm:ss")) {
                          ///do your logic 
                        } else if let date = DateInRegion(string: "2018-03-09 18:00:00", format: .custom("yyyy-MM-dd **hh**:mm:ss")) {
                               ///do your logic
                       }
 }
```
Different between this two if's is that, in first if we parsing 24H format: `"yyyy-MM-dd **HH:**mm:ss"` and if this failed, we just try parse AM/PM format `"yyyy-MM-dd **hh**:mm:ss"`.

**Comment by jsouhail** [comment]
ohhh... ok great... it worked... thanks a lot
