### ISSUE TITLE
Crash in DateInRegionFormatter with custom allowedComponents

### ISSUE THREAD

**Issue by davidganster** [malcommac/SwiftDate#537]
Hi,

when using `DateInRegionFormatter` with custom `allowedComponents`, I get a crash because of the forced unwrap in line 150: https://github.com/malcommac/SwiftDate/blob/a6ec382004f45f45a78b172d0a85a6594a0054ae/Sources/SwiftDate/DateInRegionFormatter.swift#L150

It turns out the `value` of `cmp` is `NSDateComponentUndefined`, which seems to produce the crash.
When I `po cmp`, I get:
```
(lldb) po cmp
▿ isLeapMonth: false 
  - isLeapMonth : false
```

Here is a full sample that reproduces the bug:
```
let date1 = DateInRegion(absoluteDate: Date().add(components: [.day : 1]))
let date2 = DateInRegion(absoluteDate: Date())
let formatter = DateInRegionFormatter()
formatter.allowedComponents = [.month, .day] // commenting out this line gets rid of the crash
let string = try? formatter.timeComponents(from: date1, to: date2)
```

It doesn't seem to matter what the `allowedComponents` are set to.

**Comment by malcommac** [comment]
Cannot support SwiftDate 4.x anymore. Please refer to 5.x branch
