### ISSUE TITLE
problem with pod

### ISSUE THREAD

**Issue by orlanczyk** [malcommac/SwiftDate#54]
Hi I installed the library with a pod file and could not use it only when I imported the file itself to the project using Xcode 7.
is there a known issue? solution?

Thanks,
Gal

**Comment by abunur** [comment]
am also having an issue recently trying to update via pod update: "Unable to load a podspec from `SwiftDate.podspec`"

**Comment by camel113** [comment]
Hey I can not use SwiftDate. Here is my sample project https://github.com/camel113/testSwiftDate

I can not access swift date methods. I use CocoaPods 0.39.0 and Xcode  7.2.1
