### ISSUE TITLE
is there a way to get start date and end date of year ?

### ISSUE THREAD

**Issue by Jay-iTechPioneer** [malcommac/SwiftDate#540]
suppose today is 2018-04-07 and i want to get start date = 2018-01-01 and  end date =  2018-12-31

**Comment by malcommac** [comment]
Since SwiftDate 5.x you had `dateAtEnd()` and `dateAtStart()`.

From doc:

> ## 3.9 - Date at start/end of time component
> Two functions called `.dateAtStartOf()` and `.dateAtEndOf()` allows you to get the related date from a `Date`/`DateInRegion` instance moved at the start or end of the specified component.
> 
> You can, for example, get the date at the start of the week, or the year, or a the end of the quarter.
> 
> - `func dateAtStartOf(_ unit: Calendar.Component) -> DateInRegion`: return the date at the start of the specified time component.
> - `func dateAtEndOf(_ unit: Calendar.Component) -> DateInRegion`: return the date at the end of the specified time component.

**Comment by RajChanchal** [comment]
What if I wish to start the week always from Monday?

`someDate.dateAtStartOf(.weekOfMonth)`

The above function considers start of week on Sunday for my region i.e UAE. But I want it always be Monday everywhere. Therefore, there is difference of one day in UAE but if used in some other region where week starts from Monday, it works fine as desired. 

How to resolve it?
