### ISSUE TITLE
Xcode 10 Beta, iOS 12: Crash

### ISSUE THREAD

**Issue by richardtop** [malcommac/SwiftDate#549]
![image](https://user-images.githubusercontent.com/8013017/40978089-63108646-68db-11e8-84e5-95f4eb3da878.png)

**Comment by majid701** [comment]
Got the same problem here. Any one who knows how to fix or any workarounds?

**Comment by richardtop** [comment]
Due to changes in iOS 12 the bundle couldn't be loaded at the constructed path. The loading process has to be fixed.

**Comment by jweihs** [comment]
Not beautiful neither working for non-cocoapods integrations, but it's working for me to continue developing.

Change **Line 103** in file **Localization.swift**

```
private class func resourceBundle() -> Bundle? {
     let framework = Bundle(for: DateInRegion.self)
     [...]
} 
```

to

```
private class func resourceBundle() -> Bundle? {
    var framework: Bundle!
    if #available(iOS 12.0, *) {
        framework = Bundle(identifier: "org.cocoapods.SwiftDate")
    }
    else {
        framework = Bundle(for: DateInRegion.self)
    }
    [...]
}
```

**Comment by inket** [comment]
You can simply replace
```swift
let framework = Bundle(for: DateInRegion.self)
```

with 

```swift
let framework =
    Bundle(identifier: "org.cocoapods.SwiftDate") ??
    Bundle(identifier: "com.SwiftDate.SwiftDate-iOS") ??
    Bundle(identifier: "com.SwiftDate.SwiftDate-macOS") ??
    // etc.
    Bundle(for: DateInRegion.self)
```

**Comment by swordray** [comment]
Still crashed with `let framework = ...`.
