### ISSUE TITLE
Methods isAfterDate, isBeforeDate from Date+Compare extension ignores "orEqual" argument

### ISSUE THREAD

**Issue by gsagadyn** [malcommac/SwiftDate#553]
Due to missing pass of argument "orEqual", mentioned methods returns an unexpected result.

Current implementation:
`
public func isAfterDate(_ refDate: Date, orEqual: Bool = false, granularity: Calendar.Component) -> Bool {
	return self.inDefaultRegion().isAfterDate(refDate.inDefaultRegion(), granularity: granularity)
}
`

Correct implementation:
`
public func isAfterDate(_ refDate: Date, orEqual: Bool = false, granularity: Calendar.Component) -> Bool {
	return self.inDefaultRegion().isAfterDate(refDate.inDefaultRegion(), orEqual: orEqual, granularity: granularity)
}
`

**Comment by malcommac** [comment]
Thank you

**Comment by malcommac** [comment]
5.0.1 Released. I'll close it.
