### ISSUE TITLE
toString/toFormat not using device region (differences between SwiftDate 4.x/5.x in Default Region)

### ISSUE THREAD

**Issue by steelzeh** [malcommac/SwiftDate#556]
In the earlier versions we had `.string(custom: "")`
As i've read up on the new documentations it is clear that we should use toFormat or toString.
But this results in wrong region.

```swift
Date().toString(.custom("HH:mm")) = 11:37
Date().toFormat("HH:mm") = 11:37
```

while using the old version

```swift
Date().string(custom: "HH:mm") = 13:37
```

Seems like some different region is being used to generate the date to string.
The time locally on the iPad an therefor the `Date()` is 13:37 but the formatter formats it to 11:37?

**Comment by steelzeh** [comment]
For anyone running into this issue use this .convertTo(region: .local).toString or .convertTo(region: .local).toFormat.

I just don't see why it's automatically selecting a different region than the local region.

**Comment by malcommac** [comment]
Hi,
there is a big difference between SwiftDate 4.x and 5.x and it regards the default region.
See the doc about [Upgrading from Swift 4.x](https://github.com/malcommac/SwiftDate/blob/master/Documentation/10.Upgrading_SwiftDate4.md)

> In SwiftDate 4.x the default region is automatically set to local region, where all attributes are set automatically to the current's device's locale, timezone and calendar.
> 
> Since SwiftDate 5, in order to be more comply with Date's default behaviour, the default region's timezone is set to GMT+0 (UTC).
> 
> If you want to restore the old behaviour just set it to Region.local just after the launch of the app.
> 

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
	SwiftDate.defaultRegion = Region.local // set region to local device attributes
	// ... do something else
	return true
}
```
