### ISSUE TITLE
Fixes for Decodable protocol in DateInRegion/Region on Swift 4.2

### ISSUE THREAD

**Issue by sedwo** [malcommac/SwiftDate#559]
Just did a `pod update` and it broke my project.

![image](https://user-images.githubusercontent.com/1434449/42647678-a8f9690c-85d2-11e8-922a-7a2c2d76004c.png)

**Comment by vaibhav-varshaaweblabs** [comment]
Same here

**Comment by sedwo** [comment]
@malcommac Well, it still seems to fail for me in the same way.
Running Sierra and Xcode 9.2.
I'll monitor it.

**Comment by vaibhav-varshaaweblabs** [comment]
Same here

MacOS Sierra - Version 10.12.6 (16G1036)
XCode - Version 9.2 (9C40b)

**Comment by Bawenang** [comment]
Hi, I'm using 5.0.7 and this bug is still there.

MacOS Sierra - Version 10.12.6
XCode - Version 9.0

**Comment by malcommac** [comment]
Sure it still here, you need to update to 5.0.9, otherwise you still get the same problem :)

**Comment by waploaj** [comment]
> Sure it still here, you need to update to 5.0.9, otherwise you still get the same problem :)

Hi, i'm  using 6.0.1 and this bug is still here
