### ISSUE TITLE
[Bug]  incorrect preWeek and nextWeek calculation

### ISSUE THREAD

**Issue by hao-li** [malcommac/SwiftDate#561]
https://github.com/malcommac/SwiftDate/blob/8c042f874875b72320e60b416846b315ba646d61/Sources/SwiftDate/DateInRegion/DateInRegion%2BCreate.swift#L406-L409

I think the value of dateByAdding should be -1 and 1.

**Comment by thedjinn** [comment]
Can confirm that changing -7 and 7 to -1 and 1 respectively works correctly.

**Comment by malcommac** [comment]
Thank you for reporting. Fixed in 5.0.5
