### ISSUE TITLE
isInSameDayOf method missing in latest version

### ISSUE THREAD

**Issue by YuvarajManickam** [malcommac/SwiftDate#564]
Today updated my "SwiftDate" framework through CocoaPod. The latest version "5.0.4 updated from 4.0.13". After the framework update, I got three errors and resolved two. But, I couldn't find the equivalent method for the existing method "isInSameDayOf". Am getting following error message,

  `Value of type 'Date' has no member 'isInSameDayOf'  SwiftDate 5.0.4 (was 4.0.13)
`
Could you please help me to resolve this? Thanks.

**Comment by malcommac** [comment]
Comparison methods are now part of the `compare()` function and listed inside the enum called `DateComparisonType`.
So your function is:
`... = self.compare(.isSameDay(otherDate))`

or one of the shortcuts:
```
.isToday
.isTomorrow
.isYesterday
```
More on this topic can be found inside the doc:
https://github.com/malcommac/SwiftDate/blob/master/Documentation/4.Compare_Dates.md
