### ISSUE TITLE
Differences in Years/Months/days between two dates

### ISSUE THREAD

**Issue by OuSS-90** [malcommac/SwiftDate#565]
Hi, is possible to have the difference between two date like "2 months, 3days"
I tried with this (date1 - date2) but i got wrong result:

****************************************
date1: 2018-08-02 15:45:03 +0000
date2: 2018-06-13 00:00:00 +0000
era: 0 year: 0 month: 1 day: 6 hour: 15 minute: 45 second: 3 nanosecond: 908911865 weekday: 0 weekdayOrdinal: 0 quarter: 0 weekOfMonth: 0 weekOfYear: 2 yearForWeekOfYear: 0 isLeapMonth: false 
****************************************

The difference between those two date it's 51 DAYS so it should have 1 month and 20 days but i have 1 month and 6 days

**Comment by malcommac** [comment]
You should use `toUnits()` method.

```swift
let date1 = "2018-08-02T15:45:03+0000".toISODate()!
let date2 = "2018-06-13T00:00:00+0000".toISODate()!
let diff = date1.timeIntervalSince(date2).toUnits([.month,.day])
```

**Comment by arkilis** [comment]
Still you have to decide by yourself on how many days in year and in month. Would be easy to have some method `.diffDays()`

**Comment by olegtatarciuc** [comment]
To get the number of days since a specific date, use this:
```
let daysSince = date1.timeIntervalSince(date2).toUnit(.day)
```
It will return an optional Int with the total days between 2 dates.
