### ISSUE TITLE
[SwiftDate 4.x] Convert UTC dateString into local timezone dateString in custom format in SwiftDate ~ '4.5.1'

### ISSUE THREAD

**Issue by SuhasDPatil** [malcommac/SwiftDate#569]
how do I convert UTC dateString into local timezone dateString with custom format in SwiftDate ~ '4.5.1'

Thanks in advance.

**Comment by bstillitano** [comment]
Anything on this?

**Comment by malcommac** [comment]
I'm unable to support both the new and old SwiftDate.
BTW I can merge PRs about the old 4.x branch to publish fix updates.
