### ISSUE TITLE
Use Nick Lockwood's SwiftFormat vs SwiftLint.

### ISSUE THREAD

**Issue by UncleRic** [malcommac/SwiftDate#571]
Take a look at: https://github.com/nicklockwood/SwiftFormat as a replacement for SwiftLint.

**Comment by phoney** [comment]
Why do this? Swiflint enforces a coding style and additionally has rules about poor coding practices. Swiftlint is widely used. Why change?

**Comment by malcommac** [comment]
What’s the main reason to prefer SwiftFormat in you opinion?
