### ISSUE TITLE
Why DateInRegion(seconds:) and DateInRegion(milliseconds:) uses Region.UTC?

### ISSUE THREAD

**Issue by FSMaxB-divae** [malcommac/SwiftDate#572]
This bit me because it is very surprising, since every other initializer uses the default region, except those two.

It's probably impossible to change this now because it would break existing applications, but maybe in the future if there is a new major release?

**Comment by malcommac** [comment]
Both of these initializer are resembles of the plain `Date`'s init and must be coherent with them (where the seconds is specified to the absolute date - like UTC).
If you need of a different behaviour you can still pass another `region` instead of the default's `Region.UTC`.

**Comment by FSMaxB-divae** [comment]
Thanks for the explanation. Makes sense, still surprising though.
