### ISSUE TITLE
Fallback to language when language+region option for toRelative() func does not exist

### ISSUE THREAD

**Issue by Vancion** [malcommac/SwiftDate#575]
Hi, I use Relative Date Formatting with `someString.toRelative(locale: Locale.current)` in my project and find out that when I change iOS system language, the output does not change at all. So I did some digging, it seems like it caused by `private func language(forLocale locale: Locale) -> RelativeFormatterLang`

My iPhone setting: 
Language: Simplified Chinese
Region: US

Locale would be
```
Printing description of locale:
▿ zh-Hans_US (current)
  - identifier : "zh-Hans_US"
  - kind : "current"
```
localeId from locale.collatorIdentifier is zh-Hans-US and it does not match anything in  `self.languagesMap[localeIdWihoutRegion]` so that it would fall back to english. 

I also test with some other language, e.g. Japanese
Language: Japanese
Region: US

```
someString.toRelative(locale: Locale(identifier: Locale.preferredLanguages.first!))
Printing description of locale:
▿ ja-US (fixed)
  - identifier : "ja-US"
  - kind : "fixed"
```

localeId from locale.collatorIdentifier is ja-US.

It seems like we can strip the region part of locale string(**-US**) so that the above example would become **zh-Hans** and **ja** and works. Or maybe if the check `guard let tableType = self.languagesMap[localeIdWihoutRegion]` fails, we can remove the region part and check again.

I also think identifier of lang_zh.identifier in languagesMap should be "zh-Hans" instead of "zh", but I cannot find more infomation about it at the moment.

Thanks.

**Comment by iGranDav** [comment]
I have the same issue with french `fr_FR` and I think identifier used for regions is indeed false due too the `locale.collatorIdentifier` used.

In current code `lang_fr_CA` uses `fr_CA` as identifier, it should probably be `fr-CA` instead.

Before falling back to english I propose to try with a locale language code before. For example with locale `fr_FR` :
 * `locale.collatorIdentifier` is `fr-FR` => nothing corresponds
 * `locale.languageCode` is `fr` => lang_fr corresponds 🎉 

Using @Vancion example with locale `zh-Hans_US` :
 * `locale.collatorIdentifier` is `zh-Hans-US` => nothing corresponds
 * `locale.languageCode` is `zh` => lang_zh corresponds 🎉 

English should be the latest escape case.
