### ISSUE TITLE
SwiftDate 5 equivalent of .prevWeek(at: .start)

### ISSUE THREAD

**Issue by avjiang** [malcommac/SwiftDate#576]
Migrating from previous version to version 5 is really confusing as I couldn't find almost all of the documentation.

What is the equivalent of the .prevWeek method?

i used to call it like this 

```swift
 self.fromDate = todaysDate.prevWeek(at: .start).string(custom: self.dateFormat)
 self.toDate = todaysDate.prevWeek(at: .end).string(custom: self.dateFormat)
```

This library is very helpful to me. Very good library!

Hope someone can help me

Thanks!

**Comment by malcommac** [comment]
The same method is available under the `dateAt()` umbrella function.
More info in [Manipulate Date](https://github.com/malcommac/SwiftDate/blob/master/Documentation/3.Manipulate_Date.md#relateddates) section of the documentation.

Your code can be translated to SwiftDate 5 as:

```swift
 self.fromDate = todaysDate.dateAt(at: .prevWeek).toFormat(self.dateFormat)
 self.toDate = todaysDate.dateAt(at: .prevWeek).toFormat(self.dateFormat)
```

**Comment by avjiang** [comment]
Hi how can I get the start and the end of previous month based on your reply? It seems same for both lines. Thanks

**Comment by joeljfischer** [comment]
I found this in the update guide

`DateInRegion: startOf() and endOf() are now replaced by dateAtStartOf() and dateAtEndOf()and include support for both single and multiple units.`

**Comment by malcommac** [comment]
My fault sorry:

```swift
let todaysDate = Date() // 2018-10-26T21:00:00Z
let startOfPrevWeek = todaysDate.dateAt(.prevWeek)
let endOfPrevWeek = startOfPrevWeek.dateAt(.endOfWeek)
print(startOfPrevWeek.toISO()) // 2018-10-14T00:00:00Z
print(endOfPrevWeek.toISO()) // 2018-10-20T23:59:59Z
```
