### ISSUE TITLE
Date's toFormat() ignores Locale

### ISSUE THREAD

**Issue by JeankyWang** [malcommac/SwiftDate#578]
```swift
let dateStr = date.toFormat("yyyy-MM-dd", locale: Locales.current)
```

change different locales get same result

**Comment by malcommac** [comment]
I'm not sure what are you trying to accomplish.
Locale in your format cannot affect the results, all of your format params are numeric.
Try to use a localizable value as the name of the month.
See the example below:

```swift
let dateStr = Date().toFormat("yyyy MMMM dd", locale: Locales.english) // 2018 August 23
let dateStr2 = Date().toFormat("yyyy MMMM dd", locale: Locales.italian) // 2018 Agosto 23
```

More info about format table can be found into the [documentation](https://github.com/malcommac/SwiftDate/blob/master/Documentation/7.Format_UnicodeTable.md).
