### ISSUE TITLE
Type 'DateinRegion' does not conform to protocol 'Decodable'

### ISSUE THREAD

**Issue by devansh1110** [malcommac/SwiftDate#589]
Hi... 

The above issue is arising again in SwiftDate 5.0.0, and 5.0.8 right now. Attached is a picture of the error. This is an issue in the demo files as well. 
![44520758-6ff70400-a703-11e8-9a95-503101264fdf](https://user-images.githubusercontent.com/20267529/45401339-2fade600-b61e-11e8-8889-92cef80b4c75.png)

This is occuring in Swift 4.0. Please advice ASAP whenever possible. 

Thanks

**Comment by devansh1110** [comment]
Please advice...

**Comment by malcommac** [comment]
5.0.8 was not released.
5.0.7 and earlier still have the bug but in develop branch it was fixed:

```swift
	/// Formatter used to transform this object in a string. By default is `nil` because SwiftDate
	/// uses the thread shared formatter in order to avoid expensive init of the `DateFormatter` object.
	/// However, if you need of a custom behaviour you can set a valid value.
	public var customFormatter: DateFormatter? = nil
```

would you try to compile the current develop branch?

**Comment by devansh1110** [comment]
I'm getting the following error twice from the develop branch: 

> Expression pattern of type 'String' cannot match values of type 'ISOParser.ISOChar?' (aka 'Optional<Unicode.Scalar>')

>
