### ISSUE TITLE
Version 5.0.0  does not support Linux

### ISSUE THREAD

**Issue by Antonasg** [malcommac/SwiftDate#590]
Specifically because of:  
`import ObjectiveC.runtime` 
In `AssociatedValues.swift` 

It should be stated clearly in the Readme if the plan is to no longer support Linux by using the ObjectiveC runtime.

**Comment by malcommac** [comment]
Duplicate of #568 
Currently I'm working to restore it by disabling the Objective-C Runtime dependency.
