### ISSUE TITLE
Xcode 10.0 swift 4.2

### ISSUE THREAD

**Issue by UNIQUEXJ** [malcommac/SwiftDate#591]

**Comment by boardmain** [comment]
broken :/

**Comment by malcommac** [comment]
Have you tried 5.0.9?

**Comment by UNIQUEXJ** [comment]
ok! thanks

**Comment by manuelsBTS** [comment]
Hello. I would like to know if you are going to release a version for Swift 4.2

**Comment by malcommac** [comment]
Did you get warnings on 4.2?

**Comment by manuelsBTS** [comment]
<img width="351" alt="screen shot 2018-09-19 at 12 06 57 pm" src="https://user-images.githubusercontent.com/42077660/45773034-e60d5e80-bc0e-11e8-9ba2-ca095b8fe6d4.png">

I got that @malcommac
