### ISSUE TITLE
Support for arm64_32 architecture in Xcode 10

### ISSUE THREAD

**Issue by WillAnd31** [malcommac/SwiftDate#594]
Building SwiftDate using Carthage fails because in `SwiftDate/Supports/Commons.swift` the method `combineHashValues` doesn't account for the architecture type: `arm64_32` which seems to have been added in Xcode 10. 

RxSwift ran into this same problem and this is how they fixed it:
https://github.com/ReactiveX/RxSwift/pull/1740/files

**Comment by malcommac** [comment]
Added in #595 thanks
