### ISSUE TITLE
Refactoring for hashValue in DateInRegion, fixed compiler error on watchOS target

### ISSUE THREAD

**Issue by yillars** [malcommac/SwiftDate#596]
I'm getting this error message when I compile on watch extension target.

`iPhone7 + Apple Watch Series 2(WatchOs: 5.0 (16R364))`

`Pods`->`SwiftDate`->`Commons.swift`->`combineHashValues(_:_:)`

<img width="705" alt="screen shot 2018-09-20 at 11 22 13" src="https://user-images.githubusercontent.com/2271107/45792151-8cb53600-bcc7-11e8-80ef-4315f8900bc6.png">

**Comment by Maxim-Inv** [comment]
I'm getting this error too.

**Comment by malcommac** [comment]
I had removed old `hashValue` generator function since it was now managed automatically by Swift 4.2.
