### ISSUE TITLE
Differences between two dates as DateComponents via componentsSince() method in DateInRegion

### ISSUE THREAD

**Issue by Tibbs** [malcommac/SwiftDate#597]
This worked in 5.0.7
`(date1 - date2).hour` as stated in the Readme no longer compiles

Now it gives this error:
`Value of type 'TimeInterval' (aka 'Double') has no member 'hour'`
`date1 - date2` used to be DateComponents but in 5.0.9 it's time interval

I tried to use the `toUnit(.minute)` function but it gives me the whole interval in minutes instead of the minute component

Thank you

**Comment by malcommac** [comment]
Hi,
You are right, it was restored to `TimeInterval` to be consistent with plain `Date`.
Since 5.0.11 you will use `componentsSince()` method in `DateInRegion`:

```
let hour = date2.componentsSince(date1).hour
```
