### ISSUE TITLE
How to calculate the differences between two dates in preferred time unit (day, month etc.)

### ISSUE THREAD

**Issue by grifas** [malcommac/SwiftDate#599]
I would like to get the time interval between now and a date in the future so I tried that:

`po "2018-10-05T06:30:00+00:00".toDate()!.date - Date()` // Date() = September 20 2018

Result:

```
▿ era: 0 year: 0 month: 0 day: 0 hour: 18 minute: 55 second: 10 nanosecond: 380929931 weekday: 0 weekdayOrdinal: 0 quarter: 0 weekOfMonth: 0 weekOfYear: 2 yearForWeekOfYear: 0 isLeapMonth: false 
  - era : 0
  - year : 0
  - month : 0
  - day : 0
  - hour : 18
  - minute : 55
  - second : 10
  - nanosecond : 380929931
  - weekday : 0
  - weekdayOrdinal : 0
  - quarter : 0
  - weekOfMonth : 0
  - weekOfYear : 2
  - yearForWeekOfYear : 0
  - isLeapMonth : false
```

So between this two dates, result should be have `day : 15`. 

What is wrong ?

**Comment by malcommac** [comment]
You should use `getInterval(toDate:component:)` method ([documentation](https://github.com/malcommac/SwiftDate/blob/master/Documentation/3.Manipulate_Date.md#32---get-interval-between-dates))

```swift
let fromDate = "2018-09-20T00:00:00+00:00".toDate()!
let toDate = "2018-10-05T06:30:00+00:00".toDate()!
let diffDays = b.getInterval(toDate: a, component: .day) // 15 days
```

the difference between two date since 5.0.9 returns an interval like for plain dates.
