### ISSUE TITLE
Operators doesn't work

### ISSUE THREAD

**Issue by bitomule** [malcommac/SwiftDate#6]
I want to use 

````
date+1.months
````

But I get an:

````
Binary operator '+' cannot be applied to operators of type 'NSDate' and 'MonthCalendarType'

I'm on Swift 1.2

**Comment by bitomule** [comment]
I've created a PR

https://github.com/malcommac/SwiftDate/pull/7

**Comment by malcommac** [comment]
Okay just merged, thank you

**Comment by bitomule** [comment]
No problem. Awesome work btw.

**Comment by bitomule** [comment]
Oh, can you update the version on cocoapods? :)

**Comment by malcommac** [comment]
yup, pushed 1.0.6 right now
