### ISSUE TITLE
How to use ColloquialDateFormatter, colloquialSinceNow in SwiftDate 5.x

### ISSUE THREAD

**Issue by AjayHegdeK** [malcommac/SwiftDate#601]
Hi,

ColloquialDateFormatter, colloquialSinceNow is removed in the latest version do u have exact replacement for this.

I have seen similar option using toRelative for relative time formatting, but I am not able use date as an object in its second parameter as given in ur example.
In my case I have two date components, I need difference between than, the difference might result in minutes, hours or days whatever comes code should work and show. 
ex: 4 hours ago.  ex: 4 days ago, ex:  just now.
How can I solve this any suggestion.

**Comment by malcommac** [comment]
Have you seen the https://github.com/malcommac/SwiftDate/blob/master/Documentation/5.Date_Formatting.md#colloquial inside the documentation for colloquial formatting options?
