### ISSUE TITLE
Crash in RelativeFormatter when gradation was not found

### ISSUE THREAD

**Issue by RamblinWreck77** [malcommac/SwiftDate#602]
Hello! We recently released an update using 5.0.9 and have started getting crashes. 

The issue seems to be line 329 in RelativeFormatter.swift

filteredGradation's force unwrap apparently can be nil, I'm trying to work through what kind of input can result in this now and will update this as soon as I know. 

Edit: Here's where the crash is occurring in our code. Style gets made, however once replaceDate.roRelative() is called the crash occurs. 

```
let now: Date = Date().dateRoundedAt(at: .toCeilMins(60))
let style = RelativeFormatter.Style(flavours: [.long], gradation: .convenient(), allowedUnits: [.day])
let relative = replaceDate.toRelative(since: now.in(region: .current), style: style, locale: Locale.current)
```
In this case, 

now = 2018-09-28 18:00:00 UTC
replaceDate = 2018-05-14 04:00:00 UTC	

Edit2: 

it appears this line:
```
let i = findGradationStep(elapsed: elapsed, now: referenceInterval, gradation: filteredGradation)
```

For the above dates, i is -1 which doesn't make sense

```
guard i >= 0 else {
            return nil
        }
```

fixed the crash

**Comment by malcommac** [comment]
Can you help me identify the bug? What locale are you using?

**Comment by RamblinWreck77** [comment]
Sure! I'm using 

`SwiftDate.defaultRegion = Region.local`

In my app delegate if that's important. 

Local.current = "en_US"

**Comment by malcommac** [comment]
And what's the language of the device, the value of local?

**Comment by RamblinWreck77** [comment]
en_US

**Comment by RamblinWreck77** [comment]
Wooo! Thanks for fixing this! Closing :)
