### ISSUE TITLE
[SwiftDate 4.x] Non-valid date string 'toDate(format:)' call throws an exception

### ISSUE THREAD

**Issue by Machipla** [malcommac/SwiftDate#603]
Hi there,

I've found that if you do this simple line 
`let test = "72".date(format: .iso8601Auto)?.absoluteDate`
the app throws an error at "ISO8601Parser.swift" line 799.

It's dangerous if we're expecting data from, for example, a JSON where could come a malformed String.

Maybe it's a good idea to check that the string to transform is indeed a Date?
I'm missing something?

Using SwiftDate (4.5.1)

**Comment by malcommac** [comment]
I'm unable to support both the new and old SwiftDate.
BTW I can merge PRs about the old 4.x branch to publish fix updates.
