### ISSUE TITLE
Added ms parameter to dateBySet() function to alter the milliseconds value of a date

### ISSUE THREAD

**Issue by laxmorek** [malcommac/SwiftDate#606]
Let's say I have a date:
`10.10.2018 12:02:16.024` 
and I want to update milisec value to 7, so my result should looks like this:
`10.10.2018 12:02:16.007`

I tried to use:
`date.dateBySet([.nanosecond: 7])`
without success

Is is a bug? Lack of functionality? I can't find proper method. Can you help me? 

For now I created `Date` extension as a workaround:
```swift
func set(milisec: Int) -> Date {
    var timestamp = timeIntervalSince1970.rounded(.down)
    timestamp += Double(milisec) / 1000.0
    
    return Date(timeIntervalSince1970: timestamp)
}
```

**Comment by malcommac** [comment]
Hi,
Since 5.0.12 both `Date` and `DateInRegion` `dateBySet()` function has an extra `ms` optional parameter you can use to set the milliseconds value of the receiver.

```swift
let originalDate = "2018-10-10T12:02:16.024".toISODate()!
let newDate = originalDate.dateBySet(hour: nil, min: nil, secs: nil, ms: 7)
print(newDate.toISO()) // 2018-10-10T12:02:16.007Z
```
