### ISSUE TITLE
Best way to format dates for display purposes

### ISSUE THREAD

**Issue by andreaslindahl** [malcommac/SwiftDate#614]
I have looked trough the documentation but haven't found any mentions about formatting dates while taking the current region, locale and timezone into account. 

I display dates in various forms throughout my app and when for example using `myDate.toFormat("HH:mm")` to display the time of a date, this is displayed as GMT even though my device is GMT+1. To get the time displayed in the current timezone of the device I do this:

```
let dateRegion = DateInRegion(myDate, region: Region.current)
dateRegion.toString(.time(.short))
```

This works, but is there an easier way, without having to create a DateRegion with the current region everytime?

When working with dates and formatting them to, for example, send them to my API, always having them as GMT seems logical, but when DISPLAYING dates it would be nice if the current regional settings of the device would be used by default.

**Comment by hustlzp** [comment]
I have to write those codes in 6.0.x:

```swift
myDate.in(region: Region(zone: TimeZone.current)).toFormat("yyyy-MM-dd")
```

while the build-in `DateFormatter` uses the system timezone  by default:

https://developer.apple.com/documentation/foundation/dateformatter/1411406-timezone
