### ISSUE TITLE
Swift 4 Compilation Failure

### ISSUE THREAD

**Issue by glbotu2** [malcommac/SwiftDate#615]
XCode Version: 9.2
MacOS Version: 10.12
Swift Version: 4.0
Compile for iOS
SwiftDate Version 5.0.9.
Build Target 11.2

Build Fails on `ISOParser.swift` lines 338 and 341 claiming:
`Expression of type 'String' cannot match values of type 'ISOParser.ISOChar?' (aka 'Optional<Unicode.Scalar>')`

Any help would be much appreciated.

**Comment by purkylin** [comment]
swift 4.2
