### ISSUE TITLE
Carthage Build Fails for version 5.0.13

### ISSUE THREAD

**Issue by peymankh** [malcommac/SwiftDate#618]
This is due to the linter throwing errors on a build phase task.

**Comment by yasuradodo** [comment]
@peymankh @jgarciatt 
Delete `Carthage/Checkouts/SwiftDate` and then update carthage.
I don't know exactly what's wrong, but this should help you.

**Comment by jgarciatt** [comment]
@yasuradodo Thanks, but I've done that but it does not works.

**Comment by jgarciatt** [comment]
I'm using Xcode 9 still, could that affect the compilation process of the library?

**Comment by jgarciatt** [comment]
It looks like the latest version is not compatible with Xcode 9 and the swift version I have, I', downgrading to 5.0.5 that was the one I used since the beginning and everything works. I will update after we migrate to Xcode 10.
