### ISSUE TITLE
date.toRelative() returns empty string for languages which have not a full set of plural rules

### ISSUE THREAD

**Issue by anton-kaliuzhnyi-altexsoft** [malcommac/SwiftDate#630]
If some language has not a full set of plural rules `SwiftDate` returns an empty string ("") from `date.toRelative()`.

For example, for Russian **"2 hours ago"** is not returned at all, because it falls to a **"few"** rule which is absent in the dictionary:

```
public class lang_ru: RelativeFormatterLang {
	// ...
	private var _long: [String: Any] {
		return [
		"hour": [
		"current": "в этот час",
		"past": [
			"one": "{0} час назад",
			"many": "{0} часов назад",
			"other": "{0} часа назад"
		],
	// ...
```

**Comment by 0xMarK** [comment]
The fix is available in Pull Request https://github.com/malcommac/SwiftDate/pull/631

**Comment by malcommac** [comment]
Accepted, on track for 5.1.0. Thanks
