### ISSUE TITLE
how to set the time to be the same as my zone if using SwiftDate pod?

### ISSUE THREAD

**Issue by AgungLaksana** [malcommac/SwiftDate#633]
I need to format this string date: "2019-01-18 10:14:52" to another string in format like this: 18 Jan 2019 - 10:14.

I use SwiftDate pod to format that string date using the code below:

```swift
import SwiftDate

func convert(date: String, toFormat: String) -> String {
    let userRegion = Region(calendar: Calendars.gregorian, zone: Zones.asiaJakarta, locale: Locales.indonesian)
    let convertedDate = date.toDate() ?? DateInRegion(Date(), region: userRegion)
    let userDateRegion = convertedDate.convertTo(region: userRegion)
    return userDateRegion.toFormat(toFormat, locale: Locales.indonesian)
}
```
But the time is always wrong. I expect to get 18 Jan 2019 - 10:14 but I always get 18 Jan 2019 - 17:14 in simulator.

It is always 7 hours more from the actual time. I suspect because I am in Indonesia now which is GMT+7. How to solve this issue?

**Comment by clay-mindoula** [comment]
me too:
```
        log.debug(Date().toFormat("hh:mm:ss a"))
        log.debug(Date().description(with: .current))
```
output:
```
 > 09:56:43 PM
 > Saturday, January 26, 2019 at 1:56:45 PM Pacific Standard Time
```
