### ISSUE TITLE
How to parse "tue jul 30 21:49:40 gmt+01:00 2019" with SwiftDate

### ISSUE THREAD

**Issue by lekeCoder** [malcommac/SwiftDate#637]
I really need help with this. I need to be able to convert string date to Date in swift. SwiftDate failed to convert throwing nil exception.

**Comment by malcommac** [comment]
Take a look at the [Unicode Table](https://github.com/malcommac/SwiftDate/blob/master/Documentation/7.Format_UnicodeTable.md) for parsing.

```swift
let region = Region(calendar: Calendars.gregorian, zone: TimeZone(secondsFromGMT: 0)!, locale: Locales.english)
let y = "tue jul 30 21:49:40 gmt+01:00 2019"(formatter.dateFormat, region: region)
```
