### ISSUE TITLE
How to strict date parsing (isLenient) in SwiftDate

### ISSUE THREAD

**Issue by midhunpmohan** [malcommac/SwiftDate#639]
when i trying to convert `30-2-2016` from string to date it is giving result as `2016-03-01` instead of getting failure 

```swift
"30-2-2016".toDate("dd-MM-yyyy", region: .local)
```

**Comment by malcommac** [comment]
Hi,
By default the date formatter does an heuristic parse of the date (I'm talking of the `isLenient` parameter of the `DateFormatter` class).
If you need of a strict date parsing this is the correct way to handle it in SwiftDate:

```swift
 let date = "30-2-2016".toDate(style: .strict("dd-MM-yyyy"), region: Region.local) // return nil
```
