### ISSUE TITLE
Misunderstanding how date components works with timezone and time calculations

### ISSUE THREAD

**Issue by roma86** [malcommac/SwiftDate#64]
First, thank you for good library. 

I am very stupid with dates, maybe you can explain me what i miss.

```
let justDate = NSDate()
let localDate = NSDate().toLocalTime()
let hongkongDate = NSDate().toTimezone("HKT")!
let westEurDate = NSDate().toTimezone("MSK")!
let futureDate = justDate + 4.hour

L.d("justDate: \(justDate) (\(justDate.hour) : \(justDate.minute))")
L.d("localDate: \(localDate) (\(localDate.hour) : \(localDate.minute))")
L.d("hongkongDate: \(hongkongDate) (\(hongkongDate.hour) : \(hongkongDate.minute))")
L.d("westEurDate: \(westEurDate) (\(westEurDate.hour) : \(westEurDate.minute))")
L.d("futureDate: \(futureDate) (\(futureDate.hour) : \(futureDate.minute))")
```

Output is strange for me.

> justDate: 2015-10-20 18:53:47 +0000 (21 : 53)
> localDate: 2015-10-20 15:53:47 +0000 (18 : 53)
> hongkongDate: 2015-10-21 02:53:47 +0000 (5 : 53)
> westEurDate: 2015-10-20 21:53:47 +0000 (0 : 53)
> futureDate: 2015-10-20 22:53:47 +0000 (1 : 53)

This code was run on iPhone, not simulator. Real local time in time zone **MSK** was **21:53**

Minutes are save in every case. Hours different, but has wrong values, as i see.

The target of this experiment is get hours and minutes of date in specific timezone. 

What i am doing wrong?

**Comment by Hout** [comment]
Actually NSDate is an absolute time. It is the same everywhere around the world. Without Swiftdate you can represent it by calculating a local time through NSCalendar or NSDateFormatter. There you use a calendric system (Georgian, Islamic, Hebrew, Buddhist etc) the time zone and locale.

The first line (``justDate``) is correct. It is the time in UTC (indicated by the +0000). This is the same as GMT which is UK time in winter (in summer it is BST which is summer time). In Hong Kong it is five hours later apparently. With SwiftDate use ``justDate.toString()`` to display the date in local time.

**Comment by roma86** [comment]
@Hout thank you for comment. I know about NSDate UTC feature. This topic not about. 
This topic about SwiftDate api exactly. My example show that toTimezone work not as it name suggests. 
Or i misunderstand how to use it. What i should to do if i want add 4 hours to time in HKT zone?
It is very organic to convert date to target zone, increase hours and get result. But But result is not as expected.

**Comment by malcommac** [comment]
I think I've understand your question.
Suppose to consider only justDate with the current UTC date. Here are 19:20 (GMT+1) so 18:20 (UTC).

```
let justDate = NSDate()
print("justDate: \(justDate) (\(justDate.hour) : \(justDate.minute))")
```
Result is:  "18:20:50" (from printing ```justDate```) plus "19" as hour (from ```justDate.hour```) and "20" as minutes (from ```justDate.minute```), while you are expecting 18 as ```justDate.hour```. Right?

**Comment by malcommac** [comment]
The problem is with
```
private var components: NSDateComponents {
	return  NSCalendar.currentCalendar().components(NSDate.componentFlags(), fromDate: self)
}
```

We need to set the timezone also in NSCalendar.currentCalendar.
In fact if we set the UTC timezone here the resulting time components are correct (hour return 18 instead of 19 in our previously example)

**Comment by malcommac** [comment]
We could store the timezone abbreviation into the NSDate object when it return ```.toTimezone("HKT")!``` or ```.toLocalTime()``` method and set the calendar timezone according to it.
I'm not sure about it (store the timezone inside NSData which should be considered time independent).
Any better idea?

**Comment by roma86** [comment]
@malcommac I think you understand me right. One more explanation:
![playground](https://api.monosnap.com/rpc/file/download?id=BgEseqGkfYLqtfkJ5VM5Cb6LYKkAdC)

I need this to calculate feature date
i am solving this like so
```
    /**
    Return date time of day in minutes
    */
    public func timeInMinutesInMoscow() -> Int {
        let cal = NSCalendar.currentCalendar()
        let components = cal.componentsInTimeZone(NSTimeZone(abbreviation: "MSK")!, fromDate: self)
        return components.hour * 60 + components.minute
    }
```

**Comment by roma86** [comment]
[This is link to my playground](https://drive.google.com/open?id=0Bw-eomJ7SS0ET0UySWp5NmpwekU)

**Comment by malcommac** [comment]
In fact Apple allows you to return cal.componentsInTimeZone while we are using components to simply get components always in UTC (the standard format for NSDate instance).
I'm not sure what's the best solution.
We can emulate the same behaviour of Apple but something like minutes/hours/...InTimezone seems a bit ugly and put the timezone within the NSDate object is the same.
I need to think about it a while, if anyone has an elegant solution is welcome of course :)

**Comment by Hout** [comment]
To keep things pure, I think you should treat NSDate objects as absolute time objects, not as a representation in a certain time zone (or calendar, for the matter). 

I suggest that you determine times based on time zones in string represenations or NSDateComponent elements. Let me see...

**Comment by Hout** [comment]
For .toString, I would add optional calendar and time zone parameters:
```
func toString(blahblah, calendar: NSCalendar = NSCalendar.currentCalendar,  timeZone: NSTimeZone = NSTimeZone.defaultTimeZone) 
```
Make sure to add variations of the call to the test class.

**Comment by Hout** [comment]
For components I suggest a ``func components(blahblah, calendar: etc etc etc`` (you get the idea?)

**Comment by Hout** [comment]
Of course you could use the time zone abbreviation as opposed to a tz object.
Or the calendar identifier for calendar...

**Comment by Hout** [comment]
The charm of your extension is that is can be treated as NSDate. Unfortunately you cannot store vars in an extension, so the time zones and calendars have to come with the call. An alternative would be to subclass NSDate, but that causes all kind of different issues as NSDate is a class cluster. Apple describes how to subclass but when you get further down the road it gets rather complicated.

I played around with this and came up with a [class](https://github.com/Hout/JHDate) (yes I gave it a shot with cocoapods), but this class serves another purpose than SwiftDate as it does not have the straight NSDate connection.

**Comment by malcommac** [comment]
I think I'll make another branch to move SwiftDate from a simple NSDate wrapper to a separate class which can store more (including timezone); something like Moment.js or your class.
We will lose the ability to work directly with NSDate objects but it should move the project to a whole new level.

**Comment by Hout** [comment]
Agreed. 
I would be happy to rebabtise JHDate to something like a ¿DateRepresentation? class smoothly fitting right next to a NSDate extension in the SwiftDate environment. My intention is just to learn Swift, not to start a competition. ;-)
We would have to decide what function fits where. I will check out moment.js this weekend but I would suggest some class that can be connected to an NSDate object for a local representation of that NSDate object? The class would contain a calendar, time zone and locale.

**Comment by malcommac** [comment]
The new version of SwoftDate introduced the concept of DateInRegion: this class encapsulate an UTC NSDate for a particular world's region (along with locale and calendar settings)z
Time zone conversion is now easier than ever; thank you for your report and thank you to @Hout for its help making this new revamped version of SwoftDate.
Hope you will like it, feel free to submit your reports or requests.
