### ISSUE TITLE
Parsing ISO-8601 formatted week dates fails

### ISSUE THREAD

**Issue by kenosan** [malcommac/SwiftDate#643]
Hi, 
It seems parsing of [ISO-8601 Week dates](https://en.wikipedia.org/wiki/ISO_8601#Week_dates) is not working. The following code returns `nil` with SwiftDate v5.1.0 

```swift
SwiftDate.defaultRegion = Region.current
print("Date = \(DateInRegion("2019W02"))")
print("Date = \(DateInRegion("2019-W02"))")
```
I also tried changing the default region to ISO but there was no difference. Stepping through the code, it seems that `GGGG-[W]WW` does not work for `DateFormats.builtInAutoFormat`

**Comment by malcommac** [comment]
Thank you, just fixed it.
