### ISSUE TITLE
Comparing with <= function

### ISSUE THREAD

**Issue by sameer4** [malcommac/SwiftDate#645]
I have 2 days to compare and 

```swift
object.lastCalled + callGap.minutes <= Date()
```

returns false when 2 dates are same 

logs using

```swift
print("sam full dates \(object.lastCalled + callGap.minutes) <= \(Date()) = \(object.lastCalled + callGap.minutes <= Date())")`
```

results in

`sam full dates 2019-03-01 11:05:03 +0000 <= 2019-03-01 11:05:03 +0000 = false`

**Comment by MadGeorge** [comment]
@sameer4 Hi. It's not obvious from your example the dates in example are the same. Maybe milliseconds are different. Print to log output dates in default format which ends with seconds only.

Buy the way, it's hard to read and understand your example. Especially log output is cryptic with all this interpolations (interpolation is handy in minimal usage, but all this backslashes and parentheses made expression hard to read). What is `object.lastCalled` and `callGap.minutes`? We need example with with clear explanation so it can be reproduced and tested on our side.

**Comment by sameer4** [comment]
sorry for inconvenience 

object is an object from database with lastCalled as attribute of Date type...to store when it was called last time...

callGap is an Int type variable to store how much gap is allowed between object calls...     .minutes is from your library to convert Int to date components

and about "Print to log output dates in default format which ends with seconds only"

they are in default format.i'm not applying any formatter on them

`2019-03-01 11:05:03 +0000 <= 2019-03-01 11:05:03 +0000 = false`

First date is of last call
then after <=
date is from last call + callGap(in minutes)

and after = is result of comparison..

hope this helps....let me know if i can help you for further details

**Comment by sameer4** [comment]
SwiftDate must be latest as i update pod on daily bases 

i'm using realm for database and not sure about storing millisecond

thanks for explaining...must be millisecond issue...

i just changed the condition check from language to database query...so working fine now...

thanks for the help

**Comment by malcommac** [comment]
You're welcome.
Thanks.
