### ISSUE TITLE
the result of "toRelativeString" can be returned  in chinese?

### ISSUE THREAD

**Issue by chelsh** [malcommac/SwiftDate#65]
```
let string = date.toRelativeString(fromDate: nil, abbreviated: false, maxUnits:2)
This example tell to SwiftDate to return a relative representation of the date by comparing it to the current date (nil in fromDate means NSDate()) without using an abbreviated form (use "seconds" not "secs", or "years" not "ys") and with a max number of units of 2 (this is used to get the approximation units to print, ie "2 hours, 30 minutes" are 2 units, "2 hours, 30 minutes, 5 seconds" are 3 units).

```

the result of "toRelativeString" can be returned  in chinese? example: 2分钟

**Comment by malcommac** [comment]
I don't know how it should be. Did you know how to implement this request?

**Comment by malcommac** [comment]
Anyway I would to mantain a language independent tool. A better solution is to execute this operation outside the library (See http://stackoverflow.com/questions/15076443/convert-numbers-in-chinese-characters-to-arabic-numbers, it's in objc btw).
We could provide a dictionary or a struct which can return seconds/minutes/hours/days/months/years you can convert easily.

**Comment by xiajinchun** [comment]
@chelsh 
You can custom an extension for SwiftDate and then copy `toRelativeString` function, and only one thing you do is implement `_sdLocalizeStringForValue` function like this:
```swift```
    func _sdLocalizeStringForValue(unit: NSCalendarUnit) -> String {
        var toTranslate : String = ""
        switch unit { 
        case NSCalendarUnit.Year:		toTranslate = "年"        
        case NSCalendarUnit.Month:		toTranslate = "月"      
        case NSCalendarUnit.WeekOfYear:	toTranslate = "周"       
        case NSCalendarUnit.Day:		toTranslate = "天"       
        case NSCalendarUnit.Hour:		toTranslate = "小时"      
        case NSCalendarUnit.Minute:		toTranslate = "分"      
        case NSCalendarUnit.Second:		toTranslate = "秒"       
        default:						toTranslate = ""
        }
        return toTranslate._sdLocalize
    }
```
This is also my implementation way.

**Comment by Hout** [comment]
No need for proprietary code, check the [docs](https://developer.apple.com/library/prerelease/ios/documentation/Foundation/Reference/NSDateComponentsFormatter_class/index.html#//apple_ref/occ/clm/NSDateComponentsFormatter/localizedStringFromDateComponents:unitsStyle:)

**Comment by Hout** [comment]
This needs some investigation. It should not be very complicated to create local unit descriptors.
Also check out [link](https://github.com/mluedke2/camelot/blob/master/ResearchKit/ResearchKit/Common/ORKOrderedTask.m) and search for `NSDateComponentsFormatterUnitsStyleSpellOut`

**Comment by malcommac** [comment]
we can continue this discussion in #79
