### ISSUE TITLE
Date().toISO([.withoutTZSeparators]) empty string

### ISSUE THREAD

**Issue by freedoom1984** [malcommac/SwiftDate#656]
If I use this method `Date().toISO([.withoutTZSeparators])` I get no result.
If I use this method `Date().toISO()` the string is corrected

**Comment by malcommac** [comment]
Thanks for the report, the problem happens because `withoutTZSeparators` does not work if not paired with `withInternetDateTimeExtended`.
It was fixed.
Now this is the result of both calls:

```swift
Date().toISO([.withoutTZSeparators]) // 2019-04-16T16:28:06.049+0000
Date().toISO() // 2019-04-16T16:28:06Z
```
