### ISSUE TITLE
How to format Date/DateInRegion in 12/24 hour format regardless device's date setting

### ISSUE THREAD

**Issue by alexberlato** [malcommac/SwiftDate#661]
iOS 12.2 / SwiftDate 6.0.1 / Xcode 10.2 / Swift 5

Calling .toFormat("HH:mm:ss") lead to results that depend on iOS 24/12h time setting.
For example, with the 24h format off from phone settings, the date is formatted as "10:01:32 AM", even if with the specified format "10:01:32" is expected.

Is this something wanted?
Shouldn't the specified format override the current locale settings?

**Comment by malcommac** [comment]
If you want to force 24hour clock you need to set the locale to POSIX.

```swift
print(Date().toFormat("HH:mm:ss", locale: Locales.englishUnitedStatesComputer))
// or
print(Date().toFormat("HH:mm:ss", locale: Locale(identifier: "en_US_POSIX"))
```

**Comment by alexberlato** [comment]
Thank you for the feedback!
I've already been able to make it work by passing a locale, I opened the issue because I've found strange that an explicitly set format is overridden by the default locale.

**Comment by malcommac** [comment]
You're welcome. Unfortunately it's a behaviour of iOS and it's the same with pure `NSDate` objects.
