### ISSUE TITLE
Type 'UInt32' has no member 'random'

### ISSUE THREAD

**Issue by waploaj** [malcommac/SwiftDate#663]
Am using dateswift version 6.0.1 after pod install, am getting this error on DateinRegion+Create.swift that UInt32 has no member 'random'
```

static func randomDate(region: Region = SwiftDate.defaultRegion) -> DateInRegion {
		let randomTime = TimeInterval(UInt32.random(in: UInt32.min..<UInt32.max))
		let absoluteDate = Date(timeIntervalSince1970: randomTime)
		return DateInRegion(absoluteDate, region: region)
	}
```

**Comment by malcommac** [comment]
Are you using Swift < 4.2. Number's random functions were introduced in 4.2 and SwiftDate 6 is compatible only from 4.2 to higher.
