### ISSUE TITLE
Xcode [10.2] SwiftDate [6.0.2] Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by JosePeriban** [malcommac/SwiftDate#667]
![Screen Shot 2019-04-23 at 4 10 19 PM](https://user-images.githubusercontent.com/49926470/56621911-1ec94800-65e3-11e9-99cc-91b749d38462.png)

**Comment by JosePeriban** [comment]
Debug-iphoneos/name.app/Frameworks/SwiftDate.framework: No such file or directory

**Comment by malcommac** [comment]
I think your issue is related to Cocoapods configuration and not to SwiftDate.
Double check your Swift and XCode version, then check cocoapods configuration.
Probability SwiftDate is the first framework built in your configuration and therefore its the first reported error.
