### ISSUE TITLE
The pad for zero is wrong for toClock()

### ISSUE THREAD

**Issue by libern** [malcommac/SwiftDate#668]
The pad for zero is wrong.

```
26100.toClock()         //   ->   7:15:00
```

It should be like 

```
07:15:00
```

According to Apple Foundation Documentation:

```
public static var pad: DateComponentsFormatter.ZeroFormattingBehavior { get } 

// Off: "1:0:10", On: "01:00:10" 
```

**Comment by malcommac** [comment]
For some strange reasons padding is not added automatically by the `DateComponentsFormatter` on the very beginning positional item. I had fixed it manually when necessary.
Thanks for the report.

**Comment by libern** [comment]
Thanks!
