### ISSUE TITLE
Not able to archive 

### ISSUE THREAD

**Issue by pratik6554** [malcommac/SwiftDate#67]
Hi, I am not able to archive. Also tried with ExampleProject. 

Error : Command failed due to signal: Segmentation fault: 11

0  swift                    0x0000000111a8337b llvm::sys::PrintStackTrace(__sFILE*) + 43
1  swift                    0x0000000111a83abb SignalHandler(int) + 379
2  libsystem_platform.dylib 0x00007fff9497552a _sigtramp + 26
3  libsystem_platform.dylib 0x0000000000000010 _sigtramp + 1802021632
4  swift                    0x000000011128554a llvm::DwarfCompileUnit::applyVariableAttributes(llvm::DbgVariable const&, llvm::DIE&) + 74
5  swift                    0x000000011128a318 llvm::DwarfDebug::finishVariableDefinitions() + 376
6  swift                    0x000000011128a67e llvm::DwarfDebug::finalizeModuleInfo() + 126
7  swift                    0x000000011128a9b4 llvm::DwarfDebug::endModule() + 52
8  swift                    0x0000000111270b9a llvm::AsmPrinter::doFinalization(llvm::Module&) + 554
9  swift                    0x00000001118f5f7b llvm::FPPassManager::doFinalization(llvm::Module&) + 59
10 swift                    0x00000001118f6487 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 1207
11 swift                    0x000000010fc7a8ce performLLVM(swift::IRGenOptions&, swift::DiagnosticEngine&, llvm::sys::SmartMutex<false>*, llvm::Module*, llvm::TargetMachine*, llvm::StringRef) + 1454
12 swift                    0x000000010fc7ab01 swift::performLLVM(swift::IRGenOptions&, swift::ASTContext&, llvm::Module*) + 145
13 swift                    0x000000010fb747f5 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&) + 501
14 swift                    0x000000010fb743f3 frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2691
15 swift                    0x000000010fb70a74 main + 2324
16 libdyld.dylib            0x00007fff94ad85ad start + 1
17 libdyld.dylib            0x0000000000000010 start + 1800567396

**Comment by malcommac** [comment]
Cannot reproduce the same error err with XCode 7.1 and iOS 9.1.
Maybe a problem with ENABLE_BITCODE ?

**Comment by pratik6554** [comment]
Cool..g8 :)
