### ISSUE TITLE
Is Swift 5 support planned ?

### ISSUE THREAD

**Issue by AlaeddineOuerteni** [malcommac/SwiftDate#673]

**Comment by malcommac** [comment]
SwiftDate 6.x branch is compatible with Swift 5.

**Comment by AlaeddineOuerteni** [comment]
I can't find the branch 6.x

**Comment by malcommac** [comment]
Current version (6.x) is on develop, on master you found the latest published release.
Each release has its own tag.

Daniele Margutti
Software Architect

mobile: (+39) 328.36.45.178
mail: hello@danielemargutti.com
web: http://www.danielemargutti.com
skype: daniele.margutti
