### ISSUE TITLE
Value of type 'String.Index' has no member 'utf16Offset'

### ISSUE THREAD

**Issue by julianfe** [malcommac/SwiftDate#674]
When trying to compile to virtual device

/Pods/SwiftDate/Sources/SwiftDate/Foundation+Extras/TimeInterval+Formatter.swift:106:64: 
Value of type 'String.Index' has no member 'utf16Offset'

`if let index = formattedValue.firstIndex(of: ":"), index.utf16Offset(in: formattedValue) < 2 {`

XCode Version 10.1 (10B61)

**Comment by RomanPodymov** [comment]
Hello @julianfe 
Could you please try to build your project with Xcode 10.2.1?

**Comment by julianfe** [comment]
HI, I'm away with terrible adsl, I'll update in about two weeks when I'm back, and let you know

**Comment by TristanSingleton** [comment]
Hello @RomanPodymov,

I am also not able to build SwiftDate V6.0.3 with XCode 10.3. Please let me know if I need to change anything else.

**Comment by RomanPodymov** [comment]
@julianfe As you can see in [documentation](https://developer.apple.com/documentation/swift/string/index/3151849-utf16offset) `utf16Offset(in:)` is available in Xcode 10.2+. Please upgrade your Xcode instance and close the issue.

**Comment by RomanPodymov** [comment]
@TristanSingleton What error do you get?

**Comment by TristanSingleton** [comment]
I had updated my Xcode to 10.3 prior to posting. Error reads: Value of type 'String.Index' has no member 'utf16Offset'

**Comment by RomanPodymov** [comment]
@TristanSingleton Do you have only 1 Xcode instance installed on your Mac?

**Comment by TristanSingleton** [comment]
Only one instance of xcode

**Comment by RomanPodymov** [comment]
@TristanSingleton The following code is compiling in Xcode 10.2+: `let success = Result<Int, NSError>.success(0)`. Can you compile it in your Xcode instance?

**Comment by julianfe** [comment]
Upgrading XCode as you suggest and it fixed the issue

**Comment by RuchiMakadia** [comment]
work after Upgrading XCode thank you @RomanPodymov
