### ISSUE TITLE
How to support SPM in XCode 11 with Resources

### ISSUE THREAD

**Issue by dstranz** [malcommac/SwiftDate#678]
Steps to reproduce:
* Add `SwiftDate` as SPM dependency in Xcode 11
* Add code with relative (localized) date formatting
* Run app

Expected results:
* App should load language specific settings from `langs/(ID).json` file

Current results:
* App is crashing because file couldn't be loaded.

It looks like 
`let fullURL = Bundle(for: RelativeFormatter.self).resourceURL?.appendingPathComponent("langs/\(langID).json")` generates path for Host App Bundle.

**Comment by RamblinWreck77** [comment]
Can confirm. Project crashes inside SwiftDate when installed via SPM, but it's good in Cocoapods. 

@malcommac Since Xcode 11 is now "Gold Master" and this error is still occurring do you think you could take a look at it? I imagine there will be a ton of issues on the 19th once it's live otherwise. 

Thanks for a kick ass library :)

**Comment by malcommac** [comment]
As far I know SPM does not support Resources copying (https://bugs.swift.org/browse/SR-2866).
Did you know some tricks or workaround?

**Comment by RamblinWreck77** [comment]
Would this work?

`
If binary size is not a concern. Embed resource files in a source file as base 64 encoded data in a string literal. (A tool of mine, Workspace 4, can automate this.) Then as long as the source file is checked in, the resources will be embedded in the executable and available no matter how the package is used. This allows you to treat the files as resources during development, but they are technically no longer separate resources after compiling. (The annoying binary bloat is why I watch this thread so closely, hoping for a better future.)
`

https://forums.swift.org/t/swift-pm-bundles-and-resources/13981/50

**Comment by RamblinWreck77** [comment]
SE-0271 looks to be addressing this:

https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md

**Comment by RamblinWreck77** [comment]
^The above SE has been implemented for Swift 5.3

**Comment by malcommac** [comment]
fixed in 6.2.0
