### ISSUE TITLE
create nsdate object is not working?

### ISSUE THREAD

**Issue by poppindouble** [malcommac/SwiftDate#68]
Hello, thanks for your library, but i got a bug when i tried the things below
let tempDate = NSDate.date(fromString: "22/01/2015", format: DateFormat.Custom("DD/MM/YYYY"))
print(tempDate)

the result is:
Optional(2014-12-21 05:00:00 +0000)

**Comment by malcommac** [comment]
Just fixed doc; you should use ```dd/MM/yyyy``` as format (see the doc at the end of the README file)
