### ISSUE TITLE
Relative time formatter doesn't work as advertised?

### ISSUE THREAD

**Issue by danqing** [malcommac/SwiftDate#684]
In README there's the following example:

```swift
let _ = (Date() - 3.minutes).toRelative(style: RelativeFormatter.twitterStyle(), locale: Locales.english) // "3m"
```

This is exactly what I want, but if I use the exact same setup, I get `3 min. ago`. How can I get `3m`?

**Comment by danqing** [comment]
Actually this is changed [1] from what I hope it is (and what it is in README) to the new behavior? Is this intended @malcommac ?

[1]: https://github.com/malcommac/SwiftDate/commit/fab16785406722135dda4284ad5024da74e403f3

**Comment by danqing** [comment]
In https://github.com/malcommac/SwiftDate/commit/aa067ddbe5e0851f1ddcf8c72645a135bde68937 the JSON files don't include the advertised behavior.

It would be great if this is either documented or fixed. This looks like a breaking change not mentioned anywhere (or maybe I missed it). Thanks!

**Comment by danqing** [comment]
(checked and it worked as intended in 6.0.2)

**Comment by malcommac** [comment]
We have switched to the old good localized strings :) I'm sorry for this bad behaviour.

**Comment by danqing** [comment]
Hmm I'm still getting the wrong strings with 6.1. When is it fixed?

**Comment by vburojevic** [comment]
Having the same issue, not getting "3m" like in README.
For hours i.e. I get "11 hr. ago".
