### ISSUE TITLE
Construct Region object with custom TimeZone/Locale

### ISSUE THREAD

**Issue by NeedNap** [malcommac/SwiftDate#685]
I am trying my swift app on a iOS 13 beta environment.
I have a macOS Mojave machine with XCode 11.0 installed.
The default "machine" regional settings and the swift function TimeZone.current.identifier return "US/Pacific".
When I try to get the region I use the following statement:
`let r = Region(calendar: Calendars.gregorian, zone: Zones(rawValue: TimeZone.current.identifier)!, locale: Locales(rawValue: appLanguage)!)`

but the enum Zones "creation" fails because the raw value "US/Pacific" is not present in the list.
What can I do to solve this error?
Do I use the library in a wrong way?

Thanks

**Comment by malcommac** [comment]
Both `Zones` and `Locales` are just shortcuts and the `Region` structure accepts all `LocalesConvertible` and `ZoneConvertible` objects; `TimeZone` and `Locale` are objects conforms to these protocol so you can just pass instances of these objects to construct your `Region`:

```swift
 let region = Region(calendar: Calendars.gregorian, zone: TimeZone.current, locale: Locale.current)
```

**Comment by NeedNap** [comment]
Sorry for my late replay: this solve the problem!
Thank you very much.
