### ISSUE TITLE
Compiler generated crash 

### ISSUE THREAD

**Issue by GhaisB** [malcommac/SwiftDate#686]
![Capture d’écran 2019-07-12 à 15 10 01](https://user-images.githubusercontent.com/5504674/61130638-64e1c980-a4b7-11e9-9153-ec5b780b5e6d.png)

It's seems that there is a crash related to keys of dictionary's in RelativeFormatterLanguage.

I don't have any additionnel informations so here's the stack :)

**Comment by GhaisB** [comment]
Any news on this ?

**Comment by malcommac** [comment]
I've not encountered it by compiling with XCode 11. Are you still experiencing it?

**Comment by GhaisB** [comment]
Well, some of our users encountered it (4 on 500-600) but only on iOS 12 !
