### ISSUE TITLE
DateFormatter object from NSDate.cachedObjectInCurrentThread is modified causing different return results from some functions.

### ISSUE THREAD

**Issue by wfilleman** [malcommac/SwiftDate#69]
Hello,

Thank you for this excellent library. It certainly does make working with dates quite a bit more pleasant.

Ran into an issue where calling .toISOString() changes the dateFormatter timezone and date format from the default/cached dateFormetter. Subsequent calls to .toShortString(), for example, ends up using the modified dateFormatter from .toISOString() resulting in unexpected short/medium/long string prints of the time now based on UTC instead of the user's local timezone.

Once suggestion is to always set the dateFormatter defaults each time the dateFormatter object is retrieved or make sure each func that modifies the cachedDateFormatter returns it back to the "found" state.

Wes

**Comment by malcommac** [comment]
We have fixed it with SwiftDate 2. Thank you for your report.
