### ISSUE TITLE
Set WeekFirstDay not working version 5.1.0

### ISSUE THREAD

**Issue by sathishvgs** [malcommac/SwiftDate#690]
```
        var cal = Calendar.current
        cal.firstWeekday = 2 // 2 represents Monday
        cal.timeZone = Zones.gmt.toTimezone()
        cal.locale = Locales.englishUnitedStates.toLocale()
```
I would like to set the week first day as Monday but the above which worked in swift 4 is not working after migrating to swift 4.2. So, Kindly can you check it once.

**Comment by malcommac** [comment]
I'm not sure what you would to accomplish.
Can you post

**Comment by greyder** [comment]
Hi @malcommac, also would like to know the answer to this. 
How can we set the first day of week when using SwiftDate? since firstDayOfWeek is only a get property.

**Comment by Vignesh-Thangamariappan** [comment]
I need to set the week start date based on user preference. For example: if the user selected Tuesday as the week start date. I want to make sure all computations for the week happen based on that.  I am using dateAtStartOf(.week) and dateAtEndOf(.week) throughout my project.
Currently, i tried setting the firstWeekDay in this way
`var calendar = Calendar.autoupdatingCurrent
  calendar.firstWeekday = 3
  let region = Region(calendar: calendar, zone: userTimezone, locale: Locale.autoupdatingCurrent)
  SwiftDate.defaultRegion = region`
But it seems to fail, since the default calendar is returned in any instance of Date.
Could you please provide a way to set a week start day? It would be really helpful

**Comment by VladOrackle** [comment]
> I need to set the week start date based on user preference. For example: if the user selected Tuesday as the week start date. I want to make sure all computations for the week happen based on that. I am using dateAtStartOf(.week) and dateAtEndOf(.week) throughout my project.
> Currently, i tried setting the firstWeekDay in this way
> 
> > var calendar = Calendar.autoupdatingCurrent
> > 'calendar.firstWeekday = 3'
> > 'let region = Region(calendar: calendar, zone: userTimezone, locale: Locale.autoupdatingCurrent)'
> > 'SwiftDate.defaultRegion = region`
> 
> But it seems to fail, since the default calendar is returned in any instance of Date.
> `Currently in v6.1.0`
> @malcommac Could you please provide a way to set a week start day? It would be really helpful

I have the same problem. I really need to let the user change the first weekday, but passing  the configured "Calendar" to "Region" initializer always returns "firstWeekday" based on locale

**Comment by mribeiro** [comment]
@Vignesh-Thangamariappan did you manage to solve this? I'm having the same challenge.
Thanks

**Comment by TimGrell** [comment]
I have the same problem.
I can't modify `firstWeekday` and `minimumDaysInFirstWeek` because of `Region`'s initializer.
There we have:
```swift
	public init(calendar: CalendarConvertible = SwiftDate.defaultRegion.calendar,
				zone: ZoneConvertible = SwiftDate.defaultRegion.timeZone,
				locale: LocaleConvertible = SwiftDate.defaultRegion.locale) {
		self.calendar = Calendar.newCalendar(calendar, configure: {
      print($0.firstWeekday, $0.minimumDaysInFirstWeek) // Correct values

			$0.timeZone = zone.toTimezone()
			$0.locale = locale.toLocale()

      print($0.firstWeekday, $0.minimumDaysInFirstWeek) // Incorrect values

      // Manually set the values
      $0.firstWeekday = calendar.toCalendar().firstWeekday
      $0.minimumDaysInFirstWeek = calendar.toCalendar().minimumDaysInFirstWeek

      print($0.firstWeekday, $0.minimumDaysInFirstWeek) // Correct values
		})
	}
```
It seems to me that after any change to `Calendar`'s properties in the `configure` closure, all of my settings are reset. 
But if I change the values after that, everything works as expected.

**Comment by Vignesh-Thangamariappan** [comment]
Thanks @TimGrell. This looks to be a good fix. Can you please make these changes in a separate branch and push it to the repo. Once they merge your changes, It would be a great addition in the next update of Swift Date.

**Comment by Elshir** [comment]
Is there a way to change `firstWeekday` in current version of SwiftDate? I have the same problem about it.

**Comment by suwenclub** [comment]
> Is there a way to change `firstWeekday` in current version of SwiftDate? I have the same problem about it.

me too

**Comment by Elshir** [comment]
> > Is there a way to change `firstWeekday` in current version of SwiftDate? I have the same problem about it.
> 
> me too

I've figured it out myself by setting Calendars.gregorian or the other to make it change programmatically, hope this help you somehow.

**Comment by BagmetDenis** [comment]
Сan you give an example of how you overcame this bug ?

**Comment by suwenclub** [comment]
> Сan you give an example of how you overcame this bug ?

var calendar = Calendar.init(identifier: .gregorian)
calendar.firstWeekday = 2
SwiftDate.defaultRegion = Region(calendar: calendar,
                                         zone: TimeZone.autoupdatingCurrent,
                                         locale: Locale.autoupdatingCurrent)
// print SwiftDate.defaultRegion.calendar.firstWeekday then got 1

**Comment by ExtremeMan** [comment]
There used to be a convenient method for that (https://github.com/malcommac/SwiftDate/compare/4.5.1...5.0.0#diff-4ddb0e769834923d6d637cfe9c9974c5d6d2c0e17c1703ac9ec3b7eaae5f68a9L89-L96). Maybe we can bring it back as a fix?

**Comment by Vignesh-Thangamariappan** [comment]
@BagmetDenis @Elshir @suwenclub  You can temporarily use my forked version in which the firstWeekDay works as expected. Here is a link for reference: https://github.com/Vignesh-Thangamariappan/SwiftDate
