### ISSUE TITLE
How to add/remove component values from date

### ISSUE THREAD

**Issue by linxi5547371** [malcommac/SwiftDate#691]
```swift
let now = Date()
let yesterday = now.dateAtStartOf(.day).dateBySet([.hour: -24]) //it‘s right
let yesterdayError = now.dateAtStartOf(.day).dateBySet([.day: -1]) //it's strange
print(yesterday) //Optional(2019-08-26 00:00:00 +0000)
print(yesterdayError) //Optional(2019-07-30 00:00:00 +0000)
```
When the dict key is set `.day` , yesterday is error.

**Comment by malcommac** [comment]
You are *setting* a component neither *adding* or *subtracting* value from component (specifically to hour=-24 and day=-1 which clearly does not make sense).
I think you would to use `dateByAdding()` function instead.
