### ISSUE TITLE
Converting Date into regions

### ISSUE THREAD

**Issue by RajChanchal** [malcommac/SwiftDate#699]
### My understanding:

Please check following:
My current time zone is GMT +4, the time now is: 2019-08-03 12:27:51

`let date = Date()`

if I print date, it will print 2019-08-03 08:27:51 because, as per my understanding, `Date()` is irrespective any region - thus seems to print UTC +00 time

### What I want:

I want my date variable to have 2019-08-03 12:27:51 instead of 2019-08-03 08:27:51, how can I convert the UTC date to my region date.
Please note, I want it in `Date` type variable - not as String.

### What I tried:
```
let date = Date()
let dateInUTCRegion = date.in(region: .UTC)
let dateInCurrentRegion = dateInUTCRegion.convertTo(region: .current)
print(dateInCurrentRegion.date)
```

But it again prints the same as the `date` variable does. I seems like the convertTo just converts the `region` variable of `DateInRegion` class

**Comment by AndreiBoariu** [comment]
@RajChanchal Here is how I did it, and it works brilliant!
`class func getCustomStringDateFromDate(_ date: Date, region: Region? = nil, format: String) -> String? {
		if let newRegion = region {
			return date.in(region: newRegion).toFormat(format)
		}
		
		return date.toString(.custom(format))
	}`

`if let date = Utils.getCustomStringDateFromDate(message.sentDate, region: Region.local, format: "MMM d") {
				strDate = date
			}`
