### ISSUE TITLE
Comparing time unit shortcuts (hours/minute...) with DateComponents

### ISSUE THREAD

**Issue by RolandasRazma** [malcommac/SwiftDate#706]
Probably not a bug but bit unexpected

```swift
SwiftDate.defaultRegion = .local

let now = Date()
        
print(
    (now.addingTimeInterval(3600) - now).in(.hour) == 1,
    (now.addingTimeInterval(3600) - now) == 1.hours
)
```

will output `true`, `false`

**Comment by malcommac** [comment]
Hi @RolandasRazma, thank you for your report.
I had fixed it just by settings non nil zero values for the remaining items of `DateComponent` instances created when using shortcuts of `.hour, .minute, .second` etc.
