### ISSUE TITLE
Rounding option in toRelativeString

### ISSUE THREAD

**Issue by matijakregar** [malcommac/SwiftDate#71]
Would it be possible to add a rounding option to ```toRelativeString```?
For example if ```maxUnits``` parameter is set to 1, the output for a date 1 hour 55 ago minutes is "1 hour". In some (maybe even most) cases it would make more sense to round the output to "2 hours".

**Comment by Hout** [comment]
@malcommac does this fit in v2?

**Comment by malcommac** [comment]
@Hout I'm not satisfied by current function. I think we could explore some alternatives; a very promising one could this: https://github.com/malcommac/SwiftDate/issues/79#issuecomment-164306647.
Then we could continue discussion in that thread.

**Comment by malcommac** [comment]
we will continue discussion about this topic (pretty date formatting) in #79
