### ISSUE TITLE
Question about year parameter in date formatting

### ISSUE THREAD

**Issue by RajChanchal** [malcommac/SwiftDate#713]
```swift
let dateString = "2019-12-30 00:00:00"`
let dateInCurrentRegion = DateInRegion.init(date, format: "YYYY-MM-dd HH:mm:ss", region: .current)
```

When I print it like:

```swift
print(dateInCurrentRegion?.toFormat("YYYY-MM-dd HH:mm:ss"))
```

The output is: **2021-12-30 00:00:00**

But I am expecting it to be:  **2019-12-30 00:00:00**

**Comment by mcrowder65** [comment]
I was getting some weird year issues as well when using `.toFormat`, I was expected `12/31/2019`, and `12/31/2020` was getting printed, I followed the advice listed here: https://github.com/malcommac/SwiftDate/issues/632, and I used `yyyy` instead, and it solved my problems.

**Comment by justdan0227** [comment]
so why does this not work then?

>         
let challengeStartDate = "02-10-2020".toDate("MM-dd-yyyy")        
        let dateFormatterPrint = DateFormatter()
        dateFormatterPrint.dateFormat = "MM-dd-yyyy"
Retult string is	"02-09-2020"

**Comment by nhunghuynhthihong** [comment]
Hi, I am facing the same issue on 'SwiftDate', '6.1.0':
I was expected  `31 12 2020` but it returned `31 12 2021`

(lldb) po DateInRegion("2020-12-31T12:37:34.000Z")?.toFormat("dd MM YYYY")
▿ Optional<String>
  - some : "31 12 2021"

But it returned correct for `year` and date is smaller or equal 27:

`(lldb) po DateInRegion("2020-12-31T12:37:34.000Z")?.year
▿ Optional<Int>
  - some : 2020`

`(lldb) po DateInRegion("2020-12-27T12:37:34.000Z")?.toFormat("dd MM YYYY")
▿ Optional<String>
  - some : "27 12 2020"`
Here is my current region:
`(lldb) po Region.current
▿ {calendar='gregorian', timezone='Asia/Kuala_Lumpur', locale='en_VN'}
  ▿ calendar : gregorian (autoupdatingCurrent)
    - identifier : gregorian
    - kind : "autoupdatingCurrent"
    ▿ locale : Optional<Locale>
      ▿ some : en_VN (autoupdatingCurrent)
        - identifier : "en_VN"
        - kind : "autoupdatingCurrent"
    ▿ timeZone : Asia/Kuala_Lumpur (autoupdatingCurrent)
      - identifier : "Asia/Kuala_Lumpur"
      - kind : "autoupdatingCurrent"
      ▿ abbreviation : Optional<String>
        - some : "GMT+8"
      - secondsFromGMT : 28800
      - isDaylightSavingTime : false
    - firstWeekday : 2
    - minimumDaysInFirstWeek : 1`

**Comment by malcommac** [comment]
`YYYY` and `yyyy` are different and the output depends of your calendar type. On Non-Gregorian calendar value may be different.

The `Y*` parameter:
> Year in “Week of Year” based calendars in which the year transition occurs on a week boundary; may differ from calendar year ‘y’ near a year transition. This numeric year designation is used in conjunction with pattern character ‘w’ in the ISO year-week calendar as defined by ISO 8601, but can be used in non-Gregorian based calendar systems where week date processing is desired. The field length is interpreted in the same was as for ‘y’; that is, “yy” specifies use of the two low-order year digits, while any other field length specifies a minimum number of digits to display.

The `y*` parameter:
> Calendar year (numeric). In most cases the length of the y field specifies the minimum number of digits to display, zero-padded as necessary; more digits will be displayed if needed to show the full year. However, “yy” requests just the two low-order digits of the year, zero-padded as necessary. For most use cases, “y” or “yy” should be adequate.

More:
https://unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table
