### ISSUE TITLE
Question on weekOfMonth result between simulator and real device (iPad)

### ISSUE THREAD

**Issue by avjiang** [malcommac/SwiftDate#730]
Hello, i am facing an issue where the library returns different value 

Given date = 20 March 2020

sample code 

```swift
     let date = DateInRegion()
     let dayName = date.weekdayName(.default).uppercased()
     let weekOfMonth = date.weekOfMonth
```

Simulator returns 5 
iPad returns 6

Is there something I missed out? 

SwiftDate version 6.1.0
Simulator and iPad iOS version 13.3.1

**Comment by malcommac** [comment]
```swift
        let date = "2020-03-20".toDate()!
        let dayName = date.weekdayName(.default).uppercased()
        let weekOfMonth = date.weekOfMonth
        print(dayName)
        print(weekOfMonth)
```

return `FRIDAY` and `3` (3th week of the March). What's 5 and 6? If you are talking about the week ordinal it may differ from calendar if your first day of the week is Sunday or Monday (different setup between simulator and device).
