### ISSUE TITLE
Question about date formatting with AM/PM and format set to `h:mm a`

### ISSUE THREAD

**Issue by kazuooooo** [malcommac/SwiftDate#736]
Hi, thank you for building very useful Library 😊

I noticed toFormat method is little bit strange.
Code to reproduce here.

```swift
let a = "2020-05-20 00:00:00".toDate()
print(a?.toFormat("h:mm a")) // => Optional("12:00 AM")
```
It looks h and a are inconsistent.

I think it should be 12:00 PM or 0:00 AM.
I am happy if you can help me 🙏

**Comment by malcommac** [comment]
It's correct; let's take a look at the [Unicode Table for Date Formatting](https://unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table):

<img width="1398" alt="Screenshot 2020-09-16 at 16 25 46" src="https://user-images.githubusercontent.com/235645/93350769-486abb00-f839-11ea-873b-c9e6bb1021dd.png">
