### ISSUE TITLE
version number no longer complies with ITC

### ISSUE THREAD

**Issue by abunur** [malcommac/SwiftDate#74]
if we branch from the current Head and submit to iTunes connect, it fails because of the versioning numbers being used in the pod.  Details for this issue can be found here:

https://github.com/CocoaPods/CocoaPods/issues/4421#issuecomment-150372394

ITC is now enforcing version numbers of the format x.y.z

In my own app I was able to skirt this issue by not pulling from Head (pod 'SwiftDate', :head
), whatever version number shows up in the current release still conforms to ITC while what is showing up from head does not.

**Comment by malcommac** [comment]
Fixed since 2.0.0.
Thanks
