### ISSUE TITLE
'subscript' in 'TimePeriodGroup' should be a public function

### ISSUE THREAD

**Issue by semihunaldi** [malcommac/SwiftDate#740]
'subscript' in 'TimePeriodGroup' is not public, which cannot be accessed outside the class.
As a result, the following statement will be failed to compile.

```
let chain = TimePeriodChain()
chain.append(TimePeriod())
chain[0]  // Error: 'subscript' is inaccessible due to 'internal' protection level.
```

Any reason why it is internal?

**Comment by malcommac** [comment]
fixed in 6.2.0
