### ISSUE TITLE
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0

### ISSUE THREAD

**Issue by backslash-f** [malcommac/SwiftDate#761]
In Xcode 12: `The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99.`

Support for iOS 8 is gone for good.

Any change to bump you minimum deployment version?

Thanks.

**Comment by malcommac** [comment]
fixed in 6.3.0
