### ISSUE TITLE
Minimum iOS deployment version to 9.0 (not 12) and tvOS 9 (not 12)

### ISSUE THREAD

**Issue by qcasxy** [malcommac/SwiftDate#763]
I use Carthage to manage my dependencies. I just upgraded SwiftDate to V6.3.0
I got an error `Compiling for iOS 11.0, but module 'SwiftDate' has a minimum deployment target of iOS 12.0`
I think you are using the default minimum support for Xcode12.
Can you change the configuration? I need minimum support for iOS 11.0+
![image](https://user-images.githubusercontent.com/14816550/99248258-20043a80-2843-11eb-94a0-3bdfaf4a7bd2.png)

**Comment by cameronehrlich** [comment]
@qcasxy A work around appears to be locking the version at `v6.1.0` in your `Cartfile`.
<img width="478" alt="Screen Shot 2020-11-18 at 4 21 50 PM" src="https://user-images.githubusercontent.com/1508740/99604363-2bc63d00-29ba-11eb-9e25-4a1ee9ee6bf6.png">

**Comment by qcasxy** [comment]
> @qcasxy A work around appears to be locking the version at `v6.1.0` in your `Cartfile`.
> <img alt="Screen Shot 2020-11-18 at 4 21 50 PM" width="478" src="https://user-images.githubusercontent.com/1508740/99604363-2bc63d00-29ba-11eb-9e25-4a1ee9ee6bf6.png">

Yes, you're right. That's what I'm doing now. But this is not a long-term solution.
