### ISSUE TITLE
dateAtWeekStart returns different dates depending on the language

### ISSUE THREAD

**Issue by redent** [malcommac/SwiftDate#78]
In enUS region, `dateAtWeekStart` returns the Sunday of the current week, but that's not the week start in all cases. For example, in Spain the Sunday is the last day of the week, and thus, `dateAtWeekStart` returns the next Sunday (7 days later). To make it consistent, it should always return the same date (previous sunday) or return the first day of the week in the current calendar (previous sunday or previous monday), but never a date in the future.

It could be easily fixed changing the method from:

	func dateAtWeekStart() -> NSDate {
		let flags : NSCalendarUnit = [NSCalendarUnit.Year,NSCalendarUnit.Month ,
			NSCalendarUnit.WeekOfYear,
			NSCalendarUnit.Weekday]
		let components = NSCalendar.currentCalendar().components(flags, fromDate: self)
		components.weekday = 1 // Sunday
		components.hour = 0
		components.minute = 0
		components.second = 0
		return NSCalendar.currentCalendar().dateFromComponents(components)!
	}

to:

        // Return the immediate previous Sunday regardless of the calendar
	func dateAtWeekStart() -> NSDate {
		let flags : NSCalendarUnit = [NSCalendarUnit.Year,NSCalendarUnit.Month ,
			NSCalendarUnit.WeekOfYear,
			NSCalendarUnit.Weekday]
		let components = NSCalendar.currentCalendar().components(flags, fromDate: self)
		components.weekday = 2 // Monday
		components.hour = 0
		components.minute = 0
		components.second = 0
		return NSCalendar.currentCalendar().dateFromComponents(components)! - 1.day
	}

or even better:

    // Return the first day of the week of the current calendar
    func dateAtWeekStart(firstWeekday: Int = NSCalendar.currentCalendar().firstWeekday) -> NSDate {
        let flags : NSCalendarUnit = [NSCalendarUnit.Year,
            NSCalendarUnit.WeekOfYear,
            NSCalendarUnit.Weekday]
        let components = NSCalendar.currentCalendar().components(flags, fromDate: self)
        components.weekday = firstWeekday
        components.hour = 0
        components.minute = 0
        components.second = 0
        return NSCalendar.currentCalendar().dateFromComponents(components)!
    }

**Comment by redent** [comment]
To reproduce this issue just change the region to Spain and execute:

    NSDate().dateAtWeekStart()

It will always return a date in the future (unless already on Sunday)

**Comment by malcommac** [comment]
SwftDate 2 now includes the concept of DateInRegion which encapsulate both timezone and calendar; you should create a DateInRegion with your dat by setting your fav calendar and make the same query in order to get the correct result for called method. Thank you for your report.
