### ISSUE TITLE
Could not find module 'SwiftDate' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by Ftrybe** [malcommac/SwiftDate#787]
Could not find module 'SwiftDate' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /Users/ftrybe/Library/Developer/Xcode/DerivedData/ITime-ios-geaxfifbblgkyvfqyrhqkcgisujo/Build/Products/Debug-iphonesimulator/SwiftDate.swiftmodule。

**Comment by kiet1993** [comment]
Any supports please?

**Comment by Coryhowell** [comment]
I am also having this issue on an M1 Mac. I am able to workaround this by running Xcode in Rosetta. Are there any updates on M1 support?

**Comment by anthonydito** [comment]
@Ftrybe also running into this issue. Why did you close this issue? Were you able to resolve it?

**Comment by Ftrybe** [comment]
> @Ftrybe also running into this issue. Why did you close this issue? Were you able to resolve it?
Rosetta...
