### ISSUE TITLE
Substract 1 month doesn't work

### ISSUE THREAD

**Issue by bitomule** [malcommac/SwiftDate#8]
I'm trying to use this operator
````
public func - (left: NSDate, right: CalendarType) -> NSDate {
	let calendarType = right.copy()
	calendarType.amount = -calendarType.amount
	let calendar = NSCalendar(calendarIdentifier: NSCalendarIdentifierGregorian)!
	return calendar.dateByAddingComponents(calendarType.dateComponents(), toDate: left, options: NSCalendarOptions.allZeros)!
}
````
 but always return the same month usin:
````
date = date-1.months
````

Edit: It returns the same month with any amount.

Edit2: 

````
date.add("month",value:-1)
````

doesn't work too but I don't see why

**Comment by malcommac** [comment]
Just fixed the issue with operator and calendar types, seems to be an issue related to copy() overrides in CalendarTypes subclasses.
I'm looking to see for .add() method right now.

**Comment by malcommac** [comment]
meanwhile that's the first commit: 08ee60963ce87d056c2de2affa7c68d5c9ef9b21

**Comment by malcommac** [comment]
That's the other commit: e184276a5fc895f1837a2204c07b7a1ed10bf38a

**Comment by bitomule** [comment]
Wow, that was fast. Thanks! Is it pushed to cocoapods?

**Comment by malcommac** [comment]
Sure, 1.0.7. Thank you for your reports, I did not have not enough time right now to make unit tests for this library so your report are really valuable

**Comment by bitomule** [comment]
Thanks! I'l create more issues if I find anything
