### ISSUE TITLE
/Users/.../Documents/StuDemo/swift/package/SwiftDate-master/Sources/SwiftDate/Formatters/RelativeFormatter/langs error project: Couldn't load project at: /Users/linxiaobin/Documents/StuDemo/swift/package/SwiftDate-master/Sources/SwiftDate/Formatters/RelativeFormatter/langs

### ISSUE THREAD

**Issue by wisepmlin** [malcommac/SwiftDate#800]
/Users/.../Documents/StuDemo/swift/package/SwiftDate-master/Sources/SwiftDate/Formatters/RelativeFormatter/langs error project: Couldn't load project at: /Users/linxiaobin/Documents/StuDemo/swift/package/SwiftDate-master/Sources/SwiftDate/Formatters/RelativeFormatter/langs

**Comment by malcommac** [comment]
fixed in 7.0.0
