### ISSUE TITLE
Carthage Bootstrap Error

### ISSUE THREAD

**Issue by reallyseth** [malcommac/SwiftDate#82]
Just tried to integrate SwiftDate through Carthage, and hit this error after running `carthage update`:

```
xcodebuild: error: Scheme SwiftDate-iOS is not currently configured for the build action.
```

**Comment by malcommac** [comment]
Hi, Xcode 7 or 7.1? Are you building it for Mac or iOS?

**Comment by reallyseth** [comment]
Xcode 7.1 building for iOS.

**Comment by alpennec** [comment]
Same for me.

*** Skipped building SwiftDate due to the error:
Dependency "SwiftDate" has no shared framework schemes

I think Share should be checked in the Schemes management panel.

![screenshot 2015-11-30 18 30 00](https://cloud.githubusercontent.com/assets/2082662/11479087/73b5e726-9790-11e5-8fdc-af703001e36c.png)

**Comment by reallyseth** [comment]
I forked the repo, and tried making the scheme shared, like @alpennec suggested. Noticed that the shared scheme data was ignored by the .gitignore, so I tried adding that back in, and pointing carthage to my forked version of the repo, but still wasn't able to get it working.

**Comment by malcommac** [comment]
It's the same here, I've shared it in scheme. I'm a bit confused, should i look somewhere else?

**Comment by malcommac** [comment]
Anyone can try https://github.com/malcommac/SwiftDate/pull/84 (I'm out and cannot test it today) ?

**Comment by BernardGatt** [comment]
Issue should be fixed now, @malcommac you might need to make a new release (2.0.1)

**Comment by malcommac** [comment]
Thank you @BernardGatt . Just pushed 2.0.1. Can you check?

**Comment by alpennec** [comment]
It worked for me. No problem to build v2.0.1. Thanks @BernardGatt @malcommac 
I think this thread can be closed.

**Comment by malcommac** [comment]
Thank you again @BernardGatt. Where you set required parameters?

**Comment by BernardGatt** [comment]
No problem :)

What do you mean by set required parameters? @malcommac

**Comment by reallyseth** [comment]
Hmmmm, looks like I'm still seeing the same issue when I run `carthage update`. Also tried `carthage bootstrap` but that didn't work either. Looks like it downloaded version 2.0.1, but I'll double check. I'm on terrible wifi on a train, so it's taking a while to test...

**Comment by BernardGatt** [comment]
@reallyseth can you please go into the checkout folder, delete SwiftDate and try the update command again?

**Comment by reallyseth** [comment]
@bernardgatt that fixed the issue! Thanks so much!

**Comment by BernardGatt** [comment]
Great :+1:
