### ISSUE TITLE
Make code for autoUpdate self explanatory

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#85]
A new calendar type can be initialised with `let calType = CalendarType.Local(true)` of which functionality is unclear at first sight.
Better: `let calType = CalendarType.Local` and `let calType = CalendarType.AutoUpdatingLocal`
In addition: the current calendar is named current and not local for a reason: it is not location related but user related. if I take my European iPhone to China, the local calendar will be Chinese but my calendar will stay Gregorian (if I choose to do so).
So even better: `let calType = CalendarType.Current` and `let calType = CalendarType.AutoUpdatingCurrent`
Alternatively, if you insist on the Bool parameter: `let calType = CalendarType.CurrentWithAutoUpdate(false)`

**Comment by malcommac** [comment]
It seems reasonable; I've marked as deprecated Local and added .Current and .AutoUpdatingCurrent into current develop branch (https://github.com/malcommac/SwiftDate/commit/bafe87c350b12c9c3a501641549a446a3d09f548):
```swift
// get current system calendar (non-updating)
let nonUpdatingCalendar = CalendarType.Local
// get current system calendar (auto-updating)
let updatingCalendar = CalendarType.AutoUpdatingLocale
```
