### ISSUE TITLE
Region has no defaultRegion

### ISSUE THREAD

**Issue by reallyseth** [malcommac/SwiftDate#86]
I have added SwiftDate through carthage, which is now working on version 2.0.1, and have added an `import SwiftDate` line to the top of my Swift file that i'm working in. But when I try to use the defaultRegion() static method, I get a compiler error. 

Any help is much appreciated.

![screen shot 2015-12-01 at 8 18 48 pm](https://cloud.githubusercontent.com/assets/283616/11520417/db07649e-9868-11e5-8d2a-1f0b3e321534.png)

**Comment by reallyseth** [comment]
One more note. I'm wondering if the way carthage is building the framework, or something on my end, is not including the DataStructures.swift file. I tried initializing a region and am seeing this error as well.

![screen shot 2015-12-01 at 8 28 27 pm](https://cloud.githubusercontent.com/assets/283616/11520560/5930433a-986a-11e5-8d07-beccdd0b6add.png)

**Comment by kohdesmond** [comment]
+1

To add in @reallyseth 's question, 
let romeRegion = Region(calType: CalendarType.Gregorian, tzType: TimeZoneNames.Europe.Rome)
return an error of 'Region' cannot be constructed because it has no accessible initializers

**Comment by malcommac** [comment]
Should be fixed in 2.0.2. Let me know if it works for you. https://github.com/malcommac/SwiftDate/commit/7cca2a355650ac6b4924af807463ef0c357ab166

**Comment by reallyseth** [comment]
Fixed. Thank you so much!

**Comment by malcommac** [comment]
No problem, thank you for your report :)

**Comment by PavelGerashchenko** [comment]
same problem in 3.0.8. Or it not problem?

**Comment by Hout** [comment]
There is no `defaultRegion()` func anymore.
You can use `Region()` to get the default region but you cannot set it. Rationale is to have just one default region that represents the current calendar, time zone and locale.

If you want to use alternate regions then you should specify them and not make them the default. That prevents misunderstandings.

**Comment by PavelGerashchenko** [comment]
Thanks for answer :)
