### ISSUE TITLE
Docset - missing metadata?

### ISSUE THREAD

**Issue by abunur** [malcommac/SwiftDate#87]
what is missing in the SwiftDate docs that causes it’s name to be missing when I download it to Dash?
![screen_shot_2015-12-02_at_10_54_31_am](https://cloud.githubusercontent.com/assets/4803881/11536720/b324ac96-98e7-11e5-813a-4ad3ebd66e73.png)

**Comment by malcommac** [comment]
Seems to be a bug of Jazzy or CocoaPods. See https://github.com/CocoaPods/cocoadocs.org/issues/411
