### ISSUE TITLE
custom _sdLocalizeStringForValue?

### ISSUE THREAD

**Issue by AndrewSB** [malcommac/SwiftDate#90]
Can I have my own abbreviated versions of units in _sdLocalizeStringForValue? Could I instead choose a different table to lookup or something?

[relevant function](https://github.com/malcommac/SwiftDate/blob/master/SwiftDate/DateInRegion.swift#L1191)

**Comment by Hout** [comment]
Hmmm IMHO this should be resolved in the library in the future. Pls check out #65. That contains hints that can resolve your requirement.

**Comment by AndrewSB** [comment]
agree with it being implemented in the future @Hout, I'll try to use #65, but it should definitely be an option customizable through API

**Comment by malcommac** [comment]
we will continue discussion about this topic (pretty date formatting) in #79
