### ISSUE TITLE
UTCDate vs NSDate

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#91]
SwiftDate contains an `NSDate` object named `UTCDate`. The former is the Cocoa class for absolute time. IMHO the UTC naming creates confusion as UTC is not absolute time but a representation of it. The fact that NSDate is internally represented in seconds from 1-Jan-2001 00:00 UTC stands apart from the reasoning above.

I suggest naming the object `absoluteTime` or even `nsDate`.

**Comment by malcommac** [comment]
I agree, it's a necessary step to make the lib less confusing
