### ISSUE TITLE
How to change 1 months 2 week into  = 6 weeks.

### ISSUE THREAD

**Issue by rats083** [malcommac/SwiftDate#92]
Hey,

Please let me know how to change 1 months 2 weeks into 6 weeks.
3 months 1 week to = 13 weeks

I don;t want to use month and want to use months as a weeks.

Thanks,
Ratnesh Singh

**Comment by Hout** [comment]
Ratnesh, 1 month is not equal to 4 weeks. If I have a date for 22 November and add one month, I get 22 December. If I add four weeks, I get 20 December...
Your solution lies in using weeks, not months.
