### ISSUE TITLE
toString(.ISO0861) formats timezone incorrectly

### ISSUE THREAD

**Issue by danishin** [malcommac/SwiftDate#94]
Currently `NSDate().toString(.ISO8601)` returns something like `2015-12-06T10:02:26+0000` instead of `2015-12-06T10:02:26Z`.

I've looked into the source code and found that `String.ISO0861Formatter.dateFormatter` should be `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'` not `yyyy-MM-dd'T'HH:mm:ss.SSSZ` (note the quotes for `Z`).

I'm not sure what the standard is but currently SwiftDate fails to parse the current formattedString.

The following fails:
```
NSDate().toString(.ISO8601).toDate(.ISO8601) // nil
```

**Comment by NebulaFox** [comment]
Although I am not a developer on this, by the [ISO860](https://en.wikipedia.org/wiki/ISO_8601#Dates) standard +0000 for the timezone is correct.

But I want to second the fact that

    NSDate().toString(.ISO8601).toDate(.ISO8601) // nil

**Comment by NebulaFox** [comment]
I have a fix in my fork https://github.com/NebulaFox/SwiftDate and have the pull request https://github.com/malcommac/SwiftDate/pull/100

**Comment by danishin** [comment]
@NebulaFox Thanks for the pull request! I'm not too familiar with ISO standards so I was hoping someone would do it. Hope it gets merged soon :+1:

**Comment by Hout** [comment]
Shouldn't this one be closed?

**Comment by malcommac** [comment]
yeah it was closed
