### ISSUE TITLE
Make the default region the local region in all aspects

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#96]
When not doing regional conversions, the SwiftDate library should be easy to use with minimal extra commands.

Currently the default region contains the Gregorian calendar. This requires an extra command for users of other calendars to adopt SwiftDate as their local date library.

**Comment by redent** [comment]
This bugs a little bit. Had to add these lines to all my projects, where it seemed like the default config:

    let region = SwiftDate.Region(cal: NSCalendar.currentCalendar(), tz: NSTimeZone.defaultTimeZone(), loc: NSLocale.currentLocale())
    SwiftDate.Region.setDefaultRegion(region)

**Comment by Hout** [comment]
Indeed! That is superfluous code. Working on it!

**Comment by Hout** [comment]
Fixed in v3.0.0
