### ISSUE TITLE
No love for cocoa relative formatting

### ISSUE THREAD

**Issue by redent** [malcommac/SwiftDate#97]
In Swift 1.2 we had a parameter in `toString` method to enable `doesRelativeDateFormatting` flag in `NSDateFormatter`. That parameter is now gone and there's only one method to enable it:

	public func toRelativeCocoaString() -> String? {
		let formatter = NSDateFormatter()
		formatter.locale = region.locale
		formatter.calendar = region.calendar
		formatter.timeZone = region.timeZone
		formatter.dateStyle = .MediumStyle
		formatter.doesRelativeDateFormatting = true
		return formatter.stringFromDate(UTCDate)
	}

However this method forces `dateStyle` and `timeStyle` and create a new `NSDateFormatter` on each call. In addition. `NSDateFormatter.cachedFormatter()` is declared `internal`, so no other `DateInRegion` extensions can use it.

**Comment by malcommac** [comment]
Fixed in https://github.com/malcommac/SwiftDate/commit/d85c3bbbe1cc1e3be32a6a5bdd3f50d92ac2351d
Thanks
